/** @jest-environment jsdom */
import {act,cleanup,fireEvent,render,renderHook,screen,waitFor} from '@testing-library/react';
import {NextIntlClientProvider,useTranslations} from 'next-intl';
import es from '../../../../../messages/es.json';import en from '../../../../../messages/en.json';import fr from '../../../../../messages/fr.json';import pt from '../../../../../messages/pt.json';
import * as sequenceHooks from '../useSequences';
import {SecuenciasPage} from '../SecuenciasPage';
import {SequenceEditorDialog} from '../SequenceEditorDialog';
import {EnrollDialog} from '../EnrollDialog';
import {useSequenceText} from '../useSequenceText';
import {buildTimeline} from '@/lib/services/crm/sequenceTimeline';
let mockOrg=1;
jest.mock('@/lib/hooks/useOrganization',()=>({useOrganization:()=>({organization:mockOrg?{id:mockOrg}:null})}));
jest.mock('@/components/crm/shared/useCrmLookups',()=>({useCrmLookups:()=>({templates:[],pipelines:[],stages:[],sequences:[],customers:[],opportunities:[],loading:false,error:null,reload:jest.fn()})}));
jest.mock('@/lib/context/OrganizationTimezoneContext',()=>({useFormatDate:()=>({formatDateTime:(v:string)=>`TZ:${v}`})}));
const catalogs={es,en,fr,pt}, row:sequenceHooks.SequenceView={id:'11111111-1111-4111-8111-111111111111',name:'Secuencia ejemplo',description:null,trigger_type:'manual',is_active:true,pause_on_reply:true,exit_conditions:['won_lost'],steps:[{step_number:1,channel:'email',delay_days:0,action_config:{subject:'Asunto propio'}}],updated_at:'2026-10-02T00:00:00Z',enrollment_stats:{active:5,total:9,replied:2,response_rate:2/9}};
const summary:sequenceHooks.SequenceSummary={active_enrollments:300,paused_enrollments:27,replied_enrollments:13,meetings_30d:null,meetings_available:false,from:'2026-09-03T00:00:00Z',until:'2026-10-03T00:00:00Z',timezone:'America/Bogota'};
function mount(node:React.ReactNode,locale:keyof typeof catalogs='es',onError=jest.fn()){return render(<NextIntlClientProvider locale={locale} messages={catalogs[locale]} onError={onError}>{node}</NextIntlClientProvider>)}
const wrapper=({children}:{children:React.ReactNode})=><NextIntlClientProvider locale="es" messages={es}>{children}</NextIntlClientProvider>;
function Probe(){const tr=useSequenceText(),t=useTranslations('crm.secuencias');return <div>{Object.keys(es.crm.secuencias).map(key=><i key={key}>{t(key,{p0:'A',p1:'B',p2:'C',p3:'D',p4:'E'})}</i>)}<b>{buildTimeline([{step_number:1,channel:'call',delay_days:2}],tr)[0].dayLabel}</b></div>}
beforeAll(()=>{Object.defineProperty(window,'matchMedia',{writable:true,value:jest.fn().mockImplementation(()=>({matches:true,addEventListener:jest.fn(),removeEventListener:jest.fn()}))});});
beforeEach(()=>{mockOrg=1;jest.clearAllMocks();global.fetch=jest.fn().mockResolvedValue({ok:true,json:async()=>({data:[]})});});
afterEach(()=>{cleanup();jest.restoreAllMocks();});
it.each(['es','en','fr','pt'] as const)('muestra cifras canónicas, reunión desconocida y readonly en %s',locale=>{const onError=jest.fn(),toggle=jest.fn();jest.spyOn(sequenceHooks,'useSequences').mockReturnValue({sequences:[row],loading:false,error:null,canManage:false,summary,organizationId:1,reload:jest.fn(),save:jest.fn(),toggle,remove:jest.fn(),enroll:jest.fn()});mount(<><Probe/><SecuenciasPage/></>,locale,onError);expect(onError).not.toHaveBeenCalled();expect(screen.getByText('300')).toBeTruthy();expect(screen.getByText('27')).toBeTruthy();expect(screen.getByText('13')).toBeTruthy();expect(screen.getByText('—')).toBeTruthy();expect(screen.getByRole('note').textContent).toBe({es:'Las reuniones aún no están vinculadas a inscripciones; esta cifra no está disponible.',en:'Meetings are not yet linked to enrollments; this figure is unavailable.',fr:'Les réunions ne sont pas encore liées aux inscriptions ; ce chiffre est indisponible.',pt:'As reuniões ainda não estão vinculadas a inscrições; este número não está disponível.'}[locale]);expect(screen.getByRole('table')).toBeTruthy();const sw=screen.getByRole('switch') as HTMLButtonElement;expect(sw.disabled).toBe(true);fireEvent.click(sw);expect(toggle).not.toHaveBeenCalled();expect(screen.getByText({es:'Día 2',en:'Day 2',fr:'Jour 2',pt:'Dia 2'}[locale])).toBeTruthy();});
it('guardar tiene una sola mutación y bloquea campos hasta respuesta real',async()=>{let finish:(v:unknown)=>void=()=>{};const save=jest.fn().mockImplementation(()=>new Promise(resolve=>{finish=resolve;})),close=jest.fn();mount(<SequenceEditorDialog open sequence={row} onOpenChange={close} onSave={save}/>);const button=screen.getByRole('button',{name:'Guardar cambios'});fireEvent.click(button);fireEvent.click(button);expect(save).toHaveBeenCalledTimes(1);expect((screen.getByLabelText('Nombre') as HTMLInputElement).closest('fieldset')?.disabled).toBe(true);await act(async()=>{finish({id:row.id});});expect(close).toHaveBeenCalledWith(false);expect(save.mock.calls[0][0]).not.toHaveProperty('steps');});
it('inscripción exige preview actual y confirmación explícita de mensajes reales',async()=>{global.fetch=jest.fn().mockResolvedValue({ok:true,json:async()=>({data:{sequence:{is_active:true},steps:[{id:'step',step_number:1,channel:'email',delay_days:0,delay_hours:0,name:null}],candidates:[{id:'22222222-2222-4222-8222-222222222222',name:'Oportunidad ejemplo',amount:0,currency:null,customer_name:'Contacto',customer_email:'contacto@example.invalid',already_enrolled:false}]}})});const enroll=jest.fn().mockResolvedValue({enrolled:1,skipped:[]});mount(<EnrollDialog open sequence={row} onOpenChange={jest.fn()} onEnroll={enroll} onDone={jest.fn()}/>);await waitFor(()=>expect(screen.getByText('Oportunidad ejemplo')).toBeTruthy());fireEvent.click(screen.getByText('Oportunidad ejemplo'));const button=screen.getByRole('button',{name:'Confirmar inscripción y envíos'});expect((button as HTMLButtonElement).disabled).toBe(true);fireEvent.click(button);expect(enroll).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(button);await waitFor(()=>expect(enroll).toHaveBeenCalledTimes(1));expect(enroll).toHaveBeenCalledWith(row.id,'22222222-2222-4222-8222-222222222222');});
it('una respuesta atrasada de otra organización nunca reemplaza filas o capacidad',async()=>{let oldReply:(r:Response)=>void=()=>{};const second={...row,id:'33333333-3333-4333-8333-333333333333',name:'Secuencia actual'};global.fetch=jest.fn().mockImplementationOnce(()=>new Promise(resolve=>{oldReply=resolve;})).mockResolvedValue({ok:true,json:async()=>({data:[second],can_manage:false,summary})});const v=renderHook(()=>sequenceHooks.useSequences(),{wrapper});mockOrg=2;v.rerender();expect(v.result.current.sequences).toEqual([]);await waitFor(()=>expect(v.result.current.sequences).toEqual([second]));await act(async()=>{oldReply({ok:true,json:async()=>({data:[row],can_manage:true,summary})} as Response);});expect(v.result.current.sequences).toEqual([second]);expect(v.result.current.canManage).toBe(false);});
