/**
 * Pantalla del cliente del POS — núcleo compartido por la caja y /pos-display.
 * Ver docs/pos-doble-pantalla/PLAN.md.
 */

export * from './protocol';
export { projectCartForDisplay, type DisplayTotalsOverride, type ProjectCartOptions } from './projection';
export {
  DisplayEmitter,
  RAF_FALLBACK_MS,
  THANKS_DURATION_MS,
  cartLinesSignature,
  defaultScheduler,
  findChangedLineId,
  linesSignature,
  sameLines,
  type DisplayEmitterOptions,
  type DisplayEmitterStartOptions,
  type DisplaySessionInfo,
  type Scheduler,
  type TipPhase,
} from './emitter';
// F2-B: aritmética y saneado de la propina en pantalla, compartidos por la caja y /pos-display.
export {
  TIP_AMOUNT_LIMIT,
  TIP_CUSTOM_MAX_DIGITS,
  computeTipAmount,
  isAcceptableTipChoice,
  isValidTipPercent,
  resolveTipBase,
  resolveTipSelection,
  sanitizeDisplayTip,
  sanitizeTipAmount,
  tipOptions,
  type DisplayTipBlock,
  type TipOption,
  type TipSelection,
} from './tip';
export {
  QR_TEXT_MAX_CHARS,
  isImageSource,
  isQrPaymentCode,
  normalizeQrImageSource,
  parseExpiresAt,
  pickQrFromProviderResponse,
  qrTextFits,
  resolveCashReceived,
  resolveDisplayQr,
  toDisplayPayment,
  type CashReceivedEntry,
  type DisplayPaymentInput,
  type DisplayQr,
  type PickedProviderQr,
  type ResolveDisplayQrInput,
  type ResolvedDisplayQr,
} from './payment';
// settings.ts y posDisplay.ts NO se reexportan: tocan Supabase y la organización
// activa (solo navegador). Se importan por su ruta desde la caja.
export {
  BroadcastChannelReceiver,
  BroadcastChannelTransport,
  ADOPTION_WINDOW_MS,
  DISPLAY_LINK_ORIGINS,
  HEARTBEAT_INTERVAL_MS,
  STALE_AFTER_MS,
  combineDisplayCapabilities,
  createBroadcastDisplayChannel,
  displayChannelName,
  isBroadcastChannelSupported,
  toDisplayLinkOrigin,
  type BroadcastChannelReceiverOptions,
  type BroadcastChannelTransportOptions,
  type DisplayCapabilitiesByOrigin,
  type DisplayChannel,
  type DisplayChannelEvent,
  type DisplayChannelFactory,
  type DisplayLinkOrigin,
  type DisplayReceiver,
  type DisplaySeenByOrigin,
  type DisplayTransport,
  type HelloDraft,
} from './transport';
// Fase 3, parte C: un sobre por dos tubos (local + Supabase Broadcast) y compuerta de oyente remoto.
export {
  DEFAULT_LISTENER_GATE,
  REMOTE_LISTENER_TTL_MS,
  createFanOutDisplayChannel,
  createListenerGatedChannel,
  upMessageListenerGate,
  type DisplayChannelLeg,
  type FanOutDisplayChannel,
  type ListenerGate,
  type ListenerGateVerdict,
  type ListenerGatedChannel,
  type ListenerGatedChannelOptions,
} from './multiChannel';
export { SALIDA_ANTERIOR_TIMEOUT_MS, createCajaDisplayChannel, type CajaChannelDeps, type CajaDisplayChannel } from './cajaChannel';
export {
  REMOTE_SEEN_RECENT_MINUTES,
  formatCountdown,
  formatPairingCode,
  minutesSinceRemoteSeen,
  pairingRemainingMs,
  resolvePairingUrl,
} from './remotePairing';
// Fase 3 (parte B): transporte remoto (puro: el cliente de Supabase se inyecta) y
// formas del código/token. remoteDisplayClient.ts NO se reexporta: importa supabase-js.
export {
  DISPLAY_DOWN_EVENT,
  DISPLAY_UP_EVENT,
  // Ritmo del canal remoto (ronda 2 · 2): en Realtime cada mensaje se
  // factura, así que el latido de 1 s del transporte local NO vale aquí.
  REMOTE_BEAT_INTERVAL_MS,
  REMOTE_PRESENCE_INTERVAL_MS,
  REMOTE_STALE_AFTER_MS,
  SupabaseBroadcastReceiver,
  SupabaseBroadcastTransport,
  createSupabaseDisplayChannel,
  supabaseReceiverChannelFactory,
  supabaseTransportChannelFactory,
  type SupabaseBroadcastReceiverOptions,
  type SupabaseBroadcastTransportOptions,
  type SupabaseChannelLike,
  type SupabaseChannelStatus,
  type SupabaseClientLike,
} from './supabaseBroadcastTransport';
export { PAIRING_CODE_LENGTH, PAIRING_CODE_PATTERN, isDisplayTokenShape, isPairingCodeShape, normalizePairingCodeInput } from './pairing';
export {
  TERMINAL_ID_STORAGE_KEY,
  generateTerminalId,
  getOrCreateLocalTerminalId,
  isTerminalId,
  readLocalTerminalId,
  setLocalTerminalId,
  type TerminalIdStorage,
} from './terminal';
// Ruta de la pantalla y su detección desde el layout raíz (PWA, push): ver route.ts.
export { isCustomerDisplayPath } from './route';
// Parte D: indicador de la caja y tarjeta de Configuración › POS.
export {
  DEFAULT_PRESENCE_ENVIRONMENT,
  DEFAULT_STALE_BY_ORIGIN,
  DISCONNECTED_PRESENCE,
  DISCONNECTED_PRESENCE_VIEW,
  describePresenceOrigins,
  isDisplayPresent,
  isSamePresence,
  readDisplayPresence,
  readDisplayPresenceView,
  resolvePresenceReason,
  resolvePresentOrigins,
  staleForOrigin,
  withPresenceOrigins,
  type DisplayStaleByOrigin,
  type DisplayStaleThreshold,
  type DisplayPresenceEnvironment,
  type DisplayPresenceReason,
  type DisplayPresenceSnapshot,
  type DisplayPresenceSource,
  type DisplayPresenceView,
  type PresenceLook,
} from './presence';
export {
  CUSTOMER_DISPLAY_HINT_STORAGE_KEY,
  CUSTOMER_DISPLAY_ROUTE,
  CUSTOMER_DISPLAY_WINDOW_FEATURES,
  CUSTOMER_DISPLAY_WINDOW_NAME,
  canCloseViaNativeBridge,
  closeCustomerDisplay,
  getOpenedCustomerDisplayWindow,
  openCustomerDisplay,
  resolveNativePosDisplayApi,
  type CloseCustomerDisplayDeps,
  type CloseCustomerDisplayResult,
  type NativePosDisplayApi,
  type OpenCustomerDisplayDeps,
  type OpenCustomerDisplayResult,
} from './openDisplay';
export {
  DESKTOP_DISPLAY_ID_STORAGE_KEY,
  UNKNOWN_DISPLAY_CHOICE,
  describeDisplay,
  describeSelectedDisplay,
  describeWindowStatus,
  displayChoiceToPersist,
  enableDesktopDisplayHere,
  findDisplay,
  formatDisplayOption,
  getDesktopPosDisplayBridge,
  listDesktopDisplays,
  needsReopenForDisplayChange,
  nextOpenedAt,
  persistDesktopDisplayChoice,
  readDesktopDisplayStatus,
  readSavedDisplayChoice,
  readSavedDisplayId,
  resolveDesktopWindowSignal,
  resolveIndicatorState,
  resolveNothingToClose,
  resolveSelectedDisplayId,
  saveDisplayChoice,
  saveDisplayId,
  subscribeDesktopDisplayStatus,
  supportsDesktopDisplayPicker,
  supportsDesktopDisplayStatus,
  type CustomerDisplayIndicatorState,
  type DesktopDisplayPickerBridge,
  type DesktopStatusSource,
  type DesktopWindowSignal,
  type DisplayChoice,
  type DisplayDescription,
  type DisplayIdStorage,
  type SelectedDisplayView,
  type WindowStatusView,
} from './desktopDisplay';
