/// <reference types="jest" />
/** Canonical-session and RPC boundary contract; SQL transaction gate proves actual atomic writes. */
const {OrgContextError:MockOrgError}=jest.requireActual<typeof import('@/lib/utils/orgContextError')>('@/lib/utils/orgContextError');
const ID='10000000-0000-4000-8000-000000000001',OTHER='10000000-0000-4000-8000-000000000002',OP='20000000-0000-4000-8000-000000000001',LINK='30000000-0000-4000-8000-000000000001';
let denied=false,readError:unknown=null;const rpc=jest.fn();
const rows=[{id:ID,organization_id:120,title:'Price',category:'precio',is_active:true},{id:OTHER,organization_id:121,title:'Foreign',category:'precio',is_active:true}];
function fakeSupabase(){return{rpc,from:(table:string)=>{const filters:Record<string,unknown>={};const q:{[key:string]:unknown}={};q.select=()=>q;q.eq=(key:string,value:unknown)=>{filters[key]=value;return q;};q.order=()=>q;q.then=(resolve:(value:unknown)=>void)=>resolve({data:table==='objections'?rows.filter(row=>Object.entries(filters).every(([key,value])=>row[key as keyof typeof row]===value)):[],error:readError});return q;}};}
jest.mock('@/lib/utils/orgContext',()=>({OrgContextError:MockOrgError,getServerOrgContext:jest.fn(async()=>({organizationId:120,userId:'actor',roleId:3,isSuperAdmin:false,supabase:fakeSupabase()})),requireOrgAdminOrPermission:jest.fn(async()=>{if(denied)throw new MockOrgError('denied',403,'CRM_FORBIDDEN');})}));
import {NextRequest} from 'next/server';
import {GET as getList,POST as create} from '../route';
import {PATCH as patch,DELETE as archive} from '../[id]/route';
import {GET as getOpportunity,POST as register} from '../opportunity/[opportunityId]/route';
import {requireOrgAdminOrPermission} from '@/lib/utils/orgContext';
const request=(body:unknown,method='POST',query='')=>new NextRequest(`http://localhost/api/crm/objections${query}`,{method,body:JSON.stringify(body),headers:{'Content-Type':'application/json'}});
const params={params:Promise.resolve({id:ID})},opParams={params:Promise.resolve({opportunityId:OP})};
beforeEach(()=>{denied=false;readError=null;rpc.mockReset().mockResolvedValue({data:{id:ID},error:null});jest.mocked(requireOrgAdminOrPermission).mockClear();jest.spyOn(console,'error').mockImplementation(()=>{});jest.spyOn(console,'warn').mockImplementation(()=>{});});
afterEach(()=>jest.restoreAllMocks());
test('catalog read excludes other organizations and returns management permission',async()=>{const response=await getList(new NextRequest('http://localhost/api/crm/objections?includeInactive=true'));expect(response.status).toBe(200);expect(await response.json()).toEqual({success:true,data:[rows[0]],canManage:true});});
test('active members can consult without catalog edit permission',async()=>{denied=true;const response=await getList(new NextRequest('http://localhost/api/crm/objections'));expect(response.status).toBe(200);expect((await response.json()).canManage).toBe(false);});
test('database read error returns error, not an empty success',async()=>{readError={message:'unavailable'};expect((await getList(new NextRequest('http://localhost/api/crm/objections'))).status).toBe(500);});
test('create forwards only editable data and canonical organization',async()=>{const response=await create(request({organization_id:120,title:'Price',category:'precio',detection_signals:null}));expect(response.status).toBe(201);expect(rpc).toHaveBeenCalledWith('crm_objection_catalog_write',{p_org:120,p_id:null,p_expected:null,p_archive:false,p_data:{title:'Price',category:'precio',detection_signals:null}});});
test.each([{title:'x'},{category:'precio'},{title:'x',category:'precio',id:OTHER},{title:'x',category:'precio',sort_order:-1}])('create rejects malformed or forged fields %s',async(body)=>{expect((await create(request(body))).status).toBe(400);expect(rpc).not.toHaveBeenCalled();});
test.each(['organization_id','organizationId','org_id','orgId'])('foreign %s is rejected for every writer before RPC',async(key)=>{
 for(const fn of [()=>create(request({[key]:121,title:'x',category:'precio'})),()=>patch(request({[key]:121,is_active:false},'PATCH'),params),()=>archive(request({[key]:121},'DELETE'),params),()=>register(request({[key]:121,objection_id:ID}),opParams)]){expect((await fn()).status).toBe(403);}expect(rpc).not.toHaveBeenCalled();
});
test('query organization aliases cannot override any read or mutation',async()=>{expect((await getList(new NextRequest('http://localhost/api/crm/objections?orgId=121'))).status).toBe(403);expect((await getOpportunity(new NextRequest('http://localhost/x?org_id=121'),opParams)).status).toBe(403);expect((await register(request({objection_id:ID},'POST','?organizationId=121'),opParams)).status).toBe(403);expect(rpc).not.toHaveBeenCalled();});
test('catalog custom-role denial cannot be bypassed by writing directly',async()=>{denied=true;expect((await create(request({title:'x',category:'precio'}))).status).toBe(403);expect((await patch(request({is_active:false},'PATCH'),params)).status).toBe(403);expect((await archive(new NextRequest('http://localhost/x',{method:'DELETE'}),params)).status).toBe(403);expect(rpc).not.toHaveBeenCalled();});
test('patch binds version, ID and org; DELETE archives rather than erasing history',async()=>{await patch(request({is_active:false,expected_updated_at:'2026-10-01T00:00:00Z'},'PATCH'),params);expect(rpc.mock.calls[0]).toEqual(['crm_objection_catalog_write',{p_org:120,p_id:ID,p_expected:'2026-10-01T00:00:00Z',p_data:{is_active:false},p_archive:false}]);await archive(new NextRequest('http://localhost/x',{method:'DELETE'}),params);expect(rpc.mock.calls[1][1]).toMatchObject({p_id:ID,p_org:120,p_archive:true,p_data:{}});});
test('manual registration uses one RPC, ignores body opportunity and detection author',async()=>{const response=await register(request({objection_id:ID,opportunity_id:OTHER,detected_by:'ia',notes:'  demo  '}),opParams);expect(response.status).toBe(201);expect(rpc).toHaveBeenCalledTimes(1);expect(rpc).toHaveBeenCalledWith('crm_objection_register',{p_org:120,p_opportunity:OP,p_objection:ID,p_resolve:null,p_notes:'demo'});expect(requireOrgAdminOrPermission).toHaveBeenLastCalledWith(expect.objectContaining({organizationId:120}),'crm.opportunities.edit');});
test('resolution is bound to the opportunity in the route',async()=>{expect((await register(request({resolveId:LINK}),opParams)).status).toBe(200);expect(rpc).toHaveBeenCalledWith('crm_objection_register',{p_org:120,p_opportunity:OP,p_objection:null,p_resolve:LINK,p_notes:null});});
test.each([{objection_id:ID,notes:'x'.repeat(281)},{objection_id:ID,notes:42},{objection_id:'invalid'},{objection_id:ID,resolveId:LINK},{}])('invalid manual input never reaches SQL %s',async(body)=>{expect((await register(request(body),opParams)).status).toBe(400);expect(rpc).not.toHaveBeenCalled();});
test.each([['P0002',404],['42501',403],['40001',409]])('database code %s becomes HTTP %s',async(code,status)=>{rpc.mockResolvedValue({data:null,error:{code,message:'objecion_no_encontrada'}});expect((await register(request({objection_id:ID}),opParams)).status).toBe(status);});
