'use client';
import { useCallback, useEffect, useState } from 'react';
import { useTranslations } from 'next-intl';
import { EmptyState, FormField, StatusBadge } from '@/components/kit';
import { Clock, Ban, ShieldCheck } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { ALL_TOOL_NAMES } from '@/lib/services/crm/voiceAgentToolCatalog';
import { pedirCrm } from '@/components/crm/acciones/apiCrm';
import { isMandatoryTool, toggleAllowedTool, type AgentFormState } from './useAgentForm';
function JsonField({ label, value, onChange, onValidity }: { label: string; value: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void; onValidity: (valid: boolean) => void }) {
  const t = useTranslations('crm.agentesIa'); const [raw, setRaw] = useState(JSON.stringify(value, null, 2)); const [error, setError] = useState(false);
  return <label className="grid gap-1.5 text-sm text-fg">{label}<Textarea rows={3} value={raw} aria-invalid={error} onChange={e => { setRaw(e.target.value); try { const parsed: unknown = JSON.parse(e.target.value); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('object'); onChange(parsed as Record<string, unknown>); setError(false); onValidity(true); } catch { setError(true); onValidity(false); } }} />{error && <span role="alert" className="text-danger-text">{t('jsonError')}</span>}</label>;
}
export function AgentToolsTab({ form, patch, onJsonValidity }: { form: AgentFormState; patch: (value: Partial<AgentFormState>) => void; onJsonValidity: (key: string, valid: boolean) => void }) {
  const t = useTranslations('crm.agentesIa'); const [policy, setPolicy] = useState<string | null>(null); const [policyError, setPolicyError] = useState(false); const [policyLoading, setPolicyLoading] = useState(true); const [revision, setRevision] = useState(0); const reloadPolicy = useCallback(() => setRevision(value => value + 1), []);
  useEffect(() => { let alive = true; setPolicyLoading(true); setPolicyError(false); pedirCrm<{ data_policy_url: string | null }>('/api/crm/voice-agents/editor-context').then(result => { if (alive) setPolicy(result.data.data_policy_url); }).catch(() => { if (alive) setPolicyError(true); }).finally(() => { if (alive) setPolicyLoading(false); }); return () => { alive = false; }; }, [revision]);
  return <div className="space-y-5"><section aria-label={t('toolsTitle')} className="space-y-3"><h3 className="text-xs font-medium leading-4 text-fg-secondary">{t('toolsTitle')}</h3><div className="grid gap-x-6 gap-y-2 sm:grid-cols-2">
    {ALL_TOOL_NAMES.map(tool => <label key={tool} className="flex min-h-7 items-center gap-2 text-sm text-fg"><input type="checkbox" className="size-4 accent-brand" checked={isMandatoryTool(tool) || form.allowed_tools.includes(tool)} disabled={isMandatoryTool(tool)} onChange={e => patch({ allowed_tools: toggleAllowedTool(form.allowed_tools, tool, e.target.checked) })} /><span className="min-w-0 flex-1">{t.has(`tools.${tool}`) ? t(`tools.${tool}`) : tool}</span>{isMandatoryTool(tool) && <StatusBadge estado="mandatory" etiqueta={t('mandatory')} tono="advertencia" />}</label>)}
  </div></section><section aria-label={t('compliance')} className="space-y-3"><h3 className="text-xs font-medium leading-4 text-fg-secondary">{t('compliance')}</h3>
    {([{ key: 'law', icon: Clock, title: t('lawTitle'), description: t('lawDescription') }, { key: 'rne', icon: Ban, title: t('rneTitle'), description: t('rneDescription') }, { key: 'data', icon: ShieldCheck, title: t('dataPolicy'), description: t('guardrails') }]).map(({ key, icon: Icon, title, description }) => <div key={key} className="flex items-start gap-2 rounded-lg border border-line bg-subtle p-3"><Icon className="mt-0.5 size-4 shrink-0 text-brand-deep" strokeWidth={1.5} aria-hidden /><div className="min-w-0 flex-1"><p className="text-sm font-medium text-fg">{title}</p><p className="mt-1 text-[13px] leading-[18px] text-fg-secondary">{description}</p></div><StatusBadge estado="active" etiqueta={t('active')} tono="exito" /></div>)}
    <div className="grid gap-3 sm:grid-cols-2"><FormField etiqueta={t('callsDay')} tamanoEtiqueta="sm"><Input type="number" min={1} max={500} value={form.max_calls_per_day} onChange={e => patch({ max_calls_per_day: Number(e.target.value) })} /></FormField><FormField etiqueta={t('callsHour')} tamanoEtiqueta="sm"><Input type="number" min={1} max={500} value={form.max_calls_per_hour} onChange={e => patch({ max_calls_per_hour: Number(e.target.value) })} /></FormField></div>
    <p className="text-xs leading-4 text-fg-secondary">{t('dataPolicy')}: {policyLoading ? t('loading') : policyError ? t('loadError') : policy && /^https?:\/\//.test(policy) ? <a className="text-brand-action underline" href={policy} target="_blank" rel="noreferrer">{policy}</a> : t('policyMissing')}</p>
    {policyError && <EmptyState variante="error" titulo={t('loadError')} onReintentar={reloadPolicy} />}
    <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-[13px] text-fg-secondary">{t('advancedCompliance')}</summary><div className="mt-3 space-y-3"><JsonField label={t('transferRules')} value={form.transfer_to_human_rules} onChange={value => patch({ transfer_to_human_rules: value })} onValidity={valid => onJsonValidity('transfer', valid)} /><JsonField label={t('businessHours')} value={form.business_hours} onChange={value => patch({ business_hours: value })} onValidity={valid => onJsonValidity('hours', valid)} /></div></details>
  </section></div>;
}
