'use client';

/**
 * Textos de Páginas y de Menú y navegación (`sitioWeb.paginas.*`). `TEXTOS_PAGINAS` es el español
 * canónico (Figma A/04, D/04-09, D/04-10) y la fuente de `paginas.es.json`. Mientras el
 * integrador fusiona las claves en messages/*.json, `useTextosPaginas` muestra este español en
 * vez de la clave cruda (el patrón de `useTextosComun`).
 */
import { useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { interpolar } from '../ui/textos';

export const TEXTOS_PAGINAS = {
  lista: {
    subtitulo: '{n} páginas',
    subtituloUna: '1 página',
    subtituloCambios: '{n} páginas · {c} con cambios sin publicar',
    subtituloCambiosUna: '{n} páginas · 1 con cambios sin publicar',
    etiquetaTabla: 'Páginas del sitio',
    pestanas: 'Filtrar páginas',
    todas: 'Todas',
    enMenu: 'En el menú',
    ocultas: 'Ocultas',
    legales: 'Legales',
    menuYNavegacion: 'Menú y navegación',
    nuevaPagina: 'Nueva página',
    restaurarBase: 'Restaurar páginas base',
    verSitio: 'Ver sitio',
    irLegales: 'Ir a Configuración › Legales',
    masAcciones: 'Más acciones de Páginas',
    columnas: {
      pagina: 'Página',
      tipo: 'Tipo',
      estado: 'Estado',
      enMenu: 'En el menú',
      seo: 'SEO',
      actualizada: 'Actualizada',
    },
    piePagina: 'Pie de página',
    mostrarEnMenu: 'Mostrar «{nombre}» en el menú',
    editar: 'Editar',
    editarPagina: 'Editar «{nombre}»',
    soloLectura: 'Así se ve hoy tu sitio. Al hacer el primer cambio se crea un borrador: lo que veas aquí no cambia tu web hasta que publiques.',
    vacioTitulo: 'Aún no tienes páginas',
    vacioDescripcion: 'Crea la primera desde una plantilla o restaura las páginas base de tu giro ({lista}).',
    listaBase: '{paginas} y legales',
    vacioPestanaTitulo: 'Esta pestaña aún no tiene páginas',
    vacioPestanaDescripcion: 'Cambia de pestaña o crea una página nueva.',
    vacioLegalesDescripcion: 'Genera tus políticas en Configuración › Legales: aparecen aquí y en el pie de página.',
    errorTitulo: 'No pudimos cargar tus páginas',
    errorDescripcion: 'Tu sitio sigue en línea. Inténtalo de nuevo en unos segundos.',
    reintentar: 'Reintentar',
    sinPermisoTitulo: 'Solo puedes ver las páginas',
    sinPermisoDescripcion: 'Para crear, editar u ordenar páginas necesitas el permiso «Editar sitio web» (website.sites.edit).',
    avisoMovilTitulo: 'Para editar secciones, usa un computador',
    avisoMovilDescripcion: 'Aquí puedes cambiar textos, fotos y el orden del menú.',
    restauradas: 'Se añadieron {n} páginas base al borrador',
    restauradasNinguna: 'Ya tienes todas las páginas base',
    guardadoBorrador: 'Guardado en el borrador',
    noSePudo: 'No se pudo guardar el cambio',
    revertido: 'Volvimos a dejarlo como estaba.',
  },
  tipos: {
    inicio: 'Inicio (una página)',
    carta: 'Carta',
    carta_qr: 'Carta QR',
    reservas: 'Reservas',
    eventos: 'Eventos',
    nosotros: 'Nosotros',
    contacto: 'Contacto',
    sedes: 'Sedes',
    legal: 'Legal',
    galeria: 'Galería',
    servicios: 'Servicios',
    espacios: 'Habitaciones',
    productos: 'Productos',
    categorias: 'Categorías',
    ofertas: 'Ofertas',
    domicilios: 'Domicilios',
    consultar_pedido: 'Consultar pedido',
    membresias: 'Planes',
    personalizada: 'Página',
  },
  seo: {
    completo: 'Completo',
    falta_titulo: 'Falta título',
    falta_descripcion: 'Falta descripción',
    falta_imagen: 'Falta imagen al compartir',
    sin_revisar: 'Sin revisar',
  },
  fecha: {
    hoy: 'Hoy, {hora}',
    ayer: 'Ayer',
    sinFecha: 'Sin fecha',
  },
  acciones: {
    editar: 'Editar',
    editarTextos: 'Editar textos y fotos',
    editarSeo: 'Editar SEO',
    duplicar: 'Duplicar',
    sufijoCopia: '(copia)',
    cambiarDireccion: 'Cambiar dirección (URL)',
    ocultar: 'Ocultar del sitio',
    publicar: 'Volver a publicar en el sitio',
    mostrarEnMenu: 'Mostrar en el menú',
    quitarDelMenu: 'Quitar del menú',
    eliminar: 'Eliminar',
    menuYNavegacion: 'Menú y navegación',
    titulo: 'Acciones de «{nombre}»',
    duplicada: 'Página duplicada en el borrador',
    ocultada: '«{nombre}» ya no sale en el sitio cuando publiques',
    publicada: '«{nombre}» vuelve a salir en el sitio cuando publiques',
    eliminada: '«{nombre}» se eliminó del borrador',
    direccionCambiada: 'Dirección cambiada en el borrador',
    eliminarTitulo: '¿Eliminar «{nombre}»?',
    eliminarDescripcion: 'Se quita del borrador y de los menús. La web no cambia hasta que publiques; puedes recuperarla desde el historial del editor.',
    eliminarConfirmar: 'Eliminar página',
    direccionTitulo: 'Cambiar dirección',
    direccionDescripcion: 'Los enlaces que ya compartiste con la dirección anterior dejarán de funcionar cuando publiques.',
    direccionGuardar: 'Guardar dirección',
  },
  nueva: {
    titulo: 'Nueva página',
    descripcion: 'Empieza desde una plantilla de página: ya trae las secciones típicas y usa el estilo de tu sitio. Se crea en borrador.',
    plantillas: 'Plantillas de página',
    nombre: 'Nombre de la página',
    direccion: 'Dirección (URL)',
    mostrarEnMenu: 'Mostrar en el menú del encabezado',
    mostrarEnMenuAyuda: 'Puedes moverla después en Menú y navegación.',
    cancelar: 'Cancelar',
    crear: 'Crear página en borrador',
    creada: 'Página creada en el borrador',
    nombreObligatorio: 'Escribe el nombre de la página.',
    direccionObligatoria: 'Escribe la dirección de la página.',
    direccionRepetida: 'Ya existe una página con esta dirección',
    direccionDeSede: 'Esa dirección es la de una sede publicada. Elige otra',
    direccionInvalida: 'Usa solo letras sin tildes, números y guiones.',
    plantilla: {
      inicio: 'Inicio (una página)',
      carta: 'Carta',
      carta_qr: 'Carta QR',
      reservas: 'Reservas',
      eventos: 'Eventos',
      nosotros: 'Nosotros',
      sedes: 'Sedes',
      contacto: 'Contacto',
      servicios: 'Servicios',
      productos: 'Productos',
      habitaciones: 'Habitaciones',
      planes: 'Planes',
      galeria: 'Galería',
      preguntas: 'Preguntas frecuentes',
      legal: 'Legal',
      en_blanco: 'En blanco',
    },
    nombreSugerido: {
      inicio: 'Inicio',
      carta: 'Carta',
      carta_qr: 'Carta QR',
      reservas: 'Reservas',
      eventos: 'Eventos',
      nosotros: 'Nosotros',
      sedes: 'Sedes',
      contacto: 'Contacto',
      servicios: 'Servicios',
      productos: 'Productos',
      habitaciones: 'Habitaciones',
      planes: 'Planes',
      galeria: 'Galería',
      preguntas: 'Preguntas frecuentes',
      legal: 'Términos y condiciones',
      en_blanco: 'Nueva página',
    },
  },
  conflicto: {
    titulo: 'Alguien guardó cambios antes que tú',
    descripcion: 'Otra persona o pestaña guardó una versión más nueva del borrador. Recarga para ver sus cambios; los tuyos no se guardaron.',
    recargar: 'Recargar',
  },
  menu: {
    titulo: 'Menú y navegación',
    migaPaginas: 'Páginas',
    subtitulo: 'Encabezado y pie de página · se guardan en el borrador',
    subtituloSedes: 'Menús de cada sitio · el selector de sitio del editor decide cuáles ves',
    subtituloMega: 'Megamenú de «{nombre}» · arrastra categorías del Inventario · se guarda en el borrador',
    vistaPrevia: 'Vista previa',
    guardar: 'Guardar en borrador',
    guardado: 'Menús guardados en el borrador',
    restablecer: 'Restablecer desde el principal',
    verHistorial: 'Ver historial en el editor',
    masAcciones: 'Más acciones del menú',
    encabezado: 'Encabezado',
    arrastrar: 'Arrastra para ordenar',
    arrastrarAnidar: 'Arrastra para ordenar o anidar',
    piePagina: 'Pie de página',
    anadirEnlace: 'Añadir enlace',
    anadirGrupo: 'Añadir grupo',
    grupoNuevo: 'Grupo nuevo',
    sinEncabezado: 'El encabezado aún no tiene menú. Añade el primer enlace.',
    sinPie: 'El pie aún no tiene grupos de enlaces.',
    grupoVacio: 'Este grupo no tiene enlaces.',
    ocultoEnMenu: 'Oculto en el menú · la página sigue publicada',
    soltarAqui: 'Soltar aquí: {nombre}',
    soltarRaiz: 'Soltar aquí para dejarlo en el primer nivel',
    detalle: {
      pagina: 'Página · {ruta}',
      subpagina: 'Sub-página · {ruta}',
      desplegable: 'Desplegable · {n} sub-páginas',
      categoria: 'Categoría del Inventario · {n} productos',
      categoriaSinConteo: 'Categoría del Inventario',
      categoriasSubmenu: 'Página · {ruta} · categorías del Inventario',
      externo: 'Enlace externo · {url}',
      whatsapp: 'WhatsApp · {url}',
      telefono: 'Teléfono · {url}',
      ancla: 'Ancla de página',
      sitio: 'Enlace a otro sitio',
    },
    accion: {
      subir: 'Subir',
      bajar: 'Bajar',
      moverA: 'Mover a…',
      quitar: 'Quitar del menú',
      renombrar: 'Renombrar',
    },
    moverTitulo: 'Mover «{nombre}»',
    moverDescripcion: 'Elige dónde va el enlace. El menú admite hasta tres niveles.',
    moverRaiz: 'Primer nivel del menú',
    moverDentro: 'Dentro de «{nombre}»',
    moverConfirmar: 'Mover aquí',
    profundidad: 'El menú admite hasta tres niveles.',
    ciclo: 'Un enlace no puede ir dentro de sí mismo.',
    limiteItems: 'Este menú llegó al máximo de enlaces.',
    salirTitulo: '¿Salir sin guardar?',
    salirDescripcion: 'Tienes cambios en los menús que aún no se guardaron en el borrador.',
    salirConfirmar: 'Salir sin guardar',
    sinCambios: 'Sin cambios',
    cambiosSinGuardar: 'Tienes cambios sin guardar',
    errorTitulo: 'No pudimos cargar los menús',
    sinPermisoTitulo: 'Solo puedes ver los menús',
    sinPermisoDescripcion: 'Para ordenar o crear menús necesitas el permiso «Editar sitio web» (website.sites.edit).',
    soloLecturaTitulo: 'Así están hoy los menús de tu sitio',
    soloLecturaDescripcion: 'Para editarlos se crea un borrador con lo que ves; tu web no cambia hasta que publiques.',
    empezarEdicion: 'Empezar a editar',
    vistaPreviaError: 'No se pudo abrir la vista previa',
    vistaPreviaSinDireccion: 'Tu sitio aún no tiene dirección. Configúrala en Dominios.',
  },
  inspector: {
    titulo: 'Enlace · {nombre}',
    tituloVacio: 'Enlace',
    vacio: 'Elige un enlace del encabezado o del pie para editarlo.',
    texto: 'Texto del enlace',
    llevaA: 'Al hacer clic lleva a',
    tipoDestino: 'Tipo de destino',
    destino: {
      pagina: 'Página',
      categoria: 'Categoría del Inventario',
      externo: 'Enlace externo',
      whatsapp: 'WhatsApp',
      telefono: 'Teléfono',
    },
    pagina: 'Página · {nombre} ({ruta})',
    elegirPagina: 'Elige una página',
    elegirCategoria: 'Elige una categoría',
    url: 'Dirección del enlace',
    numero: 'Número',
    numeroAyuda: 'Con indicativo, por ejemplo +57 300 123 4567.',
    nuevaPestana: 'Abrir en una pestaña nueva',
    categoriasSubmenu: 'Mostrar categorías de la carta como submenú (de Inventario)',
    categoriasSubmenuTienda: 'Mostrar categorías como submenú (de Inventario)',
    editarCategorias: 'Editar categorías en Inventario',
    tipoEnlace: 'Tipo de enlace',
    tipos: { enlace: 'Enlace', desplegable: 'Desplegable', megamenu: 'Megamenú' },
    columnas: 'Columnas del megamenú',
    autollenar: 'Llenar con las categorías del Inventario',
    autollenarAyuda: 'Las nuevas categorías aparecen solas',
    imagenCategoria: 'Mostrar imagen de cada categoría',
    destacado: 'Destacado a la derecha',
    icono: 'Icono',
    iconos: { ninguno: 'Ninguno', cubiertos: 'Cubiertos', etiqueta: 'Etiqueta', estrella: 'Estrella' },
    insignia: 'Insignia (opcional)',
    insigniaAyuda: 'Máximo 12 caracteres. Se muestra junto al enlace.',
    proximamente: 'Próximamente',
    proximamenteAyuda: 'El sitio público aún no muestra estas opciones del megamenú. Se activan cuando lo haga; hoy el submenú sale como desplegable.',
    quitar: 'Quitar del menú',
  },
  categorias: {
    titulo: 'Categorías del Inventario',
    activas: '{n} activas',
    ayuda: 'Arrástralas al árbol o tócalas con +. Se leen del Inventario: si cambias una categoría allá, el menú se actualiza solo.',
    enMenu: 'En el menú',
    anadir: 'Añadir «{nombre}» al menú',
    productos: '{n} productos',
    productoUno: '1 producto',
    subcategorias: '{n} sub',
    inactiva: 'inactiva',
    soloSede: 'solo en esta sede',
    crearEditar: 'Crear o editar categorías en Inventario',
    vacio: 'Aún no tienes categorías en el Inventario.',
    error: 'No pudimos cargar las categorías.',
    reintentar: 'Reintentar',
  },
  sedes: {
    menusDe: 'Menús de {nombre}',
    menusSitio: 'Menús del sitio',
    sitioPrincipal: 'Sitio principal',
    nuevoMenu: 'Nuevo menú',
    propio: 'Sitio propio · lo que cambies aquí no afecta al principal, y viceversa.',
    hereda: 'Hereda el sitio principal: estos son los menús del principal, de solo lectura. Si el principal los cambia, aquí cambian.',
    personalizar: 'Personalizar en esta sede',
    personalizarAyuda: 'Copia los menús del principal a {nombre}; desde ahí son propios.',
    personalizado: 'La sede ya tiene sus propios menús',
    restablecerTitulo: '¿Restablecer los menús de {nombre}?',
    restablecerDescripcion: 'Se reemplazan por los del sitio principal. Los cambios propios de esta sede se pierden al guardar.',
    restablecerConfirmar: 'Restablecer',
    copiado: 'copiado del principal',
    editado: 'editado en {nombre}',
    soloAqui: 'Solo existe en {nombre}',
    delPrincipal: 'del sitio principal',
    enlaces: '{n} enlaces',
    enlaceUno: '1 enlace',
    ubicacion: {
      encabezado: 'Encabezado',
      megamenu: 'Megamenú',
      pie: 'Pie · columna {n}',
      sin: 'Sin ubicación',
    },
    acciones: {
      editar: 'Editar enlaces',
      renombrar: 'Renombrar',
      cambiarUbicacion: 'Cambiar ubicación',
      duplicar: 'Duplicar',
      eliminar: 'Eliminar',
    },
    eliminarTitulo: '¿Eliminar el menú «{nombre}»?',
    eliminarDescripcion: 'Se quita del borrador; las páginas no se borran.',
    eliminarConfirmar: 'Eliminar menú',
    renombrarTitulo: 'Renombrar menú',
    nombre: 'Nombre',
    guardarNombre: 'Guardar nombre',
    guardarUbicacion: 'Guardar ubicación',
    ubicacionTitulo: 'Dónde se muestra «{nombre}»',
    copiaDe: '{nombre} (copia)',
  },
  nuevoMenu: {
    titulo: 'Nuevo menú',
    nombre: 'Nombre',
    donde: 'Dónde se muestra',
    opciones: {
      encabezado: 'Encabezado',
      megamenu: 'Megamenú de un enlace',
      pie: 'Pie de página',
      sin: 'Sin ubicación',
    },
    columna: 'Columna {n} del pie',
    seCreaEn: 'Se crea en: {nombre} (el sitio elegido arriba).',
    anadirEnlace: 'Añadir enlace',
    tipos: {
      pagina: 'Página',
      paginaAyuda: 'Inicio, Carta, Reservas…',
      categoria: 'Categoría del Inventario',
      categoriaAyuda: 'Se actualiza sola con el Inventario',
      externo: 'Enlace externo',
      externoAyuda: 'Otra web, PDF o red social',
      contacto: 'WhatsApp o teléfono',
      contactoAyuda: 'Abre el chat o la llamada',
    },
    cancelar: 'Cancelar',
    crear: 'Crear menú',
    creado: 'Menú «{nombre}» creado. Guarda para conservarlo.',
    reemplazaEncabezado: 'Reemplaza al menú actual del encabezado.',
    errores: {
      nombre_vacio: 'Escribe el nombre del menú.',
      limite_menus: 'El sitio llegó al máximo de 20 menús.',
      limite_columnas_pie: 'El pie admite hasta 10 columnas.',
      limite_items: 'El menú llegó al máximo de enlaces.',
      menu_no_existe: 'El menú ya no existe.',
    },
  },
} as const;

type Hoja = string;
type Arbol = { readonly [k: string]: Hoja | Arbol };

export function textoPaginas(clave: string): string | undefined {
  let nodo: Hoja | Arbol | undefined = TEXTOS_PAGINAS as unknown as Arbol;
  for (const parte of clave.split('.')) {
    if (!nodo || typeof nodo === 'string') return undefined;
    nodo = (nodo as Arbol)[parte];
  }
  return typeof nodo === 'string' ? nodo : undefined;
}

export type TraductorPaginas = (clave: string, valores?: Record<string, string | number>) => string;

/** Textos de `sitioWeb.paginas.*` en el idioma activo, con el español canónico de respaldo. */
export function useTextosPaginas(): TraductorPaginas {
  const t = useTranslations('sitioWeb');
  return useCallback(
    (clave: string, valores?: Record<string, string | number>) => {
      const completa = `paginas.${clave}`;
      if (t.has(completa)) return t(completa, valores);
      const canon = textoPaginas(clave);
      return canon === undefined ? clave : interpolar(canon, valores);
    },
    [t],
  );
}
