export { LiveVisitorsBadge } from './LiveVisitorsBadge';
export { useLiveVisitors } from './useLiveVisitors';
export { LazySection } from './LazySection';
export { HorasPresets } from './HorasPresets';
export { default as DashboardModulos } from './DashboardModulos';
export { EmployeeDashboard } from './EmployeeDashboard';
export { ModoCompactoContext } from './DashboardModulos';
export { default as ModuloSection } from './ModuloSection';
export type { ModuloSectionProps } from './ModuloSection';
export { default as FinanzasSection } from './sections/FinanzasSection';
export { default as InventarioSection } from './sections/InventarioSection';
export { default as PosSection } from './sections/PosSection';
export { default as CrmSection } from './sections/CrmSection';
export { default as PmsSection } from './sections/PmsSection';
export { default as HrmSection } from './sections/HrmSection';
export { default as GymSection } from './sections/GymSection';
export { default as ParkingSection } from './sections/ParkingSection';
export { default as TransporteSection } from './sections/TransporteSection';
export { default as PmSection } from './sections/PmSection';
export { default as NotificacionesSection } from './sections/NotificacionesSection';
export { default as IntegracionesSection } from './sections/IntegracionesSection';
export { default as CalendarioSection } from './sections/CalendarioSection';
export { default as TimelineSection } from './sections/TimelineSection';
export { default as ChatSection } from './sections/ChatSection';
export { default as ModuleRootRedirect } from './ModuleRootRedirect';
