/** @jest-environment jsdom */
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { NextIntlClientProvider, useTranslations } from 'next-intl';
import es from '../../../../../messages/es.json'; import en from '../../../../../messages/en.json'; import fr from '../../../../../messages/fr.json'; import pt from '../../../../../messages/pt.json';
import { RulesTable } from '../RulesTable';
import { BulkDryRunPreview } from '../BulkDryRunPreview';
import { RuleEditorSheet } from '../RuleEditorSheet';
import { RuleDeleteDialog } from '../RuleDeleteDialog';
import type { RuleLookups } from '../useRuleLookups';
import type { AutomationRuleView } from '../useAutomationRules';
import { useAutomationText } from '../useAutomationText';
const catalogs={es,en,fr,pt};
jest.mock('@/lib/context/OrganizationTimezoneContext',()=>({useFormatDate:()=>({formatDateTime:(v:string)=>`TZ:${v}`})}));
const rule:AutomationRuleView={id:'11111111-1111-4111-8111-111111111111',name:'Regla ejemplo',description:null,trigger_type:'manual',event:null,pipeline_id:null,stage_id:null,is_active:true,priority:10,run_once_per_opportunity:true,cooldown_hours:0,actions:[],conditions:null,last_run_at:null,runs_count:876,updated_at:'2026-10-02T00:00:00Z'};
const preview={from:'2026-09-02T23:00:00Z',until:'2026-10-02T23:00:00Z',data_basis:'current_records' as const,total:307,matched:91,skipped:214,unavailable:2,sample:[]};
const lookups={loading:false,error:null,pipelines:[],stages:[],sequences:[],templates:[],customers:[],opportunities:[],agents:[],reload:jest.fn(),humanizer:{}} as unknown as RuleLookups;
function mount(node:React.ReactNode,locale:keyof typeof catalogs='es'){return render(<NextIntlClientProvider locale={locale} messages={catalogs[locale]}>{node}</NextIntlClientProvider>)}
function IntlProbe(){const tr=useAutomationText(),t=useTranslations('crm.automatizaciones');return <div><span>{tr('Enviar email')}</span><span>{tr('con al menos {p0} h entre ejecuciones',{p0:7})}</span>{Object.keys(es.crm.automatizaciones).map(key=><i key={key}>{t(key,{p0:'A',p1:'B',p2:'C',p3:'D'})}</i>)}</div>}
beforeAll(()=>{Object.defineProperty(window,'matchMedia',{writable:true,value:jest.fn().mockImplementation(()=>({matches:true,addEventListener:jest.fn(),removeEventListener:jest.fn()}))});});
afterEach(cleanup);
it.each(['es','en','fr','pt'] as const)('mensajes ICU completos y prueba de 30 días reales en %s',locale=>{const onError=jest.fn();render(<NextIntlClientProvider locale={locale} messages={catalogs[locale]} onError={onError}><IntlProbe/><BulkDryRunPreview result={preview} loading={false} error={null} onRetry={jest.fn()}/></NextIntlClientProvider>);expect(onError).not.toHaveBeenCalled();expect(screen.getByText('TZ:2026-09-02T23:00:00Z – TZ:2026-10-02T23:00:00Z')).toBeTruthy();expect(screen.getAllByRole('status').some(e=>/307.*91.*214.*2/.test(e.textContent ?? ''))).toBe(true);expect(document.body.textContent).toContain('{{customer_name}}');});
it('el servidor controla capacidades de tabla y conserva historial de solo lectura',()=>{const toggle=jest.fn();mount(<RulesTable rules={[rule]} lookups={{}} canManage={false} togglingId={null} formatDate={v=>v??'—'} onToggle={toggle} onEdit={jest.fn()} onDryRun={jest.fn()} onHistory={jest.fn()} onDelete={jest.fn()}/>);const sw=screen.getByRole('switch') as HTMLButtonElement;expect(sw.disabled).toBe(true);fireEvent.click(sw);expect(toggle).not.toHaveBeenCalled();expect(screen.getByText('876')).toBeTruthy();});
it('probar usa regla guardada; cambios pendientes bloquean la simulación anterior',async()=>{const run=jest.fn().mockResolvedValue(preview);mount(<RuleEditorSheet open rule={rule} lookups={lookups} onOpenChange={jest.fn()} onSave={jest.fn()} onBulkDryRun={run}/>);const test=screen.getByRole('button',{name:'Probar en seco'});expect((test as HTMLButtonElement).disabled).toBe(false);fireEvent.click(test);await waitFor(()=>expect(run).toHaveBeenCalledWith(rule.id));await waitFor(()=>expect(screen.getAllByRole('status').some(e=>e.textContent?.includes('307'))).toBe(true));fireEvent.change(screen.getByLabelText('Nombre de la regla'),{target:{value:'Regla cambiada'}});expect((test as HTMLButtonElement).disabled).toBe(true);fireEvent.click(test);expect(run).toHaveBeenCalledTimes(1);});
it('una confirmación rechazada conserva el diálogo sin rechazo sin manejar',async()=>{const close=jest.fn(),remove=jest.fn().mockRejectedValue(new Error('Servidor no disponible'));mount(<RuleDeleteDialog open loading={false} title="Eliminar regla" description="Confirma el borrado" confirmLabel="Eliminar" onOpenChange={close} onConfirm={remove} onCloseAutoFocus={jest.fn()}/>);await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Eliminar'}));});expect(remove).toHaveBeenCalledTimes(1);expect(close).not.toHaveBeenCalled();expect(screen.getByRole('alertdialog')).toBeTruthy();});
