'use client';

/**
 * Textos del Resumen (`sitioWeb.resumen.*`) y del asistente de creación
 * (`sitioWeb.asistente.*`). `TEXTOS_RESUMEN` es el español canónico (Figma
 * A/02 y A/03) y la fuente de resumen.es.json. Mientras el integrador fusiona
 * las claves en messages/*.json, `useTextosResumen` muestra este español en vez
 * de la clave cruda (el patrón de `useTextosComun`).
 */
import { useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { interpolar } from '../ui/textos';

export const TEXTOS_RESUMEN = {
  resumen: {
    nombreContenido: 'el resumen del sitio',
    errorTitulo: 'No pudimos cargar el resumen del sitio',
    errorDescripcion: 'Tu sitio sigue en línea. Revisa la conexión e inténtalo de nuevo; si continúa, escríbenos.',
    sinPermisoDescripcion: 'Pide a un administrador de tu organización acceso al sitio web. Editar y publicar son permisos aparte.',
    sinPermisoEditar: 'Pide el permiso «Editar sitio web»',
    sinPermisoPublicar: 'Pide el permiso «Publicar sitio web»',
    menu: {
      copiarEnlace: 'Copiar enlace',
      codigoQr: 'Código QR',
      cambiarPlantilla: 'Cambiar plantilla',
      irConfiguracion: 'Ir a Configuración',
    },
    tarjeta: {
      titulo: 'Tu sitio',
      dominioPrincipal: 'Dominio principal',
      direccionGratis: 'Dirección gratis de GO Admin',
      tambienResponde: 'también responde en {host}',
      sinDireccion: 'Aún no tiene dirección. Configúrala en Dominios.',
      copiarEnlace: 'Copiar enlace',
      codigoQr: 'Código QR',
      verSitio: 'Ver sitio',
      compartir: 'Compartir',
      plantilla: 'Plantilla',
      ultimaPublicacion: 'Última publicación',
      cambiosBorrador: 'Cambios en borrador',
      nunca: 'Aún no publicas',
      sinCambios: 'Ninguno',
      publicarCambios: 'Publicar cambios',
      revisarCambios: 'Revisar cambios',
      publicadoLegacy: 'Publicado',
      enlaceCopiado: 'Enlace copiado',
      noSeCopio: 'No pudimos copiar el enlace. Cópialo a mano: {url}',
      publicado: 'Publicaste los cambios. Tu sitio está al día.',
      errorPublicar: 'No pudimos publicar: {mensaje}',
      conflicto: 'Otra persona guardó o publicó una versión más nueva. Recargamos el resumen para que veas lo último.',
      autorFecha: '{fecha} · {autor}',
      vistaPrevia: 'Vista previa de {host}',
    },
    areas: {
      pagina: '{titulo}',
      tema: 'estilo del sitio',
      identidad: 'logo y nombre',
      seo: 'SEO',
      contenido: 'datos del negocio',
      menus: 'menús',
      shell: 'encabezado y pie',
      y: '{lista} y {ultimo}',
    },
    lanzamiento: {
      titulo: 'Lista de lanzamiento',
      progreso: '{n} de {total}',
      progresoPasos: '{n} de {total} pasos',
      casiListo: 'Tu sitio está casi listo',
      todoListo: 'Tu sitio está listo',
      empezando: 'Empieza por la plantilla',
      etiquetaBarra: 'Avance de la lista de lanzamiento',
      pasos: {
        plantilla: 'Plantilla',
        estilo: 'Estilo del sitio',
        datos: 'Logo y datos del negocio',
        carta: 'Carta',
        catalogo: 'Catálogo',
        pagos: 'Pagos en línea',
        dominio: 'Dominio',
        publicar: 'Publicar',
      },
      plantillaListo: '{nombre}',
      plantillaPendiente: 'Elige la base de tu sitio',
      estiloDetalle: 'Colores, tipografía y botones',
      datosListo: 'Tomados de Organización',
      datosListoSede: 'Tomados de Organización y de {sede}',
      datosPorConfirmar: 'Ya tenemos tu logo y tu horario',
      datosFaltaLogo: 'Ya tenemos tu nombre; falta el logo',
      datosFaltaContacto: 'Falta un teléfono o WhatsApp de contacto',
      cartaListo: '{productos} platos de Inventario · {categorias} categorías',
      cartaPendiente: 'Tus platos de Inventario',
      catalogoListo: '{productos} productos de Inventario · {categorias} categorías',
      catalogoPendiente: 'Tus productos de Inventario',
      pagosListo: 'Pasarela conectada',
      pagosPendiente: 'Conecta una pasarela para cobrar en el sitio',
      pagosOpcional: 'Opcional',
      dominioPropio: '{host} · activo con HTTPS',
      dominioGratis: 'Dirección gratis de GO Admin, con HTTPS',
      dominioPendiente: 'Elige dónde vivirá tu sitio',
      publicarListo: 'Todo publicado',
      publicarCambios: '{n} cambios esperan publicación',
      publicarNunca: 'Publica la primera versión',
    },
    kpis: {
      etiqueta: 'Cifras del sitio en los últimos 7 días',
      visitas: 'Visitas · 7 días',
      visitasCorta: 'Visitas · 7 días',
      pedidos: 'Pedidos web · 7 días',
      pedidosCorta: 'Pedidos web',
      reservas: 'Reservas web · 7 días',
      reservasCorta: 'Reservas web',
      conversion: 'Conversión',
      conversionDetalle: 'Visitas que terminan en pedido o reserva',
      conversionDetallePedidos: 'Visitas que terminan en pedido',
      variacion: '{signo}{valor} % frente a la semana anterior',
      verPedidos: 'Ver en POS › Pedidos online',
      verReservas: 'Ver en POS › Reservas de mesas',
      disponibleAlPublicar: 'Disponible cuando publiques',
      sinAcceso: 'Sin acceso a ventas',
      sinDato: '—',
    },
    alertas: {
      titulo: 'Alertas',
      malConfiguradoTitulo: '{host} está mal configurado',
      malConfiguradoDescripcion: 'Los registros DNS no apuntan a GO Admin: esa dirección no abre tu sitio.',
      verificandoDescripcion: 'Aún estamos verificando los registros DNS. Si ya los cambiaste, puede tardar unas horas.',
      verDns: 'Ver registros DNS',
      venceTitulo: '{host} vence en {n} días',
      venceUnDiaTitulo: '{host} vence mañana',
      vencidoTitulo: '{host} está vencido',
      venceDescripcion: 'La renovación automática está apagada. Si vence, el sitio deja de abrir en esa dirección.',
      renovar: 'Renovar',
      sinPasarelaTitulo: 'Aún no recibes pagos en línea',
      sinPasarelaDescripcion: 'Tus clientes solo pueden pagar al recibir. Conecta una pasarela de pago.',
      conectarPasarela: 'Conectar pasarela',
    },
    cambios: {
      titulo: 'Cambios recientes',
      verHistorial: 'Ver historial',
      vacio: 'Aún no hay cambios. Cuando edites o publiques, aparecerán aquí.',
      editoBorrador: 'Editó el borrador',
      editoPagina: 'Editó «{pagina}»',
      edito_tema: 'Cambió el estilo del sitio',
      edito_identidad: 'Cambió el logo o el nombre',
      edito_seo: 'Cambió el SEO del sitio',
      edito_contenido: 'Cambió los datos del negocio',
      edito_menus: 'Cambió los menús',
      edito_shell: 'Cambió el encabezado o el pie',
      publicoUno: 'Publicó 1 cambio',
      publicoN: 'Publicó {n} cambios',
      publicoVersion: 'Publicó la versión {n}',
      publicoNota: 'Publicó: {nota}',
      restauro: 'Restauró una versión anterior',
      guardadoBorrador: 'Guardado en borrador',
      publicado: 'Publicado',
      hoy: 'Hoy, {hora}',
      ayer: 'Ayer, {hora}',
    },
    movil: {
      editorTitulo: 'El editor completo está en el computador',
      editorDescripcion: 'Desde aquí cambias textos, fotos y horarios al instante.',
      cambiosRapidos: 'Cambios rápidos',
      compartirTitulo: 'Compartir tu sitio',
    },
    qr: {
      titulo: 'Código QR de tu sitio',
      descripcion: 'Imprímelo en tu local, tus empaques o tus redes. Abre {host}.',
      descargar: 'Descargar PNG',
      cerrar: 'Cerrar',
    },
    revisar: {
      titulo: 'Cambios sin publicar',
      descripcion: 'Esto cambia en tu sitio cuando publiques.',
      nueva: 'Página nueva',
      editada: 'Página editada',
      quitada: 'Página quitada',
      global: 'Todo el sitio',
      vacio: 'No hay cambios sin publicar.',
      abrirEditor: 'Abrir editor',
      publicar: 'Publicar cambios',
    },
    primeraVez: {
      titulo: 'Tu sitio está a 6 pasos de estar en línea',
      descripcion:
        'Elige una plantilla para tu giro, ajusta el estilo y publica. Usamos tu logo, el horario de tu sede y la carta de Inventario: no escribes nada dos veces.',
      descripcionMovil: 'Plantilla, estilo, datos, dominio y publicar. Puedes hacerlo desde el celular.',
      empezar: 'Empezar configuración',
      seguir: 'Seguir donde ibas',
      seguirPaso: 'Vas en el paso {n} de 6',
      verPlantillas: 'Ver plantillas',
      pie: 'Unos 10 minutos · puedes salir y seguir después: el avance se guarda.',
      pieMovil: 'Unos 10 minutos · el avance se guarda.',
      recomendadas: 'Plantillas recomendadas para tu giro',
      pasoHecho: 'hecho',
    },
  },
  asistente: {
    marca: 'GO Admin',
    titulo: 'Configura tu sitio web',
    guardarSalir: 'Guardar y salir',
    cerrar: 'Cerrar el asistente',
    atras: 'Atrás',
    siguiente: 'Siguiente',
    pasoDe: 'Paso {n} de {total}',
    resumenPaso: 'Paso {n} de {total} · {etiqueta}',
    etiquetaStepper: 'Pasos de la configuración del sitio',
    vistaPrevia: 'Vista previa en vivo · móvil',
    vistaPreviaBoton: 'Vista previa',
    vistaPreviaVacia: 'La vista previa aparece cuando elijas una plantilla.',
    guardando: 'Guardando…',
    errorGuardar: 'No pudimos guardar este paso. {mensaje}',
    sinPermisoTitulo: 'No puedes configurar el sitio web',
    sinPermisoDescripcion: 'Pide a un administrador de tu organización el permiso «Editar sitio web».',
    volverResumen: 'Volver al resumen',
    errorTitulo: 'No pudimos abrir la configuración del sitio',
    errorDescripcion: 'Tu avance está guardado. Revisa la conexión e inténtalo de nuevo.',
    conflicto: 'Otra persona guardó una versión más nueva del sitio. Recargamos para que sigas desde lo último.',
    pasos: {
      giro: 'Giro y objetivo',
      plantilla: 'Plantilla',
      estilo: 'Estilo',
      datos: 'Datos del negocio',
      dominio: 'Dominio',
      publicar: 'Revisar y publicar',
    },
    giro: {
      titulo: '¿Qué tipo de negocio es?',
      descripcion: 'Lo tomamos de tu organización. Puedes cambiarlo solo para el sitio.',
      objetivosTitulo: '¿Qué quieres lograr con tu sitio?',
      giros: {
        restaurante: 'Restaurante',
        tienda: 'Tienda',
        hotel: 'Hotel',
        servicios: 'Servicios',
        gimnasio: 'Gimnasio',
        otro: 'Otro',
      },
      objetivos: {
        reservas: 'Recibir reservas',
        reservasMesa: 'Recibir reservas de mesa',
        carta: 'Mostrar mi carta',
        pedidos: 'Recibir pedidos para recoger o a domicilio',
        venta_en_linea: 'Vender productos en línea',
        buscadores: 'Que me encuentren en Google y en mapas',
      },
      avisoTitulo: 'Con esto ordenamos las plantillas y activamos Carta y «Reservas en la web»',
      avisoDescripcion: 'Las reservas se gestionan en POS › Reservas de mesas; el sitio solo las recibe.',
      avisoTituloGeneral: 'Con esto ordenamos las plantillas para tu giro',
      avisoDescripcionGeneral: 'Puedes cambiar el giro del sitio cuando quieras; no cambia el de tu organización.',
    },
    plantilla: {
      titulo: 'Elige una plantilla',
      descripcion: 'Mostramos primero las de {giro}. La plantilla define la estructura; el estilo lo eliges en el paso siguiente.',
      todas: 'Todas',
      filtros: 'Filtrar plantillas',
      errorCatalogo: 'No pudimos cargar las plantillas',
      vacio: 'No hay plantillas para este filtro. Prueba con «Todas».',
      elige: 'Elige una plantilla para seguir.',
    },
    estilo: {
      titulo: 'Elige un estilo',
      descripcion: 'Cambia colores, tipografía, botones y movimiento de todo el sitio. Luego puedes ajustarlo en Diseño.',
      logoTitulo: '¿Usar los colores de tu logo?',
      logoDescripcion: 'Tomamos el acento del logo y verificamos el contraste AA.',
      logoBoton: 'Usar colores del logo',
      logoBotonCorto: 'Colores del logo',
      logoSinLogo: 'Sube tu logo en el paso siguiente para usar sus colores.',
      logoNoSePudo: 'No pudimos leer los colores del logo. Elige un estilo de la lista.',
      logoAplicado: 'Usamos {color} de tu logo como acento, con contraste AA.',
      estiloDelLogo: 'Colores de tu logo',
      textoMuestra: 'Tu marca',
      botonMuestra: 'Reservar',
    },
    datos: {
      titulo: 'Datos de tu negocio',
      descripcion: 'Ya los teníamos de Organización{sede}: revisa y corrige. Lo que cambies aquí solo afecta al sitio.',
      descripcionSede: ' y de {sede}',
      logo: 'Logo',
      logoOrigen: 'De tu organización',
      sinLogo: 'Sin logo',
      cambiarLogo: 'Cambiar logo',
      nombre: 'Nombre en el sitio',
      nombreObligatorio: 'Escribe el nombre que verán tus clientes.',
      whatsapp: 'WhatsApp para pedidos y reservas',
      whatsappAyuda: 'Se muestra como botón flotante y en el pie.',
      whatsappInvalido: 'Escribe el número con indicativo, por ejemplo +57 300 000 0000.',
      direccion: 'Dirección',
      direccionAyuda: 'Sale de tu sede principal; se edita en Organización › Sucursales.',
      horarioTitulo: 'Horario · tomado de {sede}',
      horarioSinSede: 'Horario',
      horarioVacio: 'Tu sede aún no tiene horario. Agrégalo en Sucursales para mostrarlo en el sitio.',
      editarSucursales: 'Editar en Organización › Sucursales',
      cerrado: 'Cerrado',
      diasRango: '{desde} a {hasta}',
      dias: {
        monday: 'Lunes',
        tuesday: 'Martes',
        wednesday: 'Miércoles',
        thursday: 'Jueves',
        friday: 'Viernes',
        saturday: 'Sábado',
        sunday: 'Domingo',
      },
    },
    dominio: {
      titulo: '¿Dónde vivirá tu sitio?',
      descripcion:
        'Empieza gratis con tu subdominio. Conectar o comprar un dominio se hace en Sitio web › Dominios y puedes hacerlo cuando quieras.',
      gratisTitulo: 'Usar la dirección gratis',
      gratisDescripcion: '{host} · listo de inmediato, con HTTPS',
      gratis: 'Gratis',
      subdominio: 'Subdominio',
      subdominioAyuda: 'Tu dirección gratis. Para cambiarla, ve a Dominios.',
      conectarTitulo: 'Conectar un dominio que ya tienes',
      conectarDescripcion: 'Ej.: www.tumarca.co · te mostramos los registros DNS exactos de tu proveedor',
      conectarBoton: 'Ir a Dominios › Conectar',
      comprarTitulo: 'Comprar un dominio',
      comprarDescripcion: 'Se conecta solo y se renueva con aviso. El precio lo ves en Dominios antes de pagar.',
      comprarBoton: 'Ir a Dominios › Comprar',
      propioTitulo: 'Tu sitio ya responde en {host}',
      propioDescripcion: 'Es tu dominio principal verificado. La dirección gratis sigue funcionando y redirige a esta.',
      avisoTitulo: 'Puedes empezar gratis y conectar tu dominio después',
      avisoDescripcion: 'Cuando lo conectes, la dirección gratis redirige a la nueva y tus enlaces y QR siguen funcionando.',
      opciones: 'Dónde vivirá tu sitio',
    },
    publicar: {
      titulo: 'Todo listo para publicar',
      descripcion: 'Revisa en móvil y en escritorio. Al publicar se crea la primera versión: puedes volver a ella desde el historial.',
      giro: 'Giro',
      plantilla: 'Plantilla',
      estilo: 'Estilo',
      paginas: 'Páginas',
      direccion: 'Dirección',
      pagos: 'Pagos',
      seccionesN: '{n} secciones',
      legalesN: '{n} legales',
      pagosPasarela: 'En línea con tu pasarela',
      pagosAlRecibir: 'Al recibir (sin pasarela conectada)',
      sinPasarelaTitulo: 'Aún no cobras en línea',
      sinPasarelaDescripcion: 'Los pedidos web se pagarán al recibir. Conecta una pasarela en Ventas en línea › Pagos cuando quieras.',
      conectarAhora: 'Conectar ahora',
      escritorio: 'Escritorio',
      movil: 'Móvil',
      guardarBorrador: 'Guardar como borrador',
      publicarSitio: 'Publicar sitio',
      publicando: 'Publicando…',
      enLinea: 'Tu sitio está en línea',
      noSePudo: 'No pudimos publicar el sitio. {mensaje}',
      sinDato: '—',
    },
  },
} as const;

type Hoja = string;
interface Arbol {
  [clave: string]: Hoja | Arbol;
}

/** Español canónico por ruta con puntos (`resumen.tarjeta.verSitio`). */
export function textoResumenCanonico(clave: string): string | undefined {
  let nodo: Hoja | Arbol | undefined = TEXTOS_RESUMEN as unknown as Arbol;
  for (const parte of clave.split('.')) {
    if (!nodo || typeof nodo === 'string') return undefined;
    nodo = (nodo as Arbol)[parte];
  }
  return typeof nodo === 'string' ? nodo : undefined;
}

export type TraductorResumen = (clave: string, valores?: Record<string, string | number>) => string;

/** Textos de `sitioWeb.resumen.*` y `sitioWeb.asistente.*` con el español canónico de respaldo. */
export function useTextosResumen(): TraductorResumen {
  const t = useTranslations('sitioWeb');
  return useCallback(
    (clave: string, valores?: Record<string, string | number>) => {
      if (t.has(clave)) return t(clave, valores);
      const canon = textoResumenCanonico(clave);
      return canon === undefined ? clave : interpolar(canon, valores);
    },
    [t],
  );
}
