'use client';

/**
 * Textos de Dominios (`sitioWeb.dominios.*`, Figma B/07-01…07-26).
 * `TEXTOS_DOMINIOS` es el español canónico y la fuente de `dominios.es.json`.
 * Mientras el integrador fusiona las claves en messages/*.json,
 * `useTextosDominios` muestra este español en vez de la clave cruda (el patrón
 * de `useTextosComun`).
 *
 * Marca: sin signos de admiración (las capturas 07-09 y 07-17 los traían; el
 * manual los prohíbe) y «GO Admin» con espacio.
 */
import { useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { interpolar } from '../ui/textos';

export const TEXTOS_DOMINIOS = {
  pagina: {
    subtitulo: 'La dirección de tu sitio en internet · {host}',
    subtituloSinHost: 'La dirección de tu sitio en internet',
    subtituloVacio: 'Tu sitio ya está en línea en {host}',
    actualizar: 'Actualizar',
    conectar: 'Conectar un dominio que ya tienes',
    comprar: 'Comprar un dominio',
    conectarCorto: 'Conectar',
    comprarCorto: 'Comprar',
    cambiarSubdominio: 'Cambiar subdominio',
    sinPermisoComprar: 'Comprar dominios requiere el permiso «Comprar dominios».',
  },
  estados: {
    errorTitulo: 'No pudimos consultar el estado de tus dominios',
    errorDescripcion: 'Tu sitio sigue funcionando. Volveremos a intentarlo en unos minutos; también puedes reintentar ahora.',
    reintentar: 'Reintentar',
    sinPermisoTitulo: 'No tienes permiso para gestionar dominios',
    sinPermisoDescripcion:
      'Pide a un administrador el permiso «Dominios del sitio». Comprar dominios requiere además «Comprar dominios», porque genera un cobro.',
    volverResumen: 'Volver al resumen',
  },
  tabla: {
    etiqueta: 'Dominios del sitio',
    dominio: 'Dominio',
    tipo: 'Tipo',
    estado: 'Estado',
    renovacion: 'Renovación',
    ssl: 'SSL',
    principal: 'Principal',
  },
  tipo: {
    comprado: 'Comprado aquí',
    alias_www: 'Alias www',
    propio: 'Propio (externo)',
    subdominio: 'Subdominio GO Admin',
  },
  linea: {
    principal: 'Principal · tu sitio abre aquí',
    redirige: 'Redirige a {host} ({codigo})',
    revisado: 'Revisado {hace}',
    sinRevisar: 'Aún no lo revisamos',
    aOtroServidor: 'El registro A apunta a otro servidor',
    registrosIncorrectos: 'Revisa los registros DNS en tu proveedor',
    subdominioRedirige: 'Gratis · siempre activo · redirige al principal',
    subdominio: 'Gratis · siempre activo',
    tambienAbre: 'También abre tu sitio',
  },
  movil: {
    comprado: 'Comprado · renueva {fecha}',
    compradoSinFecha: 'Comprado · renovación automática',
    compradoApagada: 'Comprado · renovación apagada',
    propio: 'Propio · lo gestiona tu proveedor',
    subdominio: 'Subdominio gratis · siempre activo',
    alias: 'Alias de {host}',
  },
  renovacion: {
    automatica: 'Automática · {fecha}',
    automaticaSinFecha: 'Automática',
    apagada: 'Apagada · vence {fecha}',
    apagadaSinFecha: 'Apagada',
    incluida: 'Incluida con {host}',
    proveedor: 'La gestiona tu proveedor',
    noVence: 'No vence',
  },
  ssl: {
    emitido: 'Emitido',
    pendiente: 'Pendiente',
  },
  fila: {
    renovar: 'Renovar',
    registros: 'Registros',
    revisar: 'Revisar',
    verDetalle: 'Ver detalle',
    usarPrincipal: 'Usar como principal',
    verificarAhora: 'Verificar ahora',
    copiarDireccion: 'Copiar dirección',
    llevarOtro: 'Llevar a otro proveedor',
    quitar: 'Quitar',
    copiada: 'Dirección copiada',
    principalListo: '{host} ahora es tu dominio principal',
  },
  ayuda: {
    queDominioTitulo: '¿Qué dominio abre mi sitio?',
    queDominioTexto: 'El principal. Todos los demás —incluido el subdominio gratis— redirigen a él con un 308, así Google ve una sola dirección.',
    renovacionesTitulo: 'Renovaciones',
    renovacionesTexto: 'Los dominios comprados aquí se renuevan con la renovación automática del registrador. Te avisamos a los 30, 7 y 1 días.',
    correoTitulo: '¿Y el correo @tumarca.com?',
    correoTexto: 'Conectar el dominio no toca tus registros MX: tu correo sigue funcionando igual.',
  },
  vacio: {
    subdominioDescripcion: 'Subdominio gratis de GO Admin · siempre activo',
    sinSubdominio: 'Aún no tienes subdominio',
    elegirSubdominio: 'Elegir subdominio',
    yaTienesTitulo: '¿Ya tienes un dominio?',
    yaTienesTexto: 'Lo compraste en GoDaddy, Hostinger u otro proveedor. Te decimos exactamente qué registros crear y lo verificamos solos.',
    conectarMio: 'Conectar mi dominio',
    compraTitulo: 'Compra tu dominio aquí',
    compraTexto: 'Busca tumarca.com o tumarca.co, págalo con tu tarjeta y queda conectado y con HTTPS en minutos.',
    buscar: 'Buscar un dominio',
  },
  alerta: {
    venceTitulo: '{host} vence en {n} días y su renovación automática está apagada',
    venceUnoTitulo: '{host} vence mañana y su renovación automática está apagada',
    venceTexto: 'Si vence, deja de abrir tu sitio y otra persona puede registrarlo.',
    venceCorto: '{host} vence en {n} días',
    renovacionApagada: 'Renovación apagada.',
    vencidoTitulo: '{host} ya venció',
    vencidoTexto: 'Tu sitio dejó de abrir en esta dirección. Escríbenos para recuperarlo antes de que otra persona lo registre.',
    activarRenovacion: 'Activar renovación',
    activar: 'Activar',
    verDominio: 'Ver dominio',
    renovacionActivada: 'Renovación automática encendida para {host}',
  },
  subdominio: {
    titulo: 'Cambiar subdominio',
    descripcion: 'Es la dirección gratis de tu sitio en GO Admin.',
    campo: 'Subdominio',
    ayuda: 'De 3 a 63 letras, números o guiones.',
    aviso: 'La dirección {host} deja de abrir en cuanto guardes. Actualiza los enlaces que hayas compartido.',
    guardar: 'Guardar subdominio',
    guardado: 'Tu sitio ahora está en {host}',
    invalido: 'Usa de 3 a 63 letras minúsculas, números o guiones, sin guion al inicio ni al final.',
    igual: 'Es el mismo subdominio que ya tienes.',
  },
  conectar: {
    paso: 'Paso {n} de 3',
    titulo1: 'Conecta tu dominio',
    sub1: 'Escribe el dominio que ya compraste en otro proveedor.',
    paraSede: 'Para la sede {sede}',
    campo: 'Tu dominio',
    ayudaCampo: 'Sin https:// ni www. Conectaremos {host} y www.{host}.',
    ayudaCampoVacio: 'Sin https:// ni www. Conectaremos tumarca.com.co y www.tumarca.com.co.',
    invalido: 'Escribe un dominio válido, por ejemplo tumarca.com.co.',
    queHaremos: 'Lo que vamos a hacer',
    haremos1: 'Añadir {host} y www.{host} a tu sitio',
    haremos2: 'Calcular los registros DNS exactos para tu proveedor',
    haremos3: 'Revisarlo cuando nos lo pidas y avisarte en pantalla cuando quede activo con HTTPS',
    correoTitulo: 'Tu correo no se toca',
    correoTexto: 'Solo pediremos registros A y CNAME para la web. Los registros MX de tu correo quedan como están.',
    sinDominio: '¿No tienes dominio? Cómpralo aquí',
    cancelar: 'Cancelar',
    continuar: 'Continuar',
    titulo2: 'Crea estos registros en tu proveedor',
    titulo2Proveedor: 'Crea estos registros en {proveedor}',
    sub2Detectado: 'Detectamos que {host} está en {proveedor}. Entra a su panel de DNS y crea:',
    sub2: 'Entra al panel de DNS de tu proveedor y crea:',
    cloudflareTitulo: 'Si tu proveedor es Cloudflare, desactiva el proxy (nube gris)',
    cloudflareTexto: 'Con la nube naranja no podemos emitir el certificado HTTPS.',
    sinConexionTitulo: 'Verificamos que el dominio es tuyo',
    sinConexionTexto: 'Crea el registro TXT. Cuando lo veamos, nuestro equipo termina de conectarlo al servidor de tu sitio.',
    copiarTodo: 'Copiar todo',
    copiadoTodo: 'Registros copiados',
    atras: 'Atrás',
    yaLosCree: 'Ya los creé, verificar',
    titulo3: 'Verificando {host}…',
    sub3: 'Esto suele tardar de 5 minutos a 1 hora; a veces hasta 48 h.',
    revisadoHace: 'Revisado {hace}',
    puedesCerrar: 'Puedes cerrar esta ventana: el dominio queda en la lista como «Verificando DNS» y lo revisas cuando quieras.',
    certificado: 'Certificado HTTPS: se emite solo cuando los registros estén correctos.',
    verRegistros: 'Ver registros otra vez',
    verificarAhora: 'Verificar ahora',
    cerrar: 'Cerrar',
    activoTitulo: '{host} ya está activo',
    activoSub: 'Tu sitio abre en https://{host} con certificado de seguridad.',
    activoA: 'Registro A de {host} correcto',
    activoCname: 'CNAME de www.{host} correcto',
    activoTxt: 'Verificamos que {host} es tuyo',
    activoSsl: 'Certificado HTTPS emitido; se renueva solo',
    usarPrincipal: 'Usar como dominio principal',
    usarPrincipalTexto: '{otros} redirigirán aquí. Los enlaces viejos siguen funcionando.',
    yaEsPrincipal: 'Ya es tu dominio principal.',
    verSitio: 'Ver mi sitio',
    listo: 'Listo',
    malTitulo: '{host} está mal configurado',
    malSub: 'Uno de los registros apunta a otro servidor. Corrígelo en tu proveedor y vuelve a verificar.',
    loQueEncontramos: 'Lo que encontramos',
    loQueDebeDecir: 'Lo que debe decir',
    borraViejoTitulo: 'Borra el registro A viejo',
    borraViejoTexto: 'Si dejas los dos registros A, la mitad de las visitas irían al servidor anterior.',
    verGuiaProveedor: 'Ver guía del proveedor',
    enUsoTitulo: 'Este dominio ya está conectado a otro sitio',
    enUsoSub: 'Puede ser tu sitio anterior. Para pasarlo aquí, demuestra que es tuyo creando este registro:',
    enUsoTexto: 'Cuando lo verifiquemos, el dominio deja de abrir el sitio anterior y empieza a abrir este. Puedes borrar el TXT después.',
    enUsoOtraTitulo: 'Este dominio ya está conectado a otro sitio de GO Admin',
    enUsoOtraSub: 'Por seguridad no podemos decirte cuál. Si el dominio es tuyo, escríbenos a soporte y lo revisamos.',
    yaLoCree: 'Ya lo creé, verificar',
    propagaTitulo: 'Casi listo: falta que internet se entere',
    propagaSub: 'Tu proveedor ya tiene los registros, pero algunos servidores todavía muestran los viejos.',
    propagaVisto: 'Visto correcto en {vistos} de {total} servidores de prueba',
    propagaRevisado: 'Revisado {hace} · vuelve a verificar en unos minutos',
    propagaPie: 'Puede tardar hasta 72 h',
    hojaTitulo: 'Conectar {host}',
    demasiados: 'Demasiados intentos de verificación. Espera unos minutos.',
  },
  comprar: {
    paso: 'Paso {n} de 3',
    titulo1: 'Compra tu dominio',
    sub1: 'Busca el nombre de tu negocio. Incluye HTTPS y queda conectado a tu sitio.',
    campo: 'Nombre del dominio',
    buscar: 'Buscar',
    buscando: 'Buscando…',
    noDisponible: 'No disponible',
    yaTieneDueno: 'Ya tiene dueño',
    recomendado: 'Recomendado',
    oferta: 'Oferta primer año',
    elegir: 'Elegir',
    piePrecios: 'Precios en {moneda} · consultados {hace}',
    sinResultados: 'Escribe el nombre de tu negocio y busca.',
    ningunoDisponible: 'Ninguna de estas direcciones está libre. Prueba con otro nombre.',
    noDisponibleTitulo: 'La compra de dominios no está disponible por ahora',
    noDisponibleTexto: 'Puedes conectar un dominio que ya tengas en otro proveedor.',
    irConectar: 'Conectar un dominio',
    errorBuscar: 'No pudimos consultar los dominios. Inténtalo de nuevo.',
    tiempo: 'Tiempo',
    unAnio: '1 año',
    porUnAnio: 'por 1 año',
    sub2: 'Elige por cuánto tiempo y confirma los datos del titular.',
    renovarAuto: 'Renovar automáticamente',
    renovarAutoTexto: 'El registrador lo renueva antes de vencer. Puedes apagarlo después en el detalle del dominio.',
    titular: 'Titular del dominio',
    nombre: 'Nombre o razón social',
    correo: 'Correo',
    telefono: 'Teléfono',
    telefonoAyuda: 'Con indicativo de país, por ejemplo +57 300 555 0100.',
    direccion: 'Dirección',
    ciudad: 'Ciudad',
    departamento: 'Departamento o estado',
    codigoPostal: 'Código postal',
    pais: 'País',
    obligatorio: 'Este dato es obligatorio.',
    correoInvalido: 'Escribe un correo válido.',
    telefonoInvalido: 'Escribe el teléfono con indicativo de país.',
    datosRealesTitulo: 'El registrador exige datos reales',
    datosRealesTexto: 'Te puede llegar un correo para confirmarlos. El dominio es tuyo: puedes llevártelo a otro proveedor cuando quieras.',
    atras: 'Atrás',
    continuarPago: 'Continuar al pago',
    titulo3: 'Confirma y paga',
    sub3: 'Revisa el resumen. Cobraremos una sola vez ahora.',
    lineaDominio: '{host} · 1 año',
    https: 'Certificado HTTPS y conexión',
    incluido: 'Incluido',
    total: 'Total a pagar',
    metodo: 'Método de pago',
    tarjeta: 'Tarjeta',
    preparandoPago: 'Preparando el pago seguro…',
    errorPago: 'No pudimos preparar el pago. Inténtalo de nuevo.',
    terminos: 'Acepto los términos de registro de dominios y la política de transferencia y baja',
    pagoSeguro: 'Pago seguro con Stripe',
    pagar: 'Pagar {precio}',
    compraTitulo: 'Comprando {host}…',
    compraSub: 'No cierres esta ventana. Tarda menos de un minuto.',
    pasoPago: 'Pago aprobado',
    pasoRegistro: 'Registrando el dominio a tu nombre',
    pasoConexion: 'Conectándolo a tu sitio',
    pasoHttps: 'Emitiendo el certificado HTTPS',
    progreso: 'Progreso de la compra',
    listoTitulo: '{host} es tuyo',
    listoSub: 'Ya está conectado a tu sitio.',
    listoSubPrincipal: 'Ya está conectado a tu sitio y es tu dominio principal.',
    estado: 'Estado',
    emitiendo: 'Emitiendo HTTPS · ~5 min',
    vence: 'Vence',
    renovacion: 'Renovación automática',
    encendida: 'Encendida',
    cobrado: 'Cobrado',
    titularFila: 'Titular',
    verDominio: 'Ver dominio',
    listo: 'Listo',
    yaNoTitulo: '{host} ya no está disponible',
    yaNoSub: 'Alguien lo registró hace un momento. No te cobramos nada.',
    buscarOtro: 'Buscar otro nombre',
    cerrar: 'Cerrar',
    rechazoTitulo: 'Tu banco rechazó el pago',
    rechazoSub: 'No compramos el dominio ni te cobramos. Prueba con otra tarjeta o pide a tu banco que autorice compras internacionales.',
    rechazoDetalle: 'Mensaje del banco: «{mensaje}». Código: {codigo}.',
    rechazoSinDetalle: 'El banco no autorizó la transacción.',
    usarOtra: 'Usar otra tarjeta',
    reintentar: 'Reintentar',
    cancelar: 'Cancelar',
    registradorTitulo: 'No pudimos registrar {host}',
    registradorSub: 'El registrador no respondió bien. Ya te devolvimos {precio}; el reembolso se ve en tu tarjeta en 5 a 10 días hábiles.',
    reembolsoPendienteSub: 'El registrador no respondió bien y el reembolso de {precio} requiere revisión. Nuestro equipo te escribirá; no hace falta que hagas nada.',
    cobro: 'Cobro',
    reembolso: 'Reembolso',
    reembolsoRevision: 'En revisión',
    equipoAvisado: 'Nuestro equipo ya fue avisado',
    intentarDeNuevo: 'Intentar de nuevo',
    errorGeneral: 'No pudimos completar la compra. Inténtalo de nuevo.',
  },
  quitar: {
    titulo: '¿Quitar {host} de tu sitio?',
    texto: 'El sitio dejará de abrir en {hosts}.',
    textoComprado: 'El dominio sigue siendo tuyo hasta el {fecha}.',
    textoCompradoSinFecha: 'El dominio sigue siendo tuyo hasta que venza.',
    textoPrincipal: 'Como es el principal, {sub} pasa a serlo.',
    confirmar: 'Quitar dominio',
    quitado: '{host} ya no abre tu sitio',
  },
  transferir: {
    titulo: 'Llevar {host} a otro proveedor',
    sub: 'Te enviaremos el código de autorización por correo. Tu sitio sigue funcionando hasta que completes la transferencia.',
    paso1: 'Desbloqueamos el dominio y pedimos el código al registrador.',
    paso2: 'Lo recibes en {correo} (hasta 24 h).',
    paso2SinCorreo: 'Lo recibes en el correo de tu cuenta (hasta 24 h).',
    paso3: 'Lo pegas en tu nuevo proveedor y aceptas la transferencia.',
    paso4: 'Al terminar, quítalo de aquí o apúntalo de nuevo con «Conectar».',
    reglaTitulo: 'Solo si tiene más de 60 días',
    reglaPuede: 'Regla de ICANN: un dominio recién comprado o transferido no puede moverse en sus primeros 60 días. {host} ya puede.',
    reglaNoPuede: 'Regla de ICANN: un dominio recién comprado o transferido no puede moverse en sus primeros 60 días. {host} podrá a partir del {fecha}.',
    solicitar: 'Solicitar código',
    enviado: 'Te enviamos el código a {correo}',
  },
  detalle: {
    compradoEl: 'Comprado con GO Admin el {fecha}',
    conectadoEl: 'Conectado el {fecha}',
    principal: 'principal',
    ultimaVerificacion: 'Última verificación {hace} · todo correcto',
    ultimaVerificacionPendiente: 'Última verificación {hace}',
    sinVerificar: 'Aún no se ha verificado',
    activo: 'Activo',
    verSitio: 'Ver sitio',
    verificarAhora: 'Verificar ahora',
    conexionTitulo: 'Conexión DNS',
    conexionComprado: 'Registros que necesita tu sitio. Lo administra GO Admin porque el dominio está con nosotros.',
    conexionPropio: 'Registros que necesita tu sitio. Créalos en el panel de tu proveedor.',
    otrosRegistros: 'Otros registros (MX de correo, TXT de Google) se conservan.',
    sinRegistros: 'Aún no tenemos los registros de este dominio. Verifícalo para calcularlos.',
    sslTitulo: 'Certificado HTTPS',
    sslEstado: 'Estado',
    sslEmitido: 'Emitido',
    sslPendiente: 'Pendiente',
    sslNoAplica: 'Sin certificado',
    sslEmisor: 'Emisor',
    sslEmisorValor: "Let's Encrypt (vía Vercel)",
    sslRenueva: 'Se renueva solo',
    redireccionesTitulo: 'Redirecciones',
    redireccionesTexto: 'Las demás direcciones llevan a la principal con un 308 (permanente).',
    sinRedirecciones: 'Ninguna dirección redirige a este dominio.',
    renovacionTitulo: 'Renovación',
    vence: 'Vence',
    venceDesconocido: 'Sin fecha del registrador',
    renovarAuto: 'Renovar automáticamente',
    renovarAutoTexto: 'El registrador lo renueva antes de vencer.',
    precioVigente: 'Precio vigente del registrador',
    renovarAhora: 'Renovar ahora por 1 año',
    renovarAhoraNoDisponible: 'La renovación manual todavía no está disponible: deja encendida la renovación automática.',
    proveedorTitulo: 'Renovación',
    proveedorTexto: 'La gestiona tu proveedor. Renuévalo allí para que tu sitio no deje de abrir.',
    transferirTitulo: 'Llevarlo a otro proveedor',
    transferirTexto: 'El dominio es tuyo. Te damos el código de autorización para transferirlo.',
    transferirBoton: 'Solicitar código de transferencia',
    quitarTitulo: 'Quitar dominio',
    quitarTexto: 'Tu sitio dejará de abrir en {host}. Si lo compraste aquí, sigue siendo tuyo hasta que venza.',
    quitarBoton: 'Quitar de mi sitio',
    subdominioTexto: 'Es la dirección gratis de tu sitio. No vence y no se puede quitar: es el respaldo si un dominio propio falla.',
    noExisteTitulo: 'No encontramos este dominio',
    noExisteTexto: 'Puede que lo hayan quitado o que sea de otra organización.',
    volver: 'Volver a Dominios',
    copiarRegistros: 'Copiar registros',
  },
  hace: {
    ahora: 'hace un momento',
    minutos: 'hace {n} min',
    horas: 'hace {n} h',
    dias: 'hace {n} días',
    unDia: 'hace 1 día',
  },
  errores: {
    sin_permiso: 'No tienes permiso para gestionar dominios.',
    no_existe: 'No encontramos ese dominio.',
    host_invalido: 'Escribe un dominio válido, por ejemplo tumarca.com.',
    subdominio_invalido: 'Usa de 3 a 63 letras minúsculas, números o guiones, sin guion al inicio ni al final.',
    subdominio_en_uso: 'Ese subdominio ya lo usa otro sitio. Prueba con otro.',
    subdominio_sistema: 'El subdominio de GO Admin no se puede quitar: es el respaldo de tu sitio.',
    no_verificado: 'Solo un dominio activo y verificado puede ser el principal.',
    no_comprado: 'Esta acción es solo para dominios comprados con GO Admin.',
    muy_reciente: 'Un dominio recién comprado no se puede transferir en sus primeros 60 días.',
    no_disponible: 'Esta acción no está disponible por ahora.',
    demasiados_intentos: 'Demasiados intentos. Espera unos minutos.',
    red: 'Revisa tu conexión e inténtalo de nuevo.',
    error_interno: 'No pudimos completar la acción. Inténtalo de nuevo.',
  },
} as const;

type Hoja = string;
type Arbol = { readonly [k: string]: Hoja | Arbol };

export function textoDominios(clave: string): string | undefined {
  let nodo: Hoja | Arbol | undefined = TEXTOS_DOMINIOS as unknown as Arbol;
  for (const parte of clave.split('.')) {
    if (!nodo || typeof nodo === 'string') return undefined;
    nodo = (nodo as Arbol)[parte];
  }
  return typeof nodo === 'string' ? nodo : undefined;
}

export type TraductorDominios = (clave: string, valores?: Record<string, string | number>) => string;

/** Textos de `sitioWeb.dominios.*` en el idioma activo, con el español canónico de respaldo. */
export function useTextosDominios(): TraductorDominios {
  const t = useTranslations('sitioWeb');
  return useCallback(
    (clave: string, valores?: Record<string, string | number>) => {
      const completa = `dominios.${clave}`;
      if (t.has(completa)) return t(completa, valores);
      const canon = textoDominios(clave);
      return canon === undefined ? clave : interpolar(canon, valores);
    },
    [t],
  );
}
