'use client';

/**
 * Textos del editor del sitio (`sitioWeb.editor.*`). `TEXTOS_EDITOR` es el español de Colombia
 * canónico (Figma A/05, D/05, figma-estilo) y la fuente de `editor.es.json`. Mientras el
 * integrador fusiona las claves en messages/*.json, `useTextosEditor` muestra este español en vez
 * de la clave cruda (el mismo patrón que `useTextosComun`). Marcadores: `{n}`, `{sede}`…
 */
import { useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { interpolar } from '@/components/sitio-web/ui/textos';

export const TEXTOS_EDITOR = {
  barra: {
    volver: 'Volver a Sitio web',
    migas: 'Sitio y página que editas',
    sitio: 'Sitio o sede que editas',
    pagina: 'Página que editas',
    ancho: 'Ver el lienzo como',
    dispositivo: {
      escritorio: 'Computador · {ancho} px',
      portatil: 'Portátil · {ancho} px',
      tableta: 'Tableta · {ancho} px',
      celular: 'Celular · {ancho} px',
    },
    deshacer: 'Deshacer',
    deshacerAtajo: 'Deshacer (Ctrl + Z)',
    rehacer: 'Rehacer',
    rehacerAtajo: 'Rehacer (Ctrl + Mayús + Z)',
    noSeGuardo: 'No se guardó',
    cambiosSinGuardar: 'Cambios sin guardar',
    legacyAlDia: 'Publicado',
    verPublicado: 'Ver sitio publicado',
    vistaPrevia: 'Vista previa',
    publicar: 'Publicar',
    publicarSede: 'Publicar {sede}',
    guardarPublicar: 'Guardar y publicar',
    masAcciones: 'Más acciones del editor',
    sinPermisoPublicar: 'Tu rol no puede publicar el sitio. Pide el permiso «Publicar sitio web».',
    nadaQuePublicar: 'No hay cambios por publicar',
    nadaQueGuardar: 'No hay cambios por guardar',
  },
  acciones: {
    reintentar: 'Reintentar',
    cancelar: 'Cancelar',
    seoPagina: 'SEO de la página',
    disenoPagina: 'Diseño de la página',
    cancelarProgramacion: 'Cancelar la publicación programada',
    verHerencia: 'Ver lo personalizado en esta sede',
    copiarMenu: 'Copiar el menú «{menu}» a esta sede',
    activarV2: 'Activar el borrador en la web',
    activarV2SinLector: 'La web todavía no lee el borrador nuevo',
    activarV2PublicaPrimero: 'Publica una versión antes de activarlo',
    desactivarV2: 'Desactivar el borrador en la web',
    editarSinV2: 'Editar el sitio actual (sin borrador)',
    crearBorrador: 'Pasar a borrador y publicar',
  },
  estado: {
    sinPermisoTitulo: 'No puedes editar el sitio web',
    sinPermisoDescripcion: 'Pide a un administrador el permiso «Editar sitio web» (website.sites.edit). Publicar es un permiso aparte.',
    volverPaginas: 'Volver a Páginas',
    noEncontradaTitulo: 'Esta página no existe o no es de tu organización',
    noEncontradaDescripcion: 'Puede que la hayan quitado. Elige otra desde Páginas.',
    irPaginas: 'Ir a Páginas',
    errorTitulo: 'No pudimos abrir el editor',
    errorDescripcion: 'Tu sitio sigue en línea. Revisa la conexión e inténtalo de nuevo.',
  },
  lista: {
    titulo: 'Secciones de {pagina}',
    ayuda: 'Arrastra para cambiar el orden',
    encabezado: 'Encabezado',
    pie: 'Pie de página',
    soloEstaSede: 'Solo en esta sede',
    duplicar: 'Duplicar',
    subir: 'Subir',
    bajar: 'Bajar',
    eliminar: 'Eliminar',
    anadir: 'Añadir sección',
    estiloSitio: 'Estilo del sitio',
    historial: 'Historial de versiones',
    vacia: 'Aún no hay secciones en esta página. Añade la primera.',
    porDefecto: 'Usar las secciones recomendadas',
    arrastrar: 'Arrastra para cambiar el orden o usa Alt + flechas',
    noMover: 'Esta sección viene del sitio principal',
  },
  lienzo: {
    etiqueta: 'Vista del sitio',
    iframe: 'Vista previa de la página',
    sinDireccionTitulo: 'Tu sitio aún no tiene dirección',
    sinDireccionDescripcion: 'Configura el subdominio en Dominios para ver la página aquí.',
    errorTitulo: 'No se pudo mostrar la página',
    errorDescripcion: 'Revisa la conexión. Tus cambios siguen en el editor.',
    seccion: '{seccion} · clic para editar',
    seccionPropia: '{seccion} · tipografía propia · vista previa en vivo',
    encabezado: 'Encabezado · global · clic en un enlace para editar el menú',
    pie: 'Pie de página · global · clic en un enlace para editar el menú',
  },
  inspector: {
    etiqueta: 'Inspector: {nombre}',
    tituloSede: '{nombre} · {sede}',
    tipoVariante: '{tipo} · variante «{variante}»',
    vieneDelPrincipal: 'Viene del sitio principal',
    duplicar: 'Duplicar sección',
    duplicarAtajo: 'Duplicar (Ctrl + D)',
    ocultar: 'Ocultar sección',
    mostrar: 'Mostrar sección',
    eliminar: 'Eliminar sección',
    eliminarAtajo: 'Eliminar (Supr)',
    pestanas: 'Ajustes de la sección',
    diseno: 'Diseño',
    contenido: 'Contenido',
    estilo: 'Estilo',
    avanzado: 'Avanzado',
    variante: 'Variante',
    sinContenido: 'Esta sección no tiene contenido que editar aquí.',
    borradorTitulo: 'Todo queda en borrador',
    borradorDescripcion: 'Tus clientes lo verán cuando publiques.',
    legacyTitulo: 'Se publica al guardar',
    legacyDescripcion: 'En este sitio «Guardar y publicar» lleva los cambios a la web.',
    vacioTitulo: 'Elige una sección',
    vacioDescripcion: 'Haz clic en una sección de la lista o del lienzo para editar su diseño, contenido y estilo.',
  },
  campo: {
    elegir: 'Elige una opción',
  },
  contenido: {
    sinCategorias: 'Aún no hay categorías en el Inventario. Créalas una vez y se usan en el POS, la tienda y el menú.',
    editarInventario: 'Editar productos y precios en Inventario',
    cartaAyuda: 'El orden, los destacados y los platos ocultos de la carta se editan en Carta.',
    editarCartaAqui: 'Editar la carta',
    editarEnCarta: 'Editar en Carta',
  },
  avanzado: {
    titulo: 'Para casos especiales',
    descripcion: 'Lo normal se ajusta en Estilo. Estos valores ignoran el preset del sitio.',
    precedencia: 'Orden de prioridad: Avanzado, luego el estilo de la sección y, al final, el estilo del sitio.',
  },
  estilo: {
    fondoTitulo: 'Fondo',
    fondoAyuda: '«Del tema», «Alterno» y «Oscuro» salen del estilo del sitio: si cambias de preset, la sección se adapta sola.',
    entradaTitulo: 'Entrada al aparecer',
    entradaAyuda: 'Respeta «reducir movimiento» del sistema y el nivel de movimiento del sitio.',
    espaciadoTitulo: 'Espaciado',
    anchoTitulo: 'Ancho',
    fondo: { tema: 'Del tema', alterno: 'Alterno', oscuro: 'Oscuro', imagen: 'Imagen' },
    entrada: { ninguna: 'Ninguna', aparecer: 'Aparecer', revelar_texto: 'Revelar texto' },
    espaciado: { compacto: 'Compacto', normal: 'Normal', amplio: 'Amplio' },
    ancho: { contenedor: 'Contenedor', completo: 'Pantalla completa' },
    interlineado: { compacto: 'Compacto', normal: 'Normal', amplio: 'Amplio' },
    grosor: { '400': 'Normal', '500': 'Medio', '600': 'Seminegrita', '700': 'Negrita' },
    grupo: { tipografia: 'Tipografía', mostrar: 'Mostrar en', colores: 'Colores', fondo: 'Fondo' },
    tipografia: {
      sitio: 'Como el sitio',
      propia: 'Personalizada',
      ayuda:
        'Por defecto «Como el sitio»: {titulos} en títulos y {cuerpo} en el texto, del Estilo del sitio. Al personalizar, solo esta sección cambia.',
      fuenteTitulo: 'Fuente del título',
      fuenteTexto: 'Fuente del texto',
      ajustesDe: 'Ajustes de',
      titulo: 'Título',
      texto: 'Texto',
      tamano: 'Tamaño',
      tamanoPx: 'Tamaño en píxeles',
      escalaTitulo: 'S 28 · M 34 · L 40 · XL 48 px en computador; en celular se reduce un 20 %.',
      escalaTexto: 'S 14 · M 16 · L 18 · XL 20 px en computador; en celular se reduce un 20 %.',
      grosor: 'Grosor',
      interlineado: 'Interlineado',
      interlineadoValor: 'Interlineado exacto',
      mayusculas: 'Todo en mayúsculas',
      mayusculasAyuda: 'Con espaciado de letras +4 % para que se lea bien',
      enVivo: 'Vista previa en vivo: el lienzo repinta la sección con cada cambio, antes de guardar.',
    },
    mostrarEtiqueta: 'Mostrar la sección en',
    mostrarAyuda: 'Oculta en un dispositivo: no se pinta ahí y en la lista de secciones sale el aviso. Siempre queda al menos un dispositivo activo.',
    mostrarUltimo: 'Siempre queda al menos un dispositivo activo.',
    tabletaSigueComputador: 'En tableta se ve igual que en computador. Ocultar solo en tableta llega cuando el sitio publicado lo admita.',
    dispositivo: { computador: 'Computador', tableta: 'Tableta', celular: 'Celular' },
    coloresAyuda:
      'Cada selector ofrece primero los colores de la marca (enlazados: cambian si cambia la marca) y luego «Personalizado».',
    colorTexto: 'Color del texto',
    colorBorde: 'Color del borde',
    restablecer: 'Restablecer el estilo de la sección',
    sinCambios: 'La sección ya usa el estilo del sitio',
    rol: { primario: 'Primario', secundario: 'Secundario', acento: 'Acento', texto: 'Texto', fondo: 'Fondo' },
    resumen: {
      comoSitio: 'Como el sitio · {titulos} + {cuerpo}',
      propia: 'Propia',
      mayusculas: 'mayúsculas',
      colores: 'Texto: {texto} · Borde: {borde}',
      deMarca: '«{rol}» de la marca',
      delTema: 'del estilo del sitio',
    },
    sede: {
      heredado: 'El estilo de esta sección viene del sitio principal: si lo cambian allá, cambia aquí.',
      heredadoAyuda: 'Cambia cualquier ajuste y pasa a ser propio de {sede}, solo ese ajuste; el resto sigue heredando.',
      propios: '{n} ajustes propios de {sede} ({grupos}). «Restablecer» vuelve a heredar todo el estilo de la principal.',
      cambiar: 'Cambiar en esta sede',
      restablecerTodo: 'Restablecer todo el estilo (volver a heredar)',
    },
  },
  estiloSitio: {
    titulo: 'Estilo del sitio',
    cerrar: 'Cerrar estilo del sitio',
    sinDatos: 'Aún no hay estilo para este sitio. Elige una plantilla en Plantillas.',
  },
  anadir: {
    titulo: 'Añadir sección',
    tituloSede: 'Añadir sección a {sede}',
    descripcion: '{lugar}. Usa el estilo de tu sitio.',
    descripcionSede: '{lugar} de {sede}. El sitio principal y las demás sedes no cambian.',
    despuesDe: 'Se añade después de «{seccion}» en {pagina}',
    enPagina: 'Se añade en {pagina}',
    buscar: 'Buscar sección (reservas, galería, chef…)',
    buscarEtiqueta: 'Buscar',
    propositos: 'Propósitos',
    recomendadas: 'Recomendadas',
    recomendadasProposito: 'para tu negocio',
    grupoTitulo: '{grupo} · {proposito}',
    anadir: 'Añadir sección',
    anadirIgual: 'Añadir de todas formas',
    elige: 'Elige una sección',
    coinciden: '{n} de {total} secciones coinciden',
    pie: '{total} secciones · todas sirven para cualquier negocio · «Faltan datos» no bloquea',
  },
  publicar: {
    titulo: 'Publicar cambios',
    tituloSede: 'Publicar {sede}',
    descripcion: '{n} cambios desde la última publicación ({fecha}{autor}).',
    descripcionUno: '1 cambio desde la última publicación ({fecha}{autor}).',
    descripcionSede: 'Solo se publica {direccion}. El sitio principal y las demás sedes no cambian.',
    primeraVez: 'Es la primera publicación de tu sitio con borrador.',
    calculando: 'Revisando los cambios…',
    listaCambios: 'Cambios por publicar',
    sinCambios: 'No hay cambios desde la última publicación.',
    ver: 'Ver',
    cuando: '¿Cuándo?',
    ahora: 'Publicar ahora',
    ahoraAyuda: 'Tus clientes lo ven en menos de un minuto',
    programar: 'Programar',
    programarAyuda: 'Ej.: el lunes antes de abrir',
    programarNoDisponible: 'Programar aún no está activo en tu cuenta',
    ahoraAccion: 'Publicar ahora',
    programarAccion: 'Programar publicación',
    publicarSede: 'Publicar {sede}',
    fecha: {
      etiqueta: 'Fecha',
      pasada: 'Elige una fecha y hora futuras (al menos 2 minutos).',
      muy_lejana: 'Programa dentro del próximo año.',
      invalida: 'Elige la fecha y la hora.',
    },
    hora: 'Hora',
    nota: 'Nota de la versión (opcional)',
    notaAyuda: 'Aparece en el historial de versiones.',
    notaEjemplo: 'Ej.: Carta de temporada',
    versionTitulo: 'Se guarda una versión',
    versionDescripcion: 'Si algo no queda bien, la restauras desde el historial en un clic.',
    principalTitulo: 'El sitio principal tiene cambios sin publicar que {sede} hereda',
    principalDescripcion: 'No llegan a {sede} hasta que publiques el principal.',
    tambienPrincipal: 'Publicar también el sitio principal',
    sinAdoptarTitulo: 'La web todavía muestra el sitio actual',
    sinAdoptarDescripcion: 'La versión queda en el historial. Tus clientes la verán cuando se active el borrador en la web.',
    listo: 'Versión {n} publicada',
    yaPublicada: 'Esta versión ya estaba publicada',
    listoAdoptado: 'Tus clientes la verán en cuanto se actualice la caché.',
    listoSinAdoptar: 'Queda en el historial. La web sigue mostrando el sitio actual hasta activar el borrador.',
    error: 'No se pudo publicar',
    programada: 'Publicación programada',
    errorProgramar: 'No se pudo programar la publicación',
    programacionCancelada: 'Publicación programada cancelada',
    errorCancelar: 'No se pudo cancelar la publicación programada',
    programadaConCambiosTitulo: 'Tienes una publicación programada para el {fecha}',
    programadaConCambios: 'Los cambios que hagas ahora no entran en ella y la harán fallar: vuelve a programar cuando termines.',
    cambio: {
      seccionTitulo: '{pagina} · {seccion}',
      seccion: { nueva: 'Sección nueva', quitada: 'Sección quitada', editada: 'Sección editada' },
      pagina: { nueva: 'Página nueva', quitada: 'Página quitada', editada: 'Datos u orden de la página' },
      variante: 'Variante «{antes}» → «{despues}»',
      contenido: 'contenido',
      estilo: 'estilo de la sección',
      visibilidad: 'dispositivos donde se ve',
      temaTitulo: 'Estilo del sitio',
      color: '{rol} {antes} → {despues}',
      tipografia: 'tipografía',
      temaOtros: 'redondeo, botones o movimiento',
    },
    rol: { primario: 'Acento', secundario: 'Secundario', acento: 'Acento secundario', fondo: 'Fondo', texto: 'Texto' },
    area: {
      identidad: 'Logo y nombre',
      seo: 'SEO del sitio',
      contenido: 'Datos del negocio',
      menus: 'Menús',
      shell: 'Encabezado y pie',
      tema: 'Estilo del sitio',
    },
    areaDetalle: {
      identidad: 'Logo, favicon o nombre del sitio',
      seo: 'Título, descripción o imagen para compartir',
      contenido: 'Redes, horarios o texto del pie',
      menus: 'Enlaces del encabezado o del pie',
      shell: 'Diseño y opciones del encabezado o del pie',
    },
  },
  historial: {
    titulo: 'Historial de versiones',
    descripcion: 'Las versiones publicadas y los guardados automáticos',
    cerrar: 'Cerrar historial',
    borradorActual: 'Borrador actual',
    guardadoBorrador: 'Guardado en borrador',
    cambios: '{n} cambios',
    cambiosUno: '1 cambio',
    enLinea: 'En línea',
    enLineaNota: 'En línea · «{nota}»',
    nota: '«{nota}»',
    version: 'Versión {n}',
    autoguardado: 'Guardado automático',
    badgeEnLinea: 'En línea',
    badgePublicado: 'Publicado',
    ver: 'Ver esta versión',
    restaurar: 'Restaurar',
    confirmarTitulo: '¿Restaurar la versión del {fecha}?',
    confirmarDescripcion: 'Se copia a tu borrador y reemplaza los {n} cambios sin publicar. Lo que está en línea no cambia hasta que publiques.',
    confirmarDescripcionSinCambios: 'Se copia a tu borrador. Lo que está en línea no cambia hasta que publiques.',
    confirmar: 'Restaurar en borrador',
    restaurada: 'Versión restaurada en el borrador',
    restauradaDescripcion: 'Revísala y publica cuando esté lista.',
    errorRestaurar: 'No se pudo restaurar',
    errorVer: 'No se pudo abrir la versión',
    errorTitulo: 'No pudimos cargar el historial',
    errorDescripcion: 'Revisa la conexión e inténtalo de nuevo.',
    vacioTitulo: 'Aún no has publicado',
    vacioDescripcion: 'Cuando publiques, cada versión aparece aquí.',
    viendo: 'Estás viendo la versión {n} ({fecha}). Tu borrador no cambia.',
    volverBorrador: 'Volver al borrador',
  },
  conflicto: {
    titulo: 'Hay una versión más nueva',
    publico: '{quien} publicó cambios {hace}.',
    guardo: '{quien} guardó cambios en el borrador.',
    otraPersona: 'Otra persona',
    haceUnMomento: 'hace un momento',
    haceMinuto: 'hace 1 minuto',
    haceMinutos: 'hace {n} minutos',
    haceHora: 'hace 1 hora',
    haceHoras: 'hace {n} horas',
    bandaDetalle: 'Tu borrador parte de una versión anterior. Revisa antes de publicar para no deshacer su trabajo.',
    tusCambiosSiguen: 'Tus cambios siguen en el editor.',
    verSuyos: 'Ver sus cambios',
    resolver: 'Resolver',
    opciones: 'Qué hacer con tus cambios',
    combinar: 'Combinar: aplicar mis cambios sobre la versión nueva',
    combinarAyuda: 'Recomendado. Solo chocan si tocamos la misma sección.',
    combinarNoDisponible: 'No disponible: tu borrador no parte de una versión publicada.',
    descartar: 'Descartar mis cambios y cargar la versión nueva',
    descartarAyuda: 'Tus cambios quedan en el historial como guardado automático.',
    sobrescribir: 'Publicar los míos de todos modos',
    sobrescribirAyuda: 'Reemplaza lo que publicó {quien}.',
    combinarAccion: 'Combinar',
    combinarElegido: 'Combinar con lo elegido',
    descartarAccion: 'Descartar y cargar',
    sobrescribirAccion: 'Publicar los míos',
    ahoraNo: 'Ahora no',
    choquesTitulo: '{n} cambios chocan',
    choquesDescripcion: 'Los dos cambiaron lo mismo. Elige qué versión queda en cada caso.',
    choqueSeccion: '{pagina} · {seccion}',
    choquePagina: 'Datos de la página {pagina}',
    choqueOrden: 'Orden de las secciones de {pagina}',
    mia: 'La mía',
    suya: 'La suya',
    combinado: 'Cambios combinados en el borrador',
    descartado: 'Cargaste la versión nueva',
    error: 'No se pudo resolver el conflicto',
    errorCombinar: 'No se pudo leer la versión de partida para combinar. Prueba «Descartar» o «Publicar los míos».',
  },
  sede: {
    principal: 'Sitio principal',
    generica: 'Sede {id}',
    tuOrganizacion: 'Tu organización',
    preguntaTitulo: '¿Cambiar solo en {sede} o en todas las sedes?',
    preguntaTituloQuitar: '¿Quitar solo en {sede} o en todas las sedes?',
    preguntaAyuda: 'Esta sección es la misma en todas las sedes.',
    soloEn: 'Solo en {sede}',
    enTodas: 'En todas',
    enTodasAyuda: '«En todas» cambia el sitio principal. Al publicarlo, el cambio pasa al borrador de cada sede que usa esta sección y llega a su web cuando esa sede se publica.',
    ahoraPrincipal: 'Ahora editas el sitio principal',
    ahoraPrincipalDescripcion: 'Aplicamos tu cambio aquí. Al publicar, pasa al borrador de cada sede que usa esta sección.',
    crearBorradorTitulo: 'Pasar el sitio principal a borrador',
    crearBorradorDescripcion:
      'Se copia el sitio actual (páginas, secciones, estilo, encabezado, pie y menús) a un borrador. La web no cambia: sigue mostrando el sitio actual hasta que publiques y actives el borrador.',
    crearBorrador: 'Crear borrador',
    crearSitioTitulo: 'Crear el sitio de {sede}',
    crearSitioDescripcion:
      'La sede tendrá su propio borrador y su propia publicación. Hereda del sitio principal todo lo que no personalices. Nada se publica hasta que lo decidas.',
    crearSitio: 'Crear sitio de la sede',
    borradorCreado: 'Borrador creado',
    sitioCreado: 'Sitio de {sede} creado',
    nadaCambia: 'Nada cambió en la web.',
    errorCrear: 'No se pudo crear el sitio',
  },
  enVivo: {
    titulo: 'Editas el sitio en vivo:',
    descripcion: 'al guardar, los cambios salen en la web. Crea un borrador para revisarlos antes de publicar.',
    crearBorrador: 'Crear borrador',
  },
  adopcion: {
    activarTitulo: 'Activar el borrador en la web de {sitio}',
    activarDescripcion: 'La web pasará a mostrar la última versión publicada. Puedes desactivarlo después sin perder nada.',
    activar: 'Activar en la web',
    desactivarTitulo: 'Desactivar el borrador en {sitio}',
    desactivarDescripcion: 'La web vuelve a mostrar el sitio anterior. El borrador y las versiones se conservan.',
    desactivarSede: 'La web de esta sede dejará de mostrarse (no vuelve al sitio principal). El borrador y las versiones se conservan.',
    desactivar: 'Desactivar',
    activada: 'El borrador está activo en la web',
    desactivada: 'La web volvió al sitio anterior',
    error: 'No se pudo cambiar la activación',
  },
  menu: {
    tituloEncabezado: 'Menú del encabezado · {menu}',
    tituloPie: 'Menús del pie',
    sinMenu: 'sin menú',
    asignado: 'Menú asignado',
    subtitulo: 'Arrastra para ordenar o anidar. Los cambios van al borrador.',
    abrirPaginas: 'Abrir Menú y navegación',
    listo: 'Listo',
    vacioEncabezado: 'El encabezado aún no tiene menú. Créalo en Páginas › Menú y navegación.',
    vacioPie: 'El pie aún no tiene menús. Créalos en Páginas › Menú y navegación.',
    vacioMenu: 'Este menú aún no tiene enlaces. Añade el primero.',
    copiado: 'Menú copiado a esta sede',
    actualizado: 'Menú actualizado en el borrador',
    error: 'No se pudo traer el menú',
  },
  eliminar: {
    titulo: 'Eliminar sección',
    descripcionBorrador: '¿Quitar esta sección del borrador? Lo publicado no cambia hasta que publiques.',
    descripcionLegacy: 'La sección se quita de la página y de la web. No se puede deshacer.',
    descripcionSede: 'La sección se quita solo en {sede}. Las demás sedes y el sitio principal la conservan.',
    confirmar: 'Eliminar',
  },
  pagina: {
    descartarTitulo: 'Tienes cambios sin guardar',
    descartarDescripcion: 'Si cambias de página, se pierden. ¿Quieres descartarlos?',
    descartar: 'Descartar y cambiar',
  },
  seo: {
    titulo: 'SEO de {pagina}',
    descripcion: 'Cómo sale esta página en Google y al compartirla.',
    metaTitulo: 'Título para buscadores',
    metaTituloAyuda: 'Si lo dejas vacío, se usa el del sitio.',
    metaDescripcion: 'Descripción',
    imagen: 'Imagen para compartir',
    imagenAyuda: 'Enlace a una imagen de 1200 × 630 px.',
    aplicar: 'Aplicar',
  },
  guardado: {
    guardando: 'Guardando…',
    errorTitulo: 'No se guardó el borrador',
    errorDescripcion: 'Revisa tu conexión. Tus cambios siguen en el editor.',
    errorOperacion: 'No se guardaron los ajustes de operación',
    operacionSoloPrincipal: 'Envío, contador y botones de compra se configuran en el sitio principal por ahora.',
  },
  encabezadoPie: {
    titulo: 'Encabezado y pie',
    subtitulo: 'Estilo del sitio',
    detalleFila: 'Diseño, buscador, barra superior y pie',
    ayuda: 'Toca un ajuste para cambiarlo en una hoja inferior',
    ajuste: {
      diseno: 'Diseño del encabezado',
      buscador: 'Buscador',
      barra: 'Barra superior',
      boton: 'Botón de acción',
      acciones: 'Acciones',
      pie: 'Diseño del pie',
      celular: 'Menú en el celular',
    },
    estiloEncabezado: { default: 'Clásico', centered: 'Centrado', split: 'Dividido', minimal: 'Minimal', mega: 'Megamenú' },
    posicionMenu: { inline: 'menú en la misma línea', below: 'barra de menú bajo el logo' },
    buscadorComputador: { bar: 'Barra visible', icon: 'Icono', hidden: 'Sin buscador' },
    buscadorCelular: { bar: 'barra en el celular', icon: 'icono en el celular', hidden: 'sin buscador en el celular' },
    buscadorEnComputador: 'En el computador',
    buscadorEnCelular: 'En el celular',
    barraActiva: 'Activa',
    barraActivaAviso: 'Activa · {aviso}',
    barraApagada: 'Apagada',
    mostrarBarra: 'Mostrar la barra superior',
    barraTelefono: 'Mostrar el teléfono',
    barraCorreo: 'Mostrar el correo',
    sinBoton: 'Sin botón',
    botonTexto: 'Texto del botón',
    botonAyuda: 'Déjalo vacío para quitar el botón.',
    botonEnlace: 'A dónde lleva',
    accion: { carrito: 'Carrito', cuenta: 'Cuenta' },
    sinAcciones: 'Sin acciones',
    estiloPie: { default: 'Clásico', three_columns: 'Tres columnas', centered: 'Centrado', minimal: 'Minimal', split: 'Dividido' },
    columnas: '{n} columnas',
    menuCelular: { drawer: 'Cajón lateral', bottom_sheet: 'Hoja inferior', fullscreen: 'Pantalla completa', tabs: 'Pestañas abajo' },
    fijo: 'fijo al desplazar',
  },
  carta: {
    titulo: 'Carta',
    descripcion: 'Elige qué carta muestra esta sección. Lo que trae cada carta se edita en Carta.',
    queMuestra: 'Qué carta muestra esta sección',
    segunHorario: 'Según el horario',
    segunHorarioAyuda: 'Las cartas vigentes en cada sede, día y hora.',
    editarEnCarta: 'Editar en Carta',
    editarCartaNombre: 'Editar «{carta}» en Carta',
    fijaPendiente: 'Por ahora el sitio muestra las cartas vigentes según su horario. Elegir una carta fija llega cuando el sitio publicado lo admita.',
    dondeSeEdita: 'Destacados, ocultos, orden, horario y precio o agotado por sede se editan en Sitio web › Carta.',
    sinPermiso: 'No tienes permiso para ver las cartas',
    errorTitulo: 'No se pudieron cargar las cartas',
    errorDescripcion: 'Revisa tu conexión e inténtalo de nuevo.',
  },
  toast: {
    seccionBorrador: '«{seccion}» quedó en el borrador',
    seccionSede: '«{seccion}» quedó solo en esta sede',
    seccionAnadida: 'Sección añadida: {seccion}',
    seccionEliminada: 'Sección eliminada',
    seccionDuplicada: 'Sección duplicada',
    errorAnadir: 'No se pudo añadir la sección',
    errorEliminar: 'No se pudo eliminar la sección',
    errorDuplicar: 'No se pudo duplicar la sección',
    errorPorDefecto: 'No se pudieron crear las secciones recomendadas',
    errorPagina: 'No se pudo abrir esa página',
    errorSede: 'No se pudieron cargar los datos de la sede',
    sitioUsaV2: 'Este sitio ya usa borrador: edítalo desde «Editando: Sitio principal» y publica.',
    guardadoLegacy: 'Cambios guardados y publicados',
  },
  movil: {
    soloLectura: 'Vista previa · solo lectura',
    avisoTitulo: 'Abre el editor en un computador',
    avisoDescripcion: 'El editor completo necesita una pantalla grande. Desde aquí puedes hacer cambios rápidos.',
    compartir: 'Compartir',
    enlaceCopiado: 'Enlace copiado',
    cambiosRapidos: 'Cambios rápidos',
    rapidosSubtitulo: '{pagina} · se guardan en el borrador',
    rapidosSubtituloLegacy: '{pagina} · se publican al guardar',
    textos: 'Textos de la portada',
    textosDetalle: 'Título, subtítulo y botón',
    fotos: 'Fotos',
    fotosDetalle: 'Portada, galería y platos',
    horario: 'Horario',
    horarioDetalle: 'De {sede} · se edita en Sucursales',
    agotados: 'Platos agotados hoy',
    agotadosDetalle: 'Disponibilidad en Carta',
    aviso: 'Aviso en el sitio',
    avisoEjemplo: 'Ej.: «Hoy cerramos a las 8:00 p. m.»',
    avisoAyuda: 'Sale en la barra superior del sitio. Déjalo vacío para quitarlo.',
    avisoPlaceholder: 'Hoy cerramos a las 8:00 p. m.',
    guardarBorrador: 'Guardar en borrador',
  },
} as const;

type Hoja = string;
type Arbol = { readonly [k: string]: Hoja | Arbol };

export function textoEditor(clave: string): string | undefined {
  let nodo: Hoja | Arbol | undefined = TEXTOS_EDITOR as unknown as Arbol;
  for (const parte of clave.split('.')) {
    if (!nodo || typeof nodo === 'string') return undefined;
    nodo = (nodo as Arbol)[parte];
  }
  return typeof nodo === 'string' ? nodo : undefined;
}

export type TraductorEditor = (clave: string, valores?: Record<string, string | number>) => string;

/** Textos de `sitioWeb.editor.*` en el idioma activo, con el español canónico de respaldo. */
export function useTextosEditor(): TraductorEditor {
  const t = useTranslations('sitioWeb');
  return useCallback(
    (clave: string, valores?: Record<string, string | number>) => {
      const completa = `editor.${clave}`;
      if (t.has(completa)) return t(completa, valores);
      const canon = textoEditor(clave);
      return canon !== undefined ? interpolar(canon, valores) : clave;
    },
    [t],
  );
}
