/** @jest-environment jsdom */
import { act, fireEvent, screen, waitFor } from '@testing-library/react';
import { renderConIdioma } from '@/test-utils/renderConIdioma';
import { pedirCrm, ErrorApiCrm } from '@/components/crm/acciones/apiCrm';
import { CampanaVozRequisitos } from '../nuevo/CampanaVozRequisitos';
import { MAX_BYTES_ARCHIVO_RNE } from '@/lib/services/crm/voiceAgent/rne';
jest.mock('@/components/crm/acciones/apiCrm',()=>({pedirCrm:jest.fn(),ErrorApiCrm:class extends Error{constructor(public status:number,public codigo:string){super(codigo);}}}));
jest.mock('@/lib/context/OrganizationTimezoneContext',()=>({useFormatDate:()=>({formatDateTime:(v:string)=>v})}));
const request=jest.mocked(pedirCrm),v1='2026-10-01T00:00:00.123456+00:00',v2='2026-10-01T00:01:00.123457+00:00';
const record={checked_at:'2026-10-01T00:00:00Z',valid_until:'2099-01-01T00:00:00Z',numbers_in_file:2,checked_targets:2,excluded_targets:1,evidence_available:true,audience_unchanged:true,vigente:true,campaign_updated_at:v2};
function fixture(disabled=false){const callbacks={onVersion:jest.fn(),onValid:jest.fn(),onBusy:jest.fn()};const view=renderConIdioma(<CampanaVozRequisitos campaignId="private-campaign" expectedUpdatedAt={v1} disabled={disabled} {...callbacks}/>);return {...view,...callbacks};}
function file(size?:number){const value=new File(['phone\n+570000000000'],'private.csv',{type:'text/csv'});Object.defineProperty(value,'text',{value:async()=> 'phone\n+570000000000'});if(size)Object.defineProperty(value,'size',{value:size});return value;}
beforeEach(()=>{jest.clearAllMocks();request.mockResolvedValue({data:null,extra:{puede_verificar:true}});});
it('usa la versión exacta propia del upload y sólo habilita constancia confirmada',async()=>{const d=fixture();await waitFor(()=>expect(d.container.querySelector('input[type="file"]')).toBeTruthy());request.mockResolvedValueOnce({data:record,extra:{}});fireEvent.change(d.container.querySelector('input[type="file"]')!,{target:{files:[file()]}});await waitFor(()=>expect(d.onVersion).toHaveBeenCalledWith(v2));expect(request).toHaveBeenLastCalledWith('/api/crm/voice-agents/campaigns/private-campaign/rne',expect.objectContaining({method:'POST',cuerpo:{nombre_archivo:'private.csv',contenido:'phone\n+570000000000',expected_updated_at:v1}}));expect(d.onValid).toHaveBeenLastCalledWith(true);expect(d.onBusy.mock.calls.map(v=>v[0])).toContain(true);expect(d.onBusy).toHaveBeenLastCalledWith(false);});
it('un conflicto conserva la versión y deja activación bloqueada',async()=>{const d=fixture();await waitFor(()=>expect(d.container.querySelector('input[type="file"]')).toBeTruthy());request.mockRejectedValueOnce(new ErrorApiCrm(409,'campana_modificada','Conflicto de versión'));fireEvent.change(d.container.querySelector('input[type="file"]')!,{target:{files:[file()]}});await screen.findByRole('alert');expect(d.onVersion).not.toHaveBeenCalled();expect(d.onValid).toHaveBeenLastCalledWith(false);});
it('upload duplicado/archivo grande no crea una segunda verificación',async()=>{const d=fixture();await waitFor(()=>expect(d.container.querySelector('input[type="file"]')).toBeTruthy());const input=d.container.querySelector('input[type="file"]')!;fireEvent.change(input,{target:{files:[file(MAX_BYTES_ARCHIVO_RNE+1)]}});expect(request).toHaveBeenCalledTimes(1);let resolve!:(v:Awaited<ReturnType<typeof pedirCrm>>)=>void;request.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));fireEvent.change(input,{target:{files:[file()]}});fireEvent.change(input,{target:{files:[file()]}});await waitFor(()=>expect(request).toHaveBeenCalledTimes(2));await act(async()=>{resolve({data:record,extra:{}});});expect(request).toHaveBeenCalledTimes(2);});
it('lectura fallida tiene retry real y no adopta versión del GET',async()=>{request.mockRejectedValueOnce(new Error('Fallo privado'));const d=fixture();await screen.findByRole('alert');request.mockResolvedValueOnce({data:record,extra:{puede_verificar:true}});fireEvent.click(screen.getByRole('button',{name:'Actualizar'}));await waitFor(()=>expect(d.onValid).toHaveBeenLastCalledWith(true));expect(d.onVersion).not.toHaveBeenCalled();expect(request).toHaveBeenCalledTimes(2);});
it('sin permiso o disabled no sube y un desmontaje aborta la lectura',async()=>{request.mockResolvedValueOnce({data:null,extra:{puede_verificar:false}});const d=fixture();await waitFor(()=>expect(d.onValid).toHaveBeenCalled());expect(d.container.querySelector('input[type="file"]')).toBeNull();const signal=request.mock.calls[0][1]?.signal;d.unmount();expect(signal?.aborted).toBe(true);});
