-- =====================================================================
-- Precios y costos por sede (sucursal) para todo tipo de producto.
--
-- Versión PROVISIONAL: el timestamp del nombre se sustituye por la versión
-- real al aplicar con `apply_migration` (ver docs/POLITICA-MIGRACIONES.md).
-- Diseño, resolución e impacto: docs/inventario/PRECIOS-POR-SEDE.md.
--
-- Decisión de modelo (diferente de la propuesta inicial, por qué):
--   La propuesta era añadir `branch_id NULL` a `product_prices` y
--   `product_costs`. Se descartó tras el análisis porque esas tablas las leen
--   y ESCRIBEN filtrando solo por `product_id` (2026-10-05):
--     * ~30 funciones SQL (fn_producto_int_fijar_precio/costo cierran TODAS
--       las filas vivas del producto; assistant_set_product_price cierra «la
--       más reciente»; fn_pos_precio_base_vigente, catálogos, historial…),
--     * los triggers trg_meta_price_sync (enviaría a Meta el precio de una
--       sede como precio del catálogo) y trg_membresias_precio_legado,
--     * ~45 archivos TS del ERP (deshacer del asistente borra/reabre por
--       product_id; el scraper inserta/cierra por product_id),
--     * el repositorio de la web (83 sitios, service role, se despliega
--       DESPUÉS): embebe `product_prices` con `effective_to is null` y toma
--       la más reciente → mostraría y cobraría el precio de una sede como
--       precio general.
--   Con la columna, la primera fila de sede contaminaría todos esos
--   lectores y escritores hasta parchearlos uno a uno. Con tablas propias
--   (`product_branch_prices` / `product_branch_costs`) el precio general
--   sigue en su tabla de siempre, intacto, y SOLO los consumidores que se
--   adaptan explícitamente ven los de sede. Equivale a la propuesta con
--   «branch_id NULL = general» viviendo en `product_prices`/`product_costs`.
--
-- Contenido:
--   1. Tablas product_branch_prices / product_branch_costs (+ coherencia,
--      índices, RLS de lectura por pertenencia; escritura solo por RPC).
--   2. Resolución: fn_precios_vigentes_lote / fn_costos_vigentes_lote y
--      fn_precio_vigente / fn_costo_vigente (SECURITY INVOKER).
--   3. Escritura: fn_productos_sede_fijar (RPC transaccional) y sus
--      auxiliares internas.
--   4. Recetas: fn_receta_costo_teorico_sede; fn_receta_costo y
--      fn_costo_unitario_producto pasan a usar el costo vigente de la sede.
--   5. POS: fn_pos_validar_linea_venta valida contra el precio de la sede de
--      la venta; pos_checkout_v1 le pasa la sede (parche de dos llamadas con
--      guarda md5).
--
-- Retrocompatibilidad: mientras no exista ninguna fila de sede, toda función
-- tocada devuelve exactamente lo de hoy (sede → general; sin sede → general).
-- Herencia hijo→padre: hoy NO existe en el POS ni en su validación; por eso
-- es opcional (`p_heredar_padre`, por defecto false).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Tablas
-- ---------------------------------------------------------------------
create table if not exists public.product_branch_prices (
  id              bigint generated by default as identity primary key,
  organization_id integer     not null references public.organizations(id) on delete cascade,
  branch_id       integer     not null references public.branches(id) on delete cascade,
  product_id      integer     not null references public.products(id) on delete cascade,
  price           numeric     not null,
  compare_price   numeric,
  effective_from  timestamptz not null default now(),
  effective_to    timestamptz,
  created_at      timestamptz not null default now(),
  created_by      uuid        default auth.uid(),
  constraint product_branch_prices_price_check check (price >= 0),
  constraint product_branch_prices_compare_check check (compare_price is null or compare_price >= 0),
  constraint product_branch_prices_vigencia_check check (effective_to is null or effective_to >= effective_from)
);

create table if not exists public.product_branch_costs (
  id              bigint generated by default as identity primary key,
  organization_id integer     not null references public.organizations(id) on delete cascade,
  branch_id       integer     not null references public.branches(id) on delete cascade,
  product_id      integer     not null references public.products(id) on delete cascade,
  cost            numeric     not null,
  supplier_id     integer     references public.suppliers(id),
  effective_from  timestamptz not null default now(),
  effective_to    timestamptz,
  created_at      timestamptz not null default now(),
  created_by      uuid        default auth.uid(),
  constraint product_branch_costs_cost_check check (cost >= 0),
  constraint product_branch_costs_vigencia_check check (effective_to is null or effective_to >= effective_from)
);

comment on table public.product_branch_prices is
  'Precio de venta de un producto en UNA sede, con vigencia. Sin fila vigente, la sede usa el precio general (product_prices). Se escribe solo con fn_productos_sede_fijar, se resuelve con fn_precios_vigentes_lote / fn_precio_vigente. Ver docs/inventario/PRECIOS-POR-SEDE.md.';
comment on table public.product_branch_costs is
  'Costo de un producto en UNA sede, con vigencia. Sin fila vigente, la sede usa el costo general (product_costs). Se escribe solo con fn_productos_sede_fijar, se resuelve con fn_costos_vigentes_lote / fn_costo_vigente.';
comment on column public.product_branch_prices.effective_to is
  'Fin de vigencia (excluido). NULL = abierta. A lo sumo una fila abierta por (producto, sede): índice parcial único.';
comment on column public.product_branch_costs.effective_to is
  'Fin de vigencia (excluido). NULL = abierta. A lo sumo una fila abierta por (producto, sede): índice parcial único.';

-- Una sola fila abierta por producto y sede (el historial tiene effective_to).
-- OJO: NO hay UNIQUE por (product_id, effective_from): dos sedes pueden fijar
-- precio en el mismo instante.
create unique index if not exists product_branch_prices_una_abierta
  on public.product_branch_prices (product_id, branch_id) where effective_to is null;
create unique index if not exists product_branch_costs_una_abierta
  on public.product_branch_costs (product_id, branch_id) where effective_to is null;

-- Búsqueda del vigente en un instante: (producto, sede, desde más reciente).
create index if not exists product_branch_prices_busqueda
  on public.product_branch_prices (product_id, branch_id, effective_from desc);
create index if not exists product_branch_costs_busqueda
  on public.product_branch_costs (product_id, branch_id, effective_from desc);

-- Listados por organización y sede (y la política RLS por organization_id).
create index if not exists product_branch_prices_org_sede
  on public.product_branch_prices (organization_id, branch_id);
create index if not exists product_branch_costs_org_sede
  on public.product_branch_costs (organization_id, branch_id);
create index if not exists product_branch_costs_supplier
  on public.product_branch_costs (supplier_id) where supplier_id is not null;

-- Coherencia: producto, sede (y proveedor) son de la organización de la fila.
create or replace function public.fn_producto_sede_tg_coherencia()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_supplier integer := nullif(to_jsonb(new)->>'supplier_id', '')::integer;
begin
  if not exists (select 1 from public.products p
                  where p.id = new.product_id and p.organization_id = new.organization_id) then
    raise exception 'producto_de_otra_organizacion' using errcode = '23514',
      detail = format('El producto %s no es de la organización %s.', new.product_id, new.organization_id);
  end if;
  if not exists (select 1 from public.branches b
                  where b.id = new.branch_id and b.organization_id = new.organization_id) then
    raise exception 'sucursal_de_otra_organizacion' using errcode = '23514',
      detail = format('La sede %s no es de la organización %s.', new.branch_id, new.organization_id);
  end if;
  if v_supplier is not null and not exists (select 1 from public.suppliers s
                  where s.id = v_supplier and s.organization_id = new.organization_id) then
    raise exception 'proveedor_de_otra_organizacion' using errcode = '23514',
      detail = format('El proveedor %s no es de la organización %s.', v_supplier, new.organization_id);
  end if;
  return new;
end;
$$;
revoke all on function public.fn_producto_sede_tg_coherencia() from public, anon, authenticated;

create or replace trigger trg_product_branch_prices_coherencia
  before insert or update of organization_id, branch_id, product_id on public.product_branch_prices
  for each row execute function public.fn_producto_sede_tg_coherencia();

create or replace trigger trg_product_branch_costs_coherencia
  before insert or update of organization_id, branch_id, product_id, supplier_id on public.product_branch_costs
  for each row execute function public.fn_producto_sede_tg_coherencia();

-- RLS: leen los miembros activos de la organización; nadie escribe directo
-- (sin políticas de escritura y sin privilegios): solo fn_productos_sede_fijar.
alter table public.product_branch_prices enable row level security;
alter table public.product_branch_costs  enable row level security;

do $pol$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_branch_prices' and policyname = 'product_branch_prices_miembros_select') then
    create policy product_branch_prices_miembros_select on public.product_branch_prices
      for select to authenticated
      using (exists (select 1 from public.organization_members om
                      where om.organization_id = product_branch_prices.organization_id
                        and om.user_id = (select auth.uid())
                        and om.is_active));
  end if;
end;
$pol$;

do $pol$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_branch_costs' and policyname = 'product_branch_costs_miembros_select') then
    create policy product_branch_costs_miembros_select on public.product_branch_costs
      for select to authenticated
      using (exists (select 1 from public.organization_members om
                      where om.organization_id = product_branch_costs.organization_id
                        and om.user_id = (select auth.uid())
                        and om.is_active));
  end if;
end;
$pol$;

revoke all on table public.product_branch_prices from public, anon;
revoke all on table public.product_branch_costs  from public, anon;
revoke insert, update, delete, truncate, references, trigger on table public.product_branch_prices from authenticated;
revoke insert, update, delete, truncate, references, trigger on table public.product_branch_costs  from authenticated;
grant select on table public.product_branch_prices to authenticated;
grant select on table public.product_branch_costs  to authenticated;
grant all on table public.product_branch_prices to service_role;
grant all on table public.product_branch_costs  to service_role;

-- ---------------------------------------------------------------------
-- 2. Resolución del vigente (precio y costo)
--
-- Orden para (producto, sede, instante):
--   1) fila vigente de la sede (product_branch_*)           origen 'sede'
--   2) fila vigente general (product_prices/product_costs)  origen 'general'
--   3) si p_heredar_padre y el producto es una variante:
--      lo mismo con el padre                                 'padre_sede' / 'padre_general'
-- Vigente = effective_from <= instante < coalesce(effective_to, infinito);
-- entre varias, la de effective_from más reciente y, a igualdad, id mayor
-- (la regla de fn_pos_precio_base_vigente y de src/lib/pos/precioVigente.ts).
--
-- SECURITY INVOKER: con la sesión de un usuario aplica la RLS de las cuatro
-- tablas (un producto de otra organización sale sin precio: no hay fuga);
-- llamadas desde funciones SECURITY DEFINER (validación del POS, recetas)
-- leen como su dueño. Una sede de otra organización no tiene filas (el
-- trigger de coherencia lo impide), así que resolvería al general.
-- ---------------------------------------------------------------------
create or replace function public.fn_precios_vigentes_lote(
  p_organization_id integer,
  p_branch_id integer,
  p_product_ids integer[],
  p_at timestamptz default null,
  p_heredar_padre boolean default false
)
returns table (
  product_id integer,
  precio numeric,
  precio_comparacion numeric,
  origen text,
  origen_product_id integer,
  origen_id bigint
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  with prm as (select coalesce(p_at, now()) as t),
  ids as (
    select p.id, p.parent_product_id
      from public.products p
     where p.organization_id = p_organization_id
       and p.id = any (coalesce(p_product_ids, '{}'::integer[]))
  )
  select i.id, x.precio, x.precio_comparacion, x.origen, x.origen_product_id, x.origen_id
    from ids i
    cross join prm
    left join lateral (
      select c.precio, c.precio_comparacion, c.origen, c.origen_product_id, c.origen_id
        from (
          select bp.price as precio, bp.compare_price as precio_comparacion, 'sede'::text as origen,
                 i.id as origen_product_id, bp.id as origen_id, 1 as prioridad, bp.effective_from as desde
            from public.product_branch_prices bp
           where p_branch_id is not null
             and bp.product_id = i.id and bp.branch_id = p_branch_id
             and bp.effective_from <= prm.t and (bp.effective_to is null or bp.effective_to > prm.t)
          union all
          select pp.price, pp.compare_price, 'general', i.id, pp.id::bigint, 2, pp.effective_from
            from public.product_prices pp
           where pp.product_id = i.id
             and pp.effective_from <= prm.t and (pp.effective_to is null or pp.effective_to > prm.t)
          union all
          select bp.price, bp.compare_price, 'padre_sede', i.parent_product_id, bp.id, 3, bp.effective_from
            from public.product_branch_prices bp
           where p_heredar_padre and p_branch_id is not null and i.parent_product_id is not null
             and bp.product_id = i.parent_product_id and bp.branch_id = p_branch_id
             and bp.effective_from <= prm.t and (bp.effective_to is null or bp.effective_to > prm.t)
          union all
          select pp.price, pp.compare_price, 'padre_general', i.parent_product_id, pp.id::bigint, 4, pp.effective_from
            from public.product_prices pp
           where p_heredar_padre and i.parent_product_id is not null
             and pp.product_id = i.parent_product_id
             and pp.effective_from <= prm.t and (pp.effective_to is null or pp.effective_to > prm.t)
        ) c
       order by c.prioridad, c.desde desc, c.origen_id desc
       limit 1
    ) x on true
$$;

create or replace function public.fn_costos_vigentes_lote(
  p_organization_id integer,
  p_branch_id integer,
  p_product_ids integer[],
  p_at timestamptz default null,
  p_heredar_padre boolean default false
)
returns table (
  product_id integer,
  costo numeric,
  supplier_id integer,
  origen text,
  origen_product_id integer,
  origen_id bigint
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  with prm as (select coalesce(p_at, now()) as t),
  ids as (
    select p.id, p.parent_product_id
      from public.products p
     where p.organization_id = p_organization_id
       and p.id = any (coalesce(p_product_ids, '{}'::integer[]))
  )
  select i.id, x.costo, x.supplier_id, x.origen, x.origen_product_id, x.origen_id
    from ids i
    cross join prm
    left join lateral (
      select c.costo, c.supplier_id, c.origen, c.origen_product_id, c.origen_id
        from (
          select bc.cost as costo, bc.supplier_id, 'sede'::text as origen,
                 i.id as origen_product_id, bc.id as origen_id, 1 as prioridad, bc.effective_from as desde
            from public.product_branch_costs bc
           where p_branch_id is not null
             and bc.product_id = i.id and bc.branch_id = p_branch_id
             and bc.effective_from <= prm.t and (bc.effective_to is null or bc.effective_to > prm.t)
          union all
          select pc.cost, pc.supplier_id, 'general', i.id, pc.id::bigint, 2, pc.effective_from
            from public.product_costs pc
           where pc.product_id = i.id
             and pc.effective_from <= prm.t and (pc.effective_to is null or pc.effective_to > prm.t)
          union all
          select bc.cost, bc.supplier_id, 'padre_sede', i.parent_product_id, bc.id, 3, bc.effective_from
            from public.product_branch_costs bc
           where p_heredar_padre and p_branch_id is not null and i.parent_product_id is not null
             and bc.product_id = i.parent_product_id and bc.branch_id = p_branch_id
             and bc.effective_from <= prm.t and (bc.effective_to is null or bc.effective_to > prm.t)
          union all
          select pc.cost, pc.supplier_id, 'padre_general', i.parent_product_id, pc.id::bigint, 4, pc.effective_from
            from public.product_costs pc
           where p_heredar_padre and i.parent_product_id is not null
             and pc.product_id = i.parent_product_id
             and pc.effective_from <= prm.t and (pc.effective_to is null or pc.effective_to > prm.t)
        ) c
       order by c.prioridad, c.desde desc, c.origen_id desc
       limit 1
    ) x on true
$$;

-- Versión de un producto: delega en el lote (una sola regla).
create or replace function public.fn_precio_vigente(
  p_product integer,
  p_branch integer,
  p_at timestamptz default null,
  p_heredar_padre boolean default false
)
returns numeric
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select l.precio
    from public.products p
    cross join lateral public.fn_precios_vigentes_lote(p.organization_id, p_branch, array[p.id], p_at, p_heredar_padre) l
   where p.id = p_product
$$;

create or replace function public.fn_costo_vigente(
  p_product integer,
  p_branch integer,
  p_at timestamptz default null,
  p_heredar_padre boolean default false
)
returns numeric
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select l.costo
    from public.products p
    cross join lateral public.fn_costos_vigentes_lote(p.organization_id, p_branch, array[p.id], p_at, p_heredar_padre) l
   where p.id = p_product
$$;

comment on function public.fn_precios_vigentes_lote(integer, integer, integer[], timestamptz, boolean) is
  'Precio vigente por producto para una sede en un instante: sede → general → (opcional) padre sede → padre general. SECURITY INVOKER (aplica RLS). origen dice de dónde salió. Ver docs/inventario/PRECIOS-POR-SEDE.md.';
comment on function public.fn_costos_vigentes_lote(integer, integer, integer[], timestamptz, boolean) is
  'Costo vigente por producto para una sede en un instante: sede → general → (opcional) padre sede → padre general. SECURITY INVOKER (aplica RLS).';
comment on function public.fn_precio_vigente(integer, integer, timestamptz, boolean) is
  'Precio vigente de un producto en una sede (NULL = sin precio). Delega en fn_precios_vigentes_lote.';
comment on function public.fn_costo_vigente(integer, integer, timestamptz, boolean) is
  'Costo vigente de un producto en una sede (NULL = sin costo). Delega en fn_costos_vigentes_lote.';

revoke all on function public.fn_precios_vigentes_lote(integer, integer, integer[], timestamptz, boolean) from public, anon;
revoke all on function public.fn_costos_vigentes_lote(integer, integer, integer[], timestamptz, boolean) from public, anon;
revoke all on function public.fn_precio_vigente(integer, integer, timestamptz, boolean) from public, anon;
revoke all on function public.fn_costo_vigente(integer, integer, timestamptz, boolean) from public, anon;
grant execute on function public.fn_precios_vigentes_lote(integer, integer, integer[], timestamptz, boolean) to authenticated, service_role;
grant execute on function public.fn_costos_vigentes_lote(integer, integer, integer[], timestamptz, boolean) to authenticated, service_role;
grant execute on function public.fn_precio_vigente(integer, integer, timestamptz, boolean) to authenticated, service_role;
grant execute on function public.fn_costo_vigente(integer, integer, timestamptz, boolean) to authenticated, service_role;

-- ---------------------------------------------------------------------
-- 3. Escritura: fijar precio/costo por sede
-- ---------------------------------------------------------------------
-- Auxiliares internas (mismo algoritmo que fn_producto_int_fijar_precio /
-- _costo, acotado a una sede): anula lo programado después de `desde`,
-- cierra lo que rige en `desde` y abre la nueva fila. NULL = quitar el precio
-- de la sede (vuelve a regir el general). Devuelven true si cambió algo.
create or replace function public.fn_producto_sede_int_fijar_precio(
  p_org integer, p_product_id integer, p_branch_id integer,
  p_precio numeric, p_comparacion numeric, p_desde timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_desde timestamptz := coalesce(p_desde, now());
  v_hay boolean;
  v_precio numeric;
  v_comp numeric;
  v_hay_futuros boolean;
begin
  if p_precio is not null and p_precio < 0 then
    raise exception 'precio_negativo' using errcode = '22023';
  end if;
  select true, bp.price, bp.compare_price into v_hay, v_precio, v_comp
    from public.product_branch_prices bp
   where bp.product_id = p_product_id and bp.branch_id = p_branch_id
     and bp.effective_from <= v_desde and (bp.effective_to is null or bp.effective_to > v_desde)
   order by bp.effective_from desc, bp.id desc limit 1;
  v_hay := coalesce(v_hay, false);
  select exists (select 1 from public.product_branch_prices bp
                  where bp.product_id = p_product_id and bp.branch_id = p_branch_id
                    and bp.effective_from > v_desde
                    and (bp.effective_to is null or bp.effective_to > bp.effective_from)) into v_hay_futuros;
  if not v_hay_futuros then
    if not v_hay and p_precio is null then
      return false;
    end if;
    if v_hay and p_precio is not null and v_precio = p_precio
       and coalesce(v_comp, 0) = coalesce(p_comparacion, 0) then
      return false;
    end if;
  end if;
  update public.product_branch_prices bp set effective_to = bp.effective_from
   where bp.product_id = p_product_id and bp.branch_id = p_branch_id
     and bp.effective_from > v_desde
     and (bp.effective_to is null or bp.effective_to > bp.effective_from);
  update public.product_branch_prices bp set effective_to = v_desde
   where bp.product_id = p_product_id and bp.branch_id = p_branch_id
     and bp.effective_from <= v_desde
     and (bp.effective_to is null or bp.effective_to > v_desde);
  if p_precio is not null then
    insert into public.product_branch_prices (organization_id, branch_id, product_id, price, compare_price, effective_from)
    values (p_org, p_branch_id, p_product_id, p_precio, nullif(p_comparacion, 0), v_desde);
  end if;
  return true;
end;
$$;

create or replace function public.fn_producto_sede_int_fijar_costo(
  p_org integer, p_product_id integer, p_branch_id integer,
  p_costo numeric, p_supplier_id integer, p_desde timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_desde timestamptz := coalesce(p_desde, now());
  v_hay boolean;
  v_costo numeric;
  v_supplier integer;
  v_hay_futuros boolean;
begin
  if p_costo is not null and p_costo < 0 then
    raise exception 'costo_negativo' using errcode = '22023';
  end if;
  select true, bc.cost, bc.supplier_id into v_hay, v_costo, v_supplier
    from public.product_branch_costs bc
   where bc.product_id = p_product_id and bc.branch_id = p_branch_id
     and bc.effective_from <= v_desde and (bc.effective_to is null or bc.effective_to > v_desde)
   order by bc.effective_from desc, bc.id desc limit 1;
  v_hay := coalesce(v_hay, false);
  select exists (select 1 from public.product_branch_costs bc
                  where bc.product_id = p_product_id and bc.branch_id = p_branch_id
                    and bc.effective_from > v_desde
                    and (bc.effective_to is null or bc.effective_to > bc.effective_from)) into v_hay_futuros;
  if not v_hay_futuros then
    if not v_hay and p_costo is null then
      return false;
    end if;
    if v_hay and p_costo is not null and v_costo = p_costo
       and v_supplier is not distinct from coalesce(p_supplier_id, v_supplier) then
      return false;
    end if;
  end if;
  update public.product_branch_costs bc set effective_to = bc.effective_from
   where bc.product_id = p_product_id and bc.branch_id = p_branch_id
     and bc.effective_from > v_desde
     and (bc.effective_to is null or bc.effective_to > bc.effective_from);
  update public.product_branch_costs bc set effective_to = v_desde
   where bc.product_id = p_product_id and bc.branch_id = p_branch_id
     and bc.effective_from <= v_desde
     and (bc.effective_to is null or bc.effective_to > v_desde);
  if p_costo is not null then
    insert into public.product_branch_costs (organization_id, branch_id, product_id, cost, supplier_id, effective_from)
    values (p_org, p_branch_id, p_product_id, p_costo, p_supplier_id, v_desde);
  end if;
  return true;
end;
$$;

revoke all on function public.fn_producto_sede_int_fijar_precio(integer, integer, integer, numeric, numeric, timestamptz) from public, anon, authenticated;
revoke all on function public.fn_producto_sede_int_fijar_costo(integer, integer, integer, numeric, integer, timestamptz) from public, anon, authenticated;

-- RPC pública: fija (o quita) el precio o el costo de uno o varios productos
-- en una o varias sedes, en UNA transacción. Con p_incluir_variantes, cada
-- padre arrastra a todas sus variantes no eliminadas.
--   p_tipo: 'precio' | 'costo'
--   p_valor: NULL = quitar el de la sede (rige el general)
--   p_desde: NULL = ahora; no se admite el pasado (cambiaría ventas cerradas)
-- Permisos: los de fn_productos_precio_masivo. Organización: un producto,
-- una sede o un proveedor ajenos rechazan el lote entero (42501).
create or replace function public.fn_productos_sede_fijar(
  p_organization_id integer,
  p_tipo text,
  p_branch_ids integer[],
  p_product_ids integer[],
  p_valor numeric,
  p_comparacion numeric default null,
  p_desde timestamptz default null,
  p_incluir_variantes boolean default false,
  p_supplier_id integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_desde timestamptz := coalesce(p_desde, now());
  v_sedes integer[];
  v_pedidos integer[];
  v_productos integer[];
  v_omitidos integer := 0;
  v_p integer;
  v_b integer;
  v_cambio boolean;
  v_cambiados integer := 0;
  v_sin_cambio integer := 0;
begin
  perform public.fn_productos_exigir_permiso(p_organization_id,
    array['inventory.edit', 'product_management', 'inventory_management']);

  if p_tipo is null or p_tipo not in ('precio', 'costo') then
    raise exception 'tipo_invalido' using errcode = '22023';
  end if;
  if p_valor is not null and p_valor < 0 then
    raise exception 'valor_negativo' using errcode = '22023';
  end if;
  if p_comparacion is not null and (p_comparacion < 0 or p_tipo <> 'precio') then
    raise exception 'comparacion_invalida' using errcode = '22023';
  end if;
  if p_supplier_id is not null and p_tipo <> 'costo' then
    raise exception 'proveedor_no_aplica' using errcode = '22023';
  end if;
  if v_desde < now() - interval '5 minutes' then
    raise exception 'desde_en_el_pasado' using errcode = '22023';
  end if;

  select coalesce(array_agg(distinct x order by x), '{}') into v_sedes
    from unnest(coalesce(p_branch_ids, '{}'::integer[])) x where x is not null;
  select coalesce(array_agg(distinct x order by x), '{}') into v_pedidos
    from unnest(coalesce(p_product_ids, '{}'::integer[])) x where x is not null;
  if cardinality(v_sedes) = 0 or cardinality(v_pedidos) = 0 then
    raise exception 'lote_vacio' using errcode = '22023';
  end if;
  if cardinality(v_sedes) > 200 or cardinality(v_pedidos) > 1000 then
    raise exception 'lote_demasiado_grande' using errcode = '22023';
  end if;

  -- Pertenencia: una sola sede, producto o proveedor ajeno rechaza el lote.
  if (select count(*) from public.branches b
       where b.organization_id = p_organization_id and b.id = any (v_sedes)) <> cardinality(v_sedes) then
    raise exception 'sucursal_de_otra_organizacion' using errcode = '42501';
  end if;
  if (select count(*) from public.products p
       where p.organization_id = p_organization_id and p.id = any (v_pedidos)) <> cardinality(v_pedidos) then
    raise exception 'producto_de_otra_organizacion' using errcode = '42501';
  end if;
  if p_supplier_id is not null and not exists (select 1 from public.suppliers s
       where s.id = p_supplier_id and s.organization_id = p_organization_id) then
    raise exception 'proveedor_de_otra_organizacion' using errcode = '42501';
  end if;

  -- Productos efectivos: los pedidos (no eliminados) y, si se pide, sus variantes.
  select coalesce(array_agg(distinct p.id order by p.id), '{}') into v_productos
    from public.products p
   where p.organization_id = p_organization_id
     and coalesce(p.status, 'active') <> 'deleted'
     and (p.id = any (v_pedidos)
          or (p_incluir_variantes and p.parent_product_id = any (v_pedidos)));
  v_omitidos := (select count(*) from public.products p
                  where p.organization_id = p_organization_id and p.id = any (v_pedidos)
                    and coalesce(p.status, 'active') = 'deleted');
  if cardinality(v_productos) * cardinality(v_sedes) > 20000 then
    raise exception 'lote_demasiado_grande' using errcode = '22023';
  end if;

  -- Bloqueo en orden de id: dos escrituras simultáneas no se cruzan.
  perform 1 from public.products p
   where p.id = any (v_productos) and p.organization_id = p_organization_id
   order by p.id
     for update;

  foreach v_p in array v_productos loop
    foreach v_b in array v_sedes loop
      if p_tipo = 'precio' then
        v_cambio := public.fn_producto_sede_int_fijar_precio(p_organization_id, v_p, v_b, p_valor, p_comparacion, v_desde);
      else
        v_cambio := public.fn_producto_sede_int_fijar_costo(p_organization_id, v_p, v_b, p_valor, p_supplier_id, v_desde);
      end if;
      if v_cambio then
        v_cambiados := v_cambiados + 1;
      else
        v_sin_cambio := v_sin_cambio + 1;
      end if;
    end loop;
  end loop;

  return jsonb_build_object(
    'tipo', p_tipo,
    'desde', v_desde,
    'productos', cardinality(v_productos),
    'sedes', cardinality(v_sedes),
    'cambiados', v_cambiados,
    'sin_cambio', v_sin_cambio,
    'omitidos_eliminados', v_omitidos);
end;
$$;

comment on function public.fn_productos_sede_fijar(integer, text, integer[], integer[], numeric, numeric, timestamptz, boolean, integer) is
  'Fija o quita (p_valor NULL) el precio o costo de productos en sedes, en una transacción: cierra el vigente (effective_to) y abre el nuevo. Permisos de precios masivos · producto/sede/proveedor ajeno → 42501.';

revoke all on function public.fn_productos_sede_fijar(integer, text, integer[], integer[], numeric, numeric, timestamptz, boolean, integer) from public, anon;
grant execute on function public.fn_productos_sede_fijar(integer, text, integer[], integer[], numeric, numeric, timestamptz, boolean, integer) to authenticated, service_role;

-- ---------------------------------------------------------------------
-- 4. Recetas y costo unitario por sede
-- ---------------------------------------------------------------------
-- Costo teórico de una receta en una sede: Σ (cantidad bruta en unidad del
-- insumo × costo vigente del insumo en la sede). Las cantidades salen de
-- fn_receta_int_calcular (la misma regla de merma y de conversión de unidad
-- que descuenta el stock: bruta = neta / (1 − merma/100)); no se recalculan.
-- A diferencia de fn_receta_costo, NO usa el costo promedio del inventario:
-- es el costo de catálogo de la sede.
create or replace function public.fn_receta_costo_teorico_sede(
  p_organization_id integer,
  p_branch_id integer,
  p_recipe_id integer,
  p_at timestamptz default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_at timestamptz := coalesce(p_at, now());
  v_rec jsonb;
  v_ver boolean;
  v_rinde numeric;
  v_lineas jsonb;
  v_tanda numeric;
  v_sin integer;
  v_err integer;
begin
  perform public.fn_assert_acceso_org(p_organization_id);
  if p_branch_id is not null and not exists (
       select 1 from public.branches b where b.id = p_branch_id and b.organization_id = p_organization_id) then
    raise exception 'sucursal_invalida' using errcode = '22023';
  end if;
  v_rec := public.fn_receta_int_a_jsonb(p_recipe_id);
  if v_rec is null or (v_rec->>'organization_id')::integer <> p_organization_id then
    raise exception 'receta_no_encontrada' using errcode = 'P0002';
  end if;
  v_ver := public.fn_receta_int_puede_ver_costos(p_organization_id);
  v_rinde := coalesce(nullif(nullif(v_rec->>'yield_qty', '')::numeric, 0), 1);

  with k as (
    select c.*, cv.costo as costo_unitario, coalesce(cv.origen, 'sin_costo') as fuente
      from public.fn_receta_int_calcular(p_organization_id, v_rec, v_rinde) c
      left join lateral public.fn_costos_vigentes_lote(p_organization_id, p_branch_id, array[c.ingredient_product_id], v_at) cv
        on true
  ), m as (
    select k.*, case when k.costo_unitario is not null and k.factor is not null then k.cantidad * k.costo_unitario end as costo_linea
      from k
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'orden', m.orden,
           'ingredient_product_id', m.ingredient_product_id,
           'nombre', m.nombre,
           'unidad_receta', m.unidad_receta,
           'unidad_ingrediente', m.unidad_ingrediente,
           'cantidad_neta', round(m.cantidad_neta, 6),
           'merma_pct', m.merma_pct,
           'cantidad_bruta', round(m.cantidad_bruta, 6),
           'factor', m.factor,
           'cantidad', round(m.cantidad, 6),
           'opcional', m.opcional,
           'fuente', m.fuente,
           'costo_unitario', case when v_ver then m.costo_unitario end,
           'costo_linea', case when v_ver then round(m.costo_linea, 4) end,
           'error', m.error) order by m.orden), '[]'::jsonb),
         sum(m.costo_linea) filter (where not m.opcional),
         count(*) filter (where not m.opcional and m.costo_unitario is null and m.error is null),
         count(*) filter (where m.error is not null)
    into v_lineas, v_tanda, v_sin, v_err
    from m;

  return jsonb_build_object(
    'permitido', v_ver,
    'branch_id', p_branch_id,
    'instante', v_at,
    'rinde', v_rinde,
    'costo_tanda', case when v_ver then round(coalesce(v_tanda, 0), 4) end,
    'costo_unidad', case when v_ver then round(coalesce(v_tanda, 0) / v_rinde, 4) end,
    'completo', coalesce(v_sin, 0) = 0 and coalesce(v_err, 0) = 0,
    'lineas_sin_costo', coalesce(v_sin, 0),
    'lineas_con_error', coalesce(v_err, 0),
    'lineas', v_lineas);
end;
$$;

revoke all on function public.fn_receta_costo_teorico_sede(integer, integer, integer, timestamptz) from public, anon;
grant execute on function public.fn_receta_costo_teorico_sede(integer, integer, integer, timestamptz) to authenticated, service_role;

-- fn_receta_costo: el «costo vigente» del insumo pasa a ser el de la sede
-- (fn_costo_vigente). Sin costo de sede, es el general: igual que antes.
-- Único cambio respecto de la versión viva: la subconsulta `vigente`.
CREATE OR REPLACE FUNCTION public.fn_receta_costo(p_organization_id integer, p_branch_id integer, p_receta jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_rec jsonb := p_receta;
  v_ver boolean;
  v_rinde numeric;
  v_lineas jsonb;
  v_tanda numeric;
  v_sin integer;
  v_err integer;
begin
  perform public.fn_assert_acceso_org(p_organization_id);
  if p_branch_id is not null and not exists (
       select 1 from public.branches b where b.id = p_branch_id and b.organization_id = p_organization_id) then
    raise exception 'sucursal_invalida' using errcode = '22023';
  end if;
  if p_receta ? 'recipe_id' then
    v_rec := public.fn_receta_int_a_jsonb(nullif(p_receta->>'recipe_id', '')::integer);
    if v_rec is null or (v_rec->>'organization_id')::integer <> p_organization_id then
      raise exception 'receta_no_encontrada' using errcode = 'P0002';
    end if;
  end if;
  v_ver := public.fn_receta_int_puede_ver_costos(p_organization_id);
  v_rinde := coalesce(nullif(nullif(v_rec->>'yield_qty', '')::numeric, 0), 1);

  with l as (
    select c.*,
           (select sl.avg_cost from public.stock_levels sl
             where sl.product_id = c.ingredient_product_id and sl.branch_id = p_branch_id and sl.lot_id is null
             limit 1) as promedio,
           public.fn_costo_vigente(c.ingredient_product_id, p_branch_id, now()) as vigente,
           (select sum(sl.qty_on_hand) from public.stock_levels sl
             where sl.product_id = c.ingredient_product_id and sl.branch_id = p_branch_id) as existencia
      from public.fn_receta_int_calcular(p_organization_id, v_rec, v_rinde) c
  ), k as (
    select l.*,
           case when coalesce(l.promedio, 0) > 0 then l.promedio
                when coalesce(l.vigente, 0) > 0 then l.vigente end as costo_unitario,
           case when coalesce(l.promedio, 0) > 0 then 'promedio_sucursal'
                when coalesce(l.vigente, 0) > 0 then 'costo_vigente'
                else 'sin_costo' end as fuente
      from l
  ), m as (
    select k.*, case when k.costo_unitario is not null and k.factor is not null then k.cantidad * k.costo_unitario end as costo_linea
      from k
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'orden', m.orden,
           'ingredient_product_id', m.ingredient_product_id,
           'nombre', m.nombre,
           'sku', m.sku,
           'track_stock', m.track_stock,
           'unidad_receta', m.unidad_receta,
           'unidad_ingrediente', m.unidad_ingrediente,
           'cantidad_neta', round(m.cantidad_neta, 6),
           'merma_pct', m.merma_pct,
           'cantidad_bruta', round(m.cantidad_bruta, 6),
           'factor', m.factor,
           'cantidad', round(m.cantidad, 6),
           'opcional', m.opcional,
           'existencia', m.existencia,
           'fuente', m.fuente,
           'costo_unitario', case when v_ver then m.costo_unitario end,
           'costo_linea', case when v_ver then round(m.costo_linea, 4) end,
           'error', m.error) order by m.orden), '[]'::jsonb),
         sum(m.costo_linea) filter (where not m.opcional),
         count(*) filter (where not m.opcional and m.costo_unitario is null and m.error is null),
         count(*) filter (where m.error is not null)
    into v_lineas, v_tanda, v_sin, v_err
    from m;

  return jsonb_build_object(
    'permitido', v_ver,
    'rinde', v_rinde,
    'unidad_rinde', nullif(upper(btrim(coalesce(v_rec->>'yield_unit_code', ''))), ''),
    'costo_tanda', case when v_ver then round(coalesce(v_tanda, 0), 4) end,
    'costo_unidad', case when v_ver then round(coalesce(v_tanda, 0) / v_rinde, 4) end,
    'completo', coalesce(v_sin, 0) = 0 and coalesce(v_err, 0) = 0,
    'lineas_sin_costo', coalesce(v_sin, 0),
    'lineas_con_error', coalesce(v_err, 0),
    'lineas', v_lineas);
end;
$function$;

-- fn_costo_unitario_producto: promedio de la sede → costo vigente DE LA SEDE
-- (antes: general) → fallback. Sin costo de sede, igual que antes.
CREATE OR REPLACE FUNCTION public.fn_costo_unitario_producto(p_product_id integer, p_branch_id integer, p_fallback numeric DEFAULT NULL::numeric)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_costo numeric;
BEGIN
    SELECT avg_cost INTO v_costo
    FROM stock_levels
    WHERE product_id = p_product_id
      AND branch_id = p_branch_id
      AND lot_id IS NULL
    LIMIT 1;

    IF COALESCE(v_costo, 0) > 0 THEN
        RETURN v_costo;
    END IF;

    v_costo := public.fn_costo_vigente(p_product_id, p_branch_id, now());

    IF COALESCE(v_costo, 0) > 0 THEN
        RETURN v_costo;
    END IF;

    RETURN COALESCE(p_fallback, 0);
END;
$function$;

-- ---------------------------------------------------------------------
-- 5. POS: validación del precio con la sede de la venta
-- ---------------------------------------------------------------------
-- Nueva firma con la sede (la decide el servidor: pos_checkout_v1 ya
-- comprobó que es de la organización) y la tolerancia offline:
--   p_branch_id NULL         → exactamente la regla de hoy (precio general)
--   p_branch_id con valor    → precio de la sede (o general si no tiene)
--   p_aceptar_general = true → además acepta el general: el catálogo local
--     del escritorio aún no replica precios de sede (venta sin conexión).
CREATE OR REPLACE FUNCTION public.fn_pos_validar_linea_venta(
  p_org integer, p_actor uuid, p_item jsonb, p_created_at timestamp with time zone, p_autorizacion jsonb,
  p_branch_id integer, p_aceptar_general boolean)
 RETURNS void
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_product  integer := nullif(p_item->>'product_id', '')::integer;
  v_qty      numeric := (p_item->>'quantity')::numeric;
  v_price    numeric := coalesce((p_item->>'unit_price')::numeric, 0);
  v_disc     numeric := coalesce((p_item->>'discount_amount')::numeric, 0);
  v_rate     numeric := coalesce((p_item->>'tax_rate')::numeric, 0);
  v_incl     boolean := coalesce((p_item->>'tax_included')::boolean, false);
  v_total    numeric := coalesce((p_item->>'total')::numeric, 0);
  v_tax      numeric := coalesce((p_item->>'tax_amount')::numeric, 0);
  v_mods     jsonb;
  v_extra    numeric;
  v_base     numeric;
  v_general  numeric;
  v_hay_base boolean := false;
  v_ok       boolean := false;
  v_momento  timestamptz;
  v_priced   timestamptz;
  v_net      numeric;
  v_exp_tax  numeric;
  v_exp_tot  numeric;
  v_nombre   text;
begin
  if v_product is null then
    raise exception 'producto_invalido' using errcode = '22023',
      detail = 'La línea no trae producto.';
  end if;
  select p.name into v_nombre from public.products p where p.id = v_product and p.organization_id = p_org;
  if not found then
    raise exception 'producto_invalido' using errcode = '22023',
      detail = format('El producto %s no es de la organización.', v_product);
  end if;
  -- Producto eliminado (20260930234100): no se vende, salvo que la línea sea
  -- anterior a la baja (venta sin conexión: hora del equipo; mesa: hora de la línea).
  perform public.fn_producto_exigir_vendible(p_org, v_product, p_created_at);
  -- Productos por peso o medida (20260929120100): decimales, mínimo y origen del peso.
  perform public.fn_pos_validar_pesaje(p_org, p_actor, p_item);

  if v_disc > round(v_qty * v_price, 2) + 0.01 then
    raise exception 'descuento_excede_linea' using errcode = '22023',
      detail = format('Producto %s: descuento %s mayor que la línea %s.', v_product, v_disc, round(v_qty * v_price, 2));
  end if;
  if v_disc > 0 then
    perform public.fn_pos_autorizar_descuento(p_org, p_actor, p_item, p_autorizacion);
  end if;

  -- Modificadores: los del sobre o, en sobres antiguos, los de las notas.
  v_mods := case
    when jsonb_typeof(p_item->'modifiers') = 'array'
         and exists (select 1 from jsonb_array_elements(p_item->'modifiers') m
                      where coalesce(m->>'modifier_id', m->>'modifierId') is not null)
      then p_item->'modifiers'
    when jsonb_typeof(p_item->'notes'->'modifiers') = 'array' then p_item->'notes'->'modifiers'
    else p_item->'modifiers'
  end;
  v_extra := public.fn_pos_extra_modificadores(p_org, v_product, v_mods);
  if v_extra is null then
    raise exception 'modificador_invalido' using errcode = '22023',
      detail = format('Producto %s: un modificador no está configurado para el producto.', v_product);
  end if;

  v_priced := nullif(p_item->>'priced_at', '')::timestamptz;
  for v_momento in
    select m from unnest(array[
      now(),
      case when p_created_at between now() - interval '30 days' and now() + interval '5 minutes' then p_created_at end,
      case when v_priced between now() - interval '30 days' and now() + interval '5 minutes' then v_priced end
    ]) m
    where m is not null
  loop
    v_base := case when p_branch_id is null
                   then public.fn_pos_precio_base_vigente(v_product, v_momento)
                   else public.fn_precio_vigente(v_product, p_branch_id, v_momento) end;
    if v_base is not null then
      v_hay_base := true;
      if abs(v_base + v_extra - v_price) <= 0.01 then
        v_ok := true;
        exit;
      end if;
    end if;
    if p_aceptar_general and p_branch_id is not null then
      v_general := public.fn_pos_precio_base_vigente(v_product, v_momento);
      if v_general is not null then
        v_hay_base := true;
        if abs(v_general + v_extra - v_price) <= 0.01 then
          v_ok := true;
          exit;
        end if;
      end if;
    end if;
  end loop;
  if not v_hay_base then
    raise exception 'precio_no_vigente' using errcode = '22023',
      detail = format('«%s» (producto %s) no tiene precio vigente.', v_nombre, v_product);
  end if;
  if not v_ok then
    raise exception 'precio_no_coincide' using errcode = '22023',
      detail = format('«%s» (producto %s): precio enviado %s, vigente %s.', v_nombre, v_product, v_price,
                      case when p_branch_id is null
                           then public.fn_pos_precio_base_vigente(v_product, now())
                           else public.fn_precio_vigente(v_product, p_branch_id, now()) end + v_extra);
  end if;

  -- Regla única de la línea (la misma de POSService.checkout).
  if v_rate < 0 or v_rate > 100 then
    raise exception 'linea_incoherente' using errcode = '22023',
      detail = format('Producto %s: tasa de impuesto %s fuera de rango.', v_product, v_rate);
  end if;
  v_net := v_qty * v_price - v_disc;
  v_exp_tax := round(case when v_incl then v_net - v_net / (1 + v_rate / 100) else v_net * v_rate / 100 end, 2);
  v_exp_tot := case when v_incl then v_net else v_net + v_exp_tax end;
  if abs(v_total - v_exp_tot) > 0.05 or abs(v_tax - v_exp_tax) > 0.05 then
    raise exception 'linea_incoherente' using errcode = '22023',
      detail = format('Producto %s: total %s / impuesto %s · esperado %s / %s.', v_product, v_total, v_tax, v_exp_tot, v_exp_tax);
  end if;
end;
$function$;

revoke all on function public.fn_pos_validar_linea_venta(integer, uuid, jsonb, timestamp with time zone, jsonb, integer, boolean) from public, anon, authenticated;

-- La firma de 5 argumentos queda como envoltorio: sin sede, la regla de hoy.
CREATE OR REPLACE FUNCTION public.fn_pos_validar_linea_venta(p_org integer, p_actor uuid, p_item jsonb, p_created_at timestamp with time zone, p_autorizacion jsonb)
 RETURNS void
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  perform public.fn_pos_validar_linea_venta(p_org, p_actor, p_item, p_created_at, p_autorizacion, null::integer, false);
end;
$function$;

revoke all on function public.fn_pos_validar_linea_venta(integer, uuid, jsonb, timestamp with time zone, jsonb) from public, anon, authenticated;

-- pos_checkout_v1 (43 KB): se cambian SOLO sus dos llamadas a la validación
-- para pasarle la sede. En vez de copiar el cuerpo entero (y arriesgar
-- revertir un cambio ajeno), se parchea el cuerpo vivo con guarda md5:
--   md5 = 8580166ba442c69ad9757f75f613c24d → se aplica el parche
--   md5 = 32a99ca1eb51eb44e28a2ed851157094 → ya aplicado (idempotente)
--   otro → alguien cambió la función después del análisis: se aborta.
-- Llamada 1 (venta nueva): sede del sobre, ya validada contra la organización
--   por pos_checkout_v1; offline acepta también el general.
-- Llamada 2 (mesa): sede de la venta guardada.
do $$
declare
  v_oid regprocedure := 'public.pos_checkout_v1(jsonb)'::regprocedure;
  v_md5 text;
  v_def text;
begin
  select md5(p.prosrc) into v_md5 from pg_proc p where p.oid = v_oid;
  if v_md5 = '32a99ca1eb51eb44e28a2ed851157094' then
    raise notice 'pos_checkout_v1 ya pasa la sede a la validación, nada que hacer';
    return;
  end if;
  if v_md5 is distinct from '8580166ba442c69ad9757f75f613c24d' then
    raise exception 'pos_checkout_v1 cambió desde el análisis (md5 %) · regenerar el parche', v_md5;
  end if;
  v_def := pg_get_functiondef(v_oid);
  v_def := replace(v_def,
    $o1$perform public.fn_pos_validar_linea_venta(v_org, v_actor, v_item, v_hora_precio, p_envelope->'discount_authorization')$o1$ || chr(59),
    $n1$perform public.fn_pos_validar_linea_venta(v_org, v_actor, v_item, v_hora_precio, p_envelope->'discount_authorization', v_branch, v_sin_conexion)$n1$ || chr(59));
  v_def := replace(v_def,
    $o2$'priced_at', v_si.created_at), v_si.created_at, null)$o2$ || chr(59),
    $n2$'priced_at', v_si.created_at), v_si.created_at, null, coalesce((select s.branch_id from public.sales s where s.id = v_sale_id), v_branch), false)$n2$ || chr(59));
  execute v_def;
  select md5(p.prosrc) into v_md5 from pg_proc p where p.oid = v_oid;
  if v_md5 <> '32a99ca1eb51eb44e28a2ed851157094' then
    raise exception 'el parche de pos_checkout_v1 no produjo el cuerpo esperado (md5 %)', v_md5;
  end if;
end;
$$;
