'use client';

/**
 * Textos del área «ventas» del módulo Sitio web (`sitioWeb.ventas.*`): Ventas
 * en línea (B/10), Tienda y Sedes en la web (B/11). `TEXTOS_VENTAS` es el
 * español canónico y la fuente de ventas.es.json; mientras el integrador
 * fusiona las claves en messages/*.json, `useTextosVentas` muestra este
 * español en vez de la clave cruda (el patrón de `useTextosComun`).
 */
import { useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { interpolar } from '../ui/textos';

export const TEXTOS_VENTAS = {
  ventas: {
    subtitulo: 'Pagos, envíos, promociones, pedidos y reservas de tu sitio',
    nombreContenido: 'las ventas del sitio',
    recargar: 'Recargar',
    reintentar: 'Reintentar',
    probarCompra: 'Probar una compra',
    probarCompraSinSitio: 'Publica tu sitio para probar una compra',
    verSitio: 'Ver sitio',
    irConfiguracion: 'Ir a Configuración',
    progreso: {
      titulo: '{listos} de {total} listos para vender',
      corto: '{listos} de {total} listos',
      etiqueta: 'Avance para vender en línea',
      falta: 'Falta: {lista}.',
      todoListo: 'Tu sitio tiene todo para vender.',
    },
    faltan: {
      checkout: 'crear el sitio',
      pagos: 'mostrar al menos un método de pago en la web',
      envios: 'tarifas de envío',
      enviosSoloPlana: 'tarifas de envío por zona (hoy solo tarifa plana)',
      pedidos: 'activar los pedidos en línea',
      pasarela: 'conectar una pasarela de pago',
    },
    temas: {
      checkout: 'Checkout del sitio',
      pagos: 'Métodos de pago en la web',
      envios: 'Envíos',
      cupones: 'Cupones y promociones',
      pedidos: 'Pedidos online',
      reservas: 'Reservas de mesas en la web',
      pasarela: 'Pasarela de pago',
    },
    temasCortos: {
      checkout: 'Checkout del sitio',
      pagos: 'Métodos de pago',
      envios: 'Envíos',
      cupones: 'Cupones',
      pedidos: 'Pedidos online',
      reservas: 'Reservas en la web',
      pasarela: 'Pasarela',
    },
    marcas: {
      ok: 'Listo',
      alerta: 'Revisar',
      neutro: 'Sin configurar',
    },
    estados: {
      configurado: 'Configurado',
      falta: 'Falta',
      opcional: 'Opcional',
      disponible: 'Disponible con {modulo}',
    },
    filas: {
      compraInvitado: 'Compra como invitado',
      pedidoMinimo: 'Pedido mínimo',
      sellosLogos: 'Sellos de confianza y logos de pago',
      tarifaPlana: 'Tarifa plana',
      envioGratisDesde: 'Envío gratis desde',
      tarifasZona: 'Tarifas por zona visibles en la web',
      cuponesUsables: 'Cupones activos usables en la web',
      promocionesWeb: 'Promociones activas en la web',
      pendientes: 'Pendientes de confirmar',
      pagadosHoy: 'Pagados hoy',
      ventaEnLinea: 'Pedidos en línea',
      avisosCliente: 'Avisos al cliente',
      firmaEventos: 'Firma de eventos',
      sinPasarela: 'Pasarela conectada',
      pasarelaNoVisible: 'Método de la pasarela en la web',
      conectada: '{proveedor} conectado',
    },
    valores: {
      si: 'Sí',
      no: 'No',
      visible: 'Visible',
      visibles: 'Visibles',
      oculto: 'Oculto',
      ocultos: 'Ocultos',
      sinMinimo: 'Sin mínimo',
      noAplica: 'No aplica',
      activos: 'Activos',
      apagados: 'Apagados',
      recibiendo: 'Recibiendo',
      apagada: 'Apagada',
      pedidosHoy: '{cantidad} · {total}',
      produccion: 'Producción',
      pruebas: 'Pruebas',
      firmaVerificada: 'Verificada',
      firmaNoCoincide: 'No coincide',
      firmaSinEventos: 'Sin eventos aún',
      ultimoPago: 'último pago {cuando}',
      ninguno: 'Ninguno',
      o: 'o',
      canales: { correo: 'Correo', whatsapp: 'WhatsApp' },
    },
    origen: {
      checkout: 'Se edita aquí',
      pagos: 'Visibles y orden se configuran en Finanzas',
      envios: 'Las tarifas por zona viven en Transporte',
      enviosPlana: 'Tarifa plana del sitio · se edita aquí',
      cupones: 'Se crean en el POS',
      pedidos: 'Se atienden en el POS',
      reservas: 'Configuración de reservas por sede',
      pasarela: 'Se conecta en Integraciones',
    },
    acciones: {
      editarOpciones: 'Editar opciones',
      irFinanzasMetodos: 'Ir a Finanzas › Métodos de pago',
      irTransporteTarifas: 'Ir a Transporte › Tarifas de envío',
      irPosPromociones: 'Ir a POS › Promociones y cupones',
      irPosPedidos: 'Ir a POS › Pedidos online',
      irPosReservas: 'Ir a POS › Reservas › Configuración',
      irIntegraciones: 'Ir a Integraciones',
      gestionarTarifas: 'Gestionar tarifas de envío',
      disponibleCon: 'Disponible con {modulo}',
      disponibleConDetalle: 'Tu plan no incluye {modulo} o no tienes acceso a esa página.',
      verDetalle: 'Ver detalle de {tema}',
    },
    reservas: {
      interruptor: 'Mostrar «Reservar mesa» en el sitio',
      ayuda: 'Atajo del interruptor «Recibir reservas en la web» de cada sede.',
      sinConfigurar: 'Aún no configuras las reservas. Hazlo en POS › Reservas de mesas.',
      activadas: 'El sitio ya muestra «Reservar mesa».',
      desactivadas: 'El sitio ya no muestra «Reservar mesa».',
      error: 'No pudimos cambiar las reservas en la web: {mensaje}',
    },
    resumen: {
      checkout: '{invitado} · {minimo}',
      invitado: 'Invitado',
      conCuenta: 'Con cuenta',
      minimo: 'mínimo {valor}',
      pagosVacio: 'Ninguno visible',
      enviosZonas: '{n} tarifas por zona',
      enviosSinZonas: 'Sin tarifas por zona',
      cupones: '{n} activos',
      pedidos: '{n} por confirmar',
      reservasRecibiendo: '{sedes} recibiendo',
      reservasApagadas: 'Ninguna sede recibe',
      pasarela: '{proveedor} · firma verificada',
      pasarelaSinFirma: '{proveedor} conectada',
      sinPasarela: 'Sin pasarela',
    },
    errorTarjeta: {
      titulo: 'No pudimos leer el estado de {tema}',
      descripcion: 'Las demás tarjetas están al día. El módulo {modulo} no respondió.',
      descripcionGenerica: 'Las demás tarjetas están al día. Inténtalo de nuevo en un momento.',
    },
    vacio: {
      titulo: 'Tu sitio todavía no vende',
      descripcion: 'Conecta una pasarela, elige qué métodos de pago se ven en la web y define cómo envías. Te guiamos paso a paso.',
      conectarPasarela: 'Conectar Wompi',
      verGuia: 'Ver la guía',
    },
    sinPermiso: {
      titulo: 'No tienes permiso para ver las ventas del sitio',
      descripcion: 'Pide el permiso «Editar sitio web» a un administrador.',
    },
    envios: {
      titulo: 'Tarifas de envío',
      descripcion: 'Las mismas tarifas de Transporte: lo que cambies aquí cambia allá y en el costo que calcula tu sitio.',
      alternativaTitulo: 'Tu plan no incluye Transporte',
      alternativaDescripcion: 'Tu sitio cobra la tarifa plana. Puedes editarla en «Editar opciones» del checkout.',
    },
    checkout: {
      titulo: 'Opciones del checkout',
      descripcion: 'Cómo compran tus clientes en el sitio. Se aplica al publicar los cambios del sitio.',
      guardar: 'Guardar cambios',
      guardado: 'Guardaste las opciones del checkout.',
      error: 'No pudimos guardar: {mensaje}',
      pendienteMigracion: 'Se activa con una actualización pendiente de la base de datos.',
      seccionCompra: 'Compra',
      modo: 'Cómo se ve el checkout',
      modoPasos: 'Por pasos',
      modoUnaPagina: 'Una página',
      tiposEntrega: 'Cómo reciben el pedido',
      entregaRetiro: 'Retiro en tienda',
      entregaPropio: 'Domicilio propio',
      entregaTercero: 'Domicilio de tercero',
      entregaComerAqui: 'Comer aquí',
      tiposEntregaAyuda: 'Elige al menos una.',
      tiposEntregaAyudaRestaurante: 'Elige retiro o domicilio. «Comer aquí» se suma: el cliente pide desde su mesa con el QR.',
      invitado: 'Compra como invitado',
      invitadoAyuda: 'El cliente compra sin crear una cuenta.',
      pedidoMinimo: 'Pedido mínimo',
      pedidoMinimoAyuda: 'Déjalo vacío si no hay mínimo.',
      ventaEnLinea: 'Recibir pedidos en línea',
      ventaEnLineaAyuda: 'Apagado, el sitio muestra el catálogo pero no deja pagar.',
      seccionConfianza: 'Confianza',
      sellos: 'Sellos de confianza',
      sellosAyuda: 'Frases cortas bajo el botón de pagar.',
      agregarSello: 'Agregar sello',
      quitarSello: 'Quitar «{texto}»',
      textoSello: 'Texto del sello {n}',
      logosPago: 'Logos de medios de pago',
      logosPagoAyuda: 'Muestra los logos de los métodos que aceptas.',
      seccionEnvio: 'Envío del sitio',
      seccionEnvioAyuda: 'La tarifa plana se cobra cuando no hay una tarifa por zona de Transporte para la dirección.',
      envioActivo: 'Ofrecer envío',
      tarifaPlana: 'Tarifa plana',
      envioGratisDesde: 'Envío gratis desde',
      envioGratisAyuda: 'Déjalo vacío para no ofrecer envío gratis.',
    },
  },
  tienda: {
    subtitulo: 'Catálogo web, plantillas de producto y reseñas',
    nombreContenido: 'la tienda del sitio',
    pestanas: {
      etiqueta: 'Secciones de la tienda',
      catalogo: 'Catálogo web',
      plantillas: 'Plantillas de producto y categoría',
      resenas: 'Reseñas',
    },
    kpis: {
      etiqueta: 'Catálogo web',
      productosActivos: 'Productos activos',
      categorias: 'Categorías',
      ocultos: 'Ocultos en la web',
      agotados: 'Agotados hoy',
      enSede: 'en {sede}',
    },
    catalogo: {
      sede: 'Sede',
      buscar: 'Buscar producto o SKU',
      filtro: 'Mostrar',
      filtros: { todos: 'Todos', personalizados: 'Con cambios', agotados: 'Agotados', ocultos: 'Ocultos' },
      columnas: { producto: 'Producto', precio: 'Precio web', enWeb: 'En la web', agotado: 'Agotado' },
      precioInventario: 'De Inventario',
      precioPersonalizado: 'Personalizado',
      sinPrecio: 'Sin precio',
      mostrarEnWeb: 'Mostrar {producto} en la web',
      marcarAgotado: 'Marcar {producto} como agotado',
      vacio: 'Aún no tienes productos activos. Crea el primero en Inventario.',
      sinResultados: 'Ningún producto coincide con la búsqueda.',
      irInventario: 'Ir a Inventario',
      editarInventario: 'Editar en Inventario',
      editarInventarioDetalle: 'Nombre, fotos, precio y categoría se editan en Inventario',
      guardado: 'Guardamos el cambio en {sede}.',
      error: 'No pudimos guardar: {mensaje}',
      sinPermisoEditar: 'Solo lectura: pide el permiso «Editar sitio web».',
      enWebCorto: 'En la web',
      agotadoCorto: 'Agotado',
      paginaDe: 'Página {pagina} de {total}',
      anterior: 'Anterior',
      siguiente: 'Siguiente',
    },
    plantillas: {
      descripcion: 'Así se ven el detalle de cada producto, cada categoría, el carrito y la confirmación. Páginas no las lista.',
      columnas: { plantilla: 'Plantilla', direccion: 'Dirección' },
      editar: 'Editar',
      vacio: 'Tu sitio usa las plantillas de detalle de su diseño. Se crean al abrir el editor.',
      soloV2: 'Esta plantilla se edita cuando el sitio pase al editor nuevo.',
      tipos: {
        product_detail: 'Detalle de producto',
        category_detail: 'Detalle de categoría',
        cart: 'Carrito',
        checkout: 'Pago',
        order_confirmation: 'Confirmación del pedido',
        space_detail: 'Detalle de espacio',
        account: 'Cuenta del cliente',
      },
    },
    resenas: {
      autoAprobar: 'Aprobar reseñas automáticamente',
      autoAprobarAyuda: 'Apagado, cada reseña espera tu aprobación antes de salir en el sitio.',
      guardado: 'Guardamos la aprobación de reseñas.',
      error: 'No pudimos guardar: {mensaje}',
      pendientes: '{n} por revisar',
      etiqueta: 'Reseñas de tus productos',
      filtroEstado: 'Estado',
      filtros: { pending: 'Por revisar', approved: 'Aprobadas', rejected: 'Rechazadas', all: 'Todas' },
      estados: { pending: 'Por revisar', approved: 'Aprobada', rejected: 'Rechazada' },
      columnas: { resena: 'Reseña', producto: 'Producto', calificacion: 'Calificación', fecha: 'Fecha', estado: 'Estado' },
      calificacion: '{n} de 5 estrellas',
      compraVerificada: 'Compra verificada',
      sinTexto: 'Sin comentario',
      respuesta: 'Tu respuesta',
      aprobar: 'Aprobar',
      rechazar: 'Rechazar',
      responder: 'Responder',
      editarRespuesta: 'Editar respuesta',
      guardarRespuesta: 'Publicar respuesta',
      cancelar: 'Cancelar',
      respuestaPlaceholder: 'Agradece y responde con amabilidad. Se publica bajo la reseña.',
      aprobada: 'Aprobaste la reseña.',
      rechazada: 'Rechazaste la reseña.',
      respondida: 'Publicaste tu respuesta.',
      errorAccion: 'No pudimos guardar: {mensaje}',
      vacio: {
        pending: 'No tienes reseñas por revisar.',
        approved: 'Aún no apruebas reseñas.',
        rejected: 'No has rechazado reseñas.',
        all: 'Aún no tienes reseñas. Llegan cuando un cliente califica un producto en tu sitio.',
      },
      errorCarga: 'No pudimos cargar las reseñas.',
      soloLectura: 'Solo lectura: pide el permiso «Editar sitio web» para moderar reseñas.',
      verMas: 'Ver la reseña de {autor}',
      detalle: 'Reseña de {autor}',
    },
    sinPermiso: {
      titulo: 'No tienes permiso para ver la tienda del sitio',
      descripcion: 'Pide el permiso «Editar sitio web» a un administrador.',
    },
  },
  sedes: {
    subtitulo: '{total} sucursales · {publicadas} publicadas',
    subtituloMovil: '{publicadas} de {total} publicadas',
    nombreContenido: 'tus sedes',
    irSucursales: 'Ir a Sucursales',
    recargar: 'Recargar',
    vistaPrevia: 'Así lo ve el cliente',
    stockTitulo: '¿De qué sedes sale el stock de la tienda?',
    modo: {
      titulo: '¿Cómo se muestran tus sedes?',
      selector: 'Un sitio con selector de sede',
      selectorDescripcion: '{host} y el cliente elige la sede al entrar o al pagar. Catálogo, precios y stock de la sede elegida.',
      selectorCorto: 'Con selector',
      porSede: 'Un sitio por sede',
      porSedeDescripcion: 'Cada sede tiene su propio sitio ({host}/centro o un dominio propio) con su diseño heredado o propio.',
      porSedeCorto: 'Sitio por sede',
      recomendado: 'Recomendado',
      pendienteMigracion: 'Elegir el modo se activa con una actualización pendiente de la base de datos.',
    },
    tabla: {
      etiqueta: 'Sedes en la web',
      sede: 'Sede',
      enWeb: 'En la web',
      direccion: 'Dirección web',
      horario: 'Horario (de la sucursal)',
      dominioPropioNo: 'Dominio propio: no',
      conectarDominio: 'Conectar dominio',
      noSeMuestra: 'No se muestra a clientes',
      soloStock: 'Solo surte stock web',
      sinHorario: 'Sin horario',
      cerrado: 'cerrado',
      slug: 'Dirección de {sede}',
      slugInvalido: 'Usa minúsculas, números y guiones; algunas palabras están reservadas.',
      slugRepetido: 'Otra sede ya usa esa dirección.',
      slugRequerido: 'Escribe la dirección para publicar la sede.',
      publicar: 'Mostrar {sede} en la web',
      principal: 'Principal',
      editarSede: 'Editar {sede} en la web',
      direccionAyuda: 'Usa minúsculas, números y guiones. Así queda: {ejemplo}',
      dominioPropio: 'Dominio propio',
    },
    hoja: {
      descripcion: 'Qué ve el cliente de esta sede en tu sitio.',
    },
    recargarConfirmar: {
      titulo: '¿Recargar y descartar los cambios?',
      descripcion: 'Tienes {n} cambios sin guardar en tus sedes. Si recargas, se pierden.',
      confirmar: 'Descartar y recargar',
      cancelar: 'Seguir editando',
    },
    aviso: {
      titulo: 'Las sedes se publican como {ejemplo}, no como {incorrecto}',
      descripcion: 'El certificado comodín *.goadmin.io cubre un solo nivel: un sub-subdominio no tendría HTTPS. Para una dirección propia por sede, conecta un dominio (p. ej. norte.{dominio}).',
    },
    stockAyuda: 'Una sede puede surtir la web aunque no se muestre como sede.',
    selector: {
      titulo: '¿Dónde quieres comprar?',
      descripcion: 'Precios y disponibilidad cambian según la sede.',
      ubicacion: 'Usar mi ubicación',
      abiertoHasta: 'Abierto hasta {hora}',
      cerradoAhora: 'Cerrado ahora',
      continuar: 'Continuar',
      vacio: 'Publica al menos una sede para ver el selector.',
    },
    guardado: 'Guardaste las sedes en la web.',
    error: 'No pudimos guardar: {mensaje}',
    errorSlugEnUso: 'La dirección «{slug}» ya la usa otra sede.',
    unaSede: {
      titulo: 'Tienes una sola sucursal',
      descripcion: 'Tu sitio muestra {sede} automáticamente. Cuando abras otra sede, aquí eliges cómo mostrarlas.',
    },
    errorCarga: {
      titulo: 'No pudimos cargar tus sedes',
      descripcion: 'Revisa tu conexión e inténtalo de nuevo.',
    },
    sinPermiso: {
      titulo: 'No tienes permiso para publicar sedes',
      descripcion: 'Pide el permiso «Editar sitio web» a un administrador.',
    },
    dias: {
      monday: 'Lun',
      tuesday: 'Mar',
      wednesday: 'Mié',
      thursday: 'Jue',
      friday: 'Vie',
      saturday: 'Sáb',
      sunday: 'Dom',
    },
    masOpciones: 'Más opciones de sedes',
    verVistaPrevia: 'Ver cómo lo ve el cliente',
    verStock: 'Sedes que surten la tienda',
  },
} as const;

type Arbol = { readonly [k: string]: string | Arbol };

export function textoVentasCanonico(clave: string): string | undefined {
  let nodo: string | Arbol | undefined = TEXTOS_VENTAS as unknown as Arbol;
  for (const parte of clave.split('.')) {
    if (typeof nodo !== 'object' || nodo === null) return undefined;
    nodo = (nodo as Arbol)[parte];
  }
  return typeof nodo === 'string' ? nodo : undefined;
}

export type TraductorVentas = (clave: string, valores?: Record<string, string | number>) => string;

/**
 * Textos de `sitioWeb.ventas.<clave>` en el idioma activo, con el español
 * canónico de respaldo. `clave` va sin el prefijo: «ventas.temas.envios»,
 * «sedes.tabla.sede», «tienda.pestanas.catalogo».
 */
export function useTextosVentas(): TraductorVentas {
  const t = useTranslations('sitioWeb');
  return useCallback(
    (clave: string, valores?: Record<string, string | number>) => {
      const completa = `ventas.${clave}`;
      if (t.has(completa)) return t(completa, valores);
      const canon = textoVentasCanonico(clave);
      return canon === undefined ? clave : interpolar(canon, valores);
    },
    [t],
  );
}
