'use client';

/**
 * Textos del área «configuracion» del módulo Sitio web (`sitioWeb.configuracion.*`):
 * Configuración del sitio (B/12) y Carta (B/13). `TEXTOS_CONFIGURACION` es el
 * español canónico y la fuente de configuracion.es.json; mientras el integrador
 * fusiona las claves en messages/*.json, `useTextosConfiguracion` muestra este
 * español en vez de la clave cruda (el patrón de `useTextosComun`).
 */
import { useCallback } from 'react';
import { useTranslations } from 'next-intl';
import { interpolar } from '../ui/textos';

export const TEXTOS_CONFIGURACION = {
  enConfiguracionGeneral: {
    titulo: 'El sitio web se configura en su módulo',
    descripcion: 'Datos del negocio, legales, código, idioma y mantenimiento están en Sitio web › Configuración. Diseño, páginas y ventas, en sus pantallas del módulo.',
    configuracion: 'Datos, legales y ajustes',
    resumen: 'Estado del sitio y publicación',
    abrir: 'Abrir',
  },
  pagina: {
    titulo: 'Configuración del sitio',
    subtitulo: 'Datos del negocio, legales y ajustes avanzados',
    nombreContenido: 'la configuración del sitio',
    recargar: 'Recargar',
    verSitio: 'Ver sitio',
    indice: 'Secciones de la configuración',
  },
  secciones: {
    datos: 'Datos del negocio',
    legales: 'Legales',
    codigo: 'Código y píxeles',
    chat: 'Chat en el sitio',
    idioma: 'Idioma y moneda',
    mantenimiento: 'Mantenimiento',
    peligro: 'Zona de peligro',
  },
  barra: {
    cambios: '{n} cambios',
    unCambio: '1 cambio',
    mensaje: 'Tienes cambios sin guardar',
    guardar: 'Guardar cambios',
    descartar: 'Descartar',
    invalido: 'Revisa los campos marcados antes de guardar.',
    guardado: 'Cambios guardados',
    guardadoIdentidad: 'Nombre, logo y favicon se ven en el sitio cuando publiques.',
  },
  estados: {
    vacioTitulo: 'Completa los datos de tu negocio',
    vacioDescripcion: 'Tomamos nombre, logo y contacto de Organización › Información. Revísalos antes de publicar.',
    vacioAccion: 'Usar datos de la organización',
    errorGuardarTitulo: 'No pudimos guardar los cambios',
    errorGuardarDescripcion: 'Tus cambios siguen aquí. Revisa tu conexión y vuelve a guardar.',
    reintentar: 'Reintentar',
    volverCambios: 'Volver a mis cambios',
    sinPermisoTitulo: 'No tienes permiso para cambiar estos ajustes',
    sinPermisoDescripcion: 'Los scripts y los legales requieren el permiso «Editar sitio web». Pídeselo a un administrador.',
    pendienteTitulo: 'Algunos ajustes llegan con la próxima actualización',
    pendienteDescripcion: 'Contacto del sitio, idioma, mantenimiento y código a medida se activan cuando se aplique la actualización del sitio web. Lo demás ya se guarda.',
    pendienteGuardar: 'Ese ajuste se activa con la próxima actualización del sitio web.',
    conflicto: 'Otra persona guardó cambios en el sitio. Recarga para ver la última versión.',
  },
  datos: {
    descripcion: 'Lo que ven tus clientes en el encabezado, el pie y Google.',
    nombre: 'Nombre en el sitio',
    correo: 'Correo de contacto',
    telefono: 'Teléfono',
    whatsapp: 'WhatsApp del botón flotante',
    saludo: 'Saludo prellenado',
    saludoAyuda: 'Abre wa.me con un saludo prellenado.',
    saludoAyudaInicio: 'Abre wa.me con',
    saludoEnlace: 'un saludo prellenado',
    saludoDescripcion: 'Es el mensaje que aparece escrito cuando tu cliente toca el botón de WhatsApp. Lo puede cambiar antes de enviarlo.',
    saludoAyudaDialogo: 'Se guarda con «Guardar cambios». Déjalo vacío para abrir el chat sin mensaje.',
    saludoAplicar: 'Usar este saludo',
    saludoPlaceholder: 'Hola, quiero hacer un pedido',
    notaSucursal: 'Dirección y horario se muestran por sede y se leen de Organización › Sucursales.',
    irSucursales: 'Ir a Sucursales',
    publicarNota: 'Nombre, logo y favicon se ven en el sitio cuando publiques.',
    deOrganizacion: 'De Organización › Información',
    errores: {
      nombreRequerido: 'Escribe el nombre que verán tus clientes.',
      correoRequerido: 'Escribe un correo de contacto.',
      correoInvalido: 'Escribe un correo válido, por ejemplo hola@tumarca.com.',
      whatsappInvalido: 'Usa solo números, espacios y el signo +.',
    },
  },
  legales: {
    descripcion: 'Obligatorios para vender en línea (Ley 1480 y 1581 de Colombia). También los usan el agente de voz y el CRM para pedir autorización de datos.',
    publicado: 'Publicado · {fecha}',
    publicadoSinFecha: 'Publicado',
    borrador: 'Borrador',
    falta: 'Falta',
    editar: 'Editar',
    generar: 'Generar con asistente',
    revisar: 'Revisar y publicar',
    generando: 'Creando la página…',
    creado: 'Creamos la página «{titulo}». Complétala y publícala desde el editor.',
    errorCrear: 'No pudimos crear la página. Inténtalo de nuevo.',
    avisoTitulo: 'Sin política de tratamiento de datos no se activan el agente de voz ni los formularios de CRM',
    avisoDescripcion: 'La pedimos para registrar la autorización del cliente (Ley 1581). El asistente la genera con los datos de tu organización.',
    avisoAccion: 'Generar ahora',
    errorCargar: 'No pudimos leer las páginas legales.',
    asistenteTitulo: 'Generar «{titulo}»',
    asistenteDescripcion: 'Creamos la página en tu sitio, fuera del menú y con el pie «Legales». Luego la completas en el editor con los datos de tu negocio y la publicas.',
    asistenteDatos: 'Datos que usaremos',
    asistenteRazon: 'Razón social',
    asistenteCorreo: 'Correo para solicitudes',
    asistenteCrear: 'Crear página',
  },
  codigo: {
    descripcion: 'Para medir anuncios usa los campos de Analítica › Píxeles. Aquí solo código a medida.',
    irPixeles: 'Ir a Analítica',
    avisoTitulo: 'El código a medida se ejecuta en cada visita a tu sitio',
    avisoDescripcion: 'Puede romper el checkout o robar datos si viene de una fuente no confiable. Cada bloque queda con su autor y su fecha.',
    vacio: 'Aún no tienes código a medida.',
    anadir: 'Añadir código',
    detalleTodas: 'Todas las páginas',
    detalle: '{posicion} · {alcance}',
    detalleAutor: '{posicion} · {alcance} · añadido por {autor}',
    head: 'En <head>',
    body: 'Antes de </body>',
    legado: 'Código anterior (solo lectura). Pasa los píxeles a Analítica y quítalo de aquí.',
    activar: 'Activar «{nombre}»',
    editar: 'Editar',
    quitar: 'Quitar',
    quitarTitulo: '¿Quitar «{nombre}»?',
    quitarDescripcion: 'Deja de ejecutarse en tu sitio cuando guardes los cambios.',
    dialogoNuevo: 'Añadir código',
    dialogoEditar: 'Editar código',
    dialogoDescripcion: 'Pega solo código de fuentes en las que confías. Se ejecuta en el navegador de tus clientes.',
    nombre: 'Nombre',
    nombrePlaceholder: 'Chat de soporte externo',
    alcance: 'Dónde se carga',
    alcanceTodas: 'Todas las páginas',
    alcanceRuta: 'Solo una página',
    ruta: 'Dirección de la página',
    rutaPlaceholder: '/gracias',
    posicion: 'Posición',
    contenido: 'Código',
    guardarDialogo: 'Listo',
    errores: {
      nombre: 'Escribe un nombre para reconocerlo.',
      ruta: 'Escribe una dirección que empiece con /.',
      codigo: 'Pega el código.',
    },
  },
  chat: {
    mostrar: 'Mostrar el botón de chat',
    mostrarDescripcion: 'Los mensajes llegan a Chat › Bandeja con el canal «Sitio web». Requiere el módulo Chat.',
    sinModulo: 'Tu plan no incluye el módulo Chat.',
    configurar: 'Configurar en Chat',
    reservasTitulo: 'Reservas web',
    reservasDescripcion: 'Tus clientes reservan mesa desde el sitio. Horarios, turnos y reglas se configuran en POS.',
    reservasIr: 'Ir a POS › Reservas de mesas',
  },
  idioma: {
    idioma: 'Idioma del sitio',
    idiomaDescripcion: 'Textos del checkout, correos y botones.',
    moneda: 'Moneda',
    monedaDescripcion: 'Los precios salen del inventario en esta moneda.',
    monedaSinBase: 'Sin moneda base',
    idiomas: { 'es-CO': 'Español (Colombia)', en: 'Inglés', fr: 'Francés', pt: 'Portugués' },
    monedas: { COP: 'COP · peso colombiano', USD: 'USD · dólar estadounidense', EUR: 'EUR · euro', MXN: 'MXN · peso mexicano' },
  },
  mantenimiento: {
    titulo: 'Sitio en construcción',
    descripcion: 'Los visitantes ven una página «Volvemos pronto» con tu logo y WhatsApp; tú sigues viendo el sitio con tu sesión.',
  },
  peligro: {
    despublicar: 'Despublicar el sitio',
    despublicarDescripcion: 'Nadie podrá verlo hasta que lo publiques de nuevo. Pedidos y reservas web se detienen.',
    despublicarBoton: 'Despublicar',
    republicar: 'Volver a publicar',
    republicarDescripcion: 'Tu sitio está despublicado: nadie lo ve. Vuelve a publicarlo cuando quieras.',
    eliminar: 'Eliminar el sitio',
    eliminarDescripcion: 'Borra páginas, diseño y ajustes. Tus productos, pedidos y dominios no se borran.',
    eliminarBoton: 'Eliminar sitio',
    despublicarTitulo: '¿Despublicar tu sitio?',
    despublicarConfirmacion: '{host} mostrará «Sitio no disponible». Los pedidos y reservas web se detienen hasta que lo publiques de nuevo.',
    eliminarTitulo: '¿Eliminar tu sitio web?',
    eliminarConfirmacion: 'Se borrarán páginas, diseño y ajustes de {host}. Tus productos, pedidos, clientes y dominios se conservan. Escribe «{subdominio}» para confirmar.',
    tuSitio: 'tu sitio',
    despublicado: 'Despublicaste el sitio',
    republicado: 'Tu sitio está publicado de nuevo',
    eliminado: 'Eliminaste el sitio. Puedes crearlo de nuevo desde el Resumen.',
    errorPublicar: 'No pudimos cambiar la publicación del sitio.',
    errorEliminar: 'No pudimos eliminar el sitio.',
    sinPermiso: 'Necesitas el permiso «Publicar sitio web».',
    sinSubdominio: 'Tu sitio aún no tiene subdominio.',
  },
  movil: {
    volver: 'Volver a la configuración',
    resumen: {
      datos: '{datos}',
      datosVacio: 'Sin completar',
      legalesCargando: 'Revisando documentos…',
      legalesFalta: '1 documento falta',
      legalesFaltan: '{n} documentos faltan',
      legalesCompletos: 'Todos los documentos',
      codigoNinguno: 'Sin código a medida',
      codigoUno: '1 script activo',
      codigoVarios: '{n} scripts activos',
      activo: 'Activo',
      inactivo: 'Inactivo',
      idioma: '{idioma} · {moneda}',
      enConstruccion: 'Sitio en construcción',
      publicado: 'Sitio publicado',
      noPublicado: 'Sitio sin publicar',
      peligro: 'Despublicar o eliminar',
    },
  },
  carta: {
    titulo: 'Carta',
    subtitulo: '{n} cartas · se muestran según la hora y la sede',
    subtituloUna: '1 carta · se muestra según la hora y la sede',
    nombreContenido: 'tus cartas',
    recargar: 'Recargar',
    cartaQr: 'Carta QR',
    nuevaCarta: 'Nueva carta',
    verPublica: 'Ver carta pública',
    bannerAhora: 'Ahora ({momento}) tus clientes ven: {detalle}',
    bannerNinguna: 'Ahora ({momento}) ninguna carta está a la vista en tus sedes.',
    bannerEn: '{cartas} en {sede}',
    notaOrden: 'Si dos cartas coinciden en hora y sede, se muestran como pestañas en el orden de esta lista (arrastra para cambiarlo).',
    visibleAhora: 'Visible ahora',
    fueraHorario: 'Fuera de horario',
    inactiva: 'Pausada',
    pdf: 'PDF',
    todasLasSedes: 'Todas las sedes',
    sedesN: '{n} sedes',
    categorias: '{n} categorías',
    unaCategoria: '1 categoría',
    productos: '{n} productos',
    unProducto: '1 producto',
    todosLosDias: 'Todos los días',
    todoElDia: 'todo el día',
    sinHorario: 'Sin horario: no se muestra',
    editar: 'Editar',
    duplicar: 'Duplicar',
    verComoCliente: 'Ver como cliente',
    eliminar: 'Eliminar',
    mover: 'Arrastra para ordenar o usa Alt + flechas',
    eliminarTitulo: '¿Eliminar «{nombre}»?',
    eliminarDescripcion: 'Tu sitio deja de mostrar esta carta. Los productos y precios del inventario no cambian.',
    eliminada: 'Eliminaste la carta',
    duplicada: 'Creamos «{nombre}»',
    copia: '{nombre} (copia)',
    vacioTitulo: 'Aún no tienes cartas',
    vacioDescripcion: 'Crea la «Carta principal» con todas tus categorías del inventario; luego separa Desayuno, Almuerzo o Bar si lo necesitas.',
    vacioAccion: 'Crear carta principal',
    principal: 'Carta principal',
    errorTitulo: 'No pudimos cargar tus cartas',
    errorDescripcion: 'Tu carta pública sigue funcionando con la última versión guardada.',
    sinPermisoTitulo: 'No tienes permiso para editar la carta',
    sinPermisoDescripcion: 'Pide el permiso «Editar sitio web» a un administrador.',
    noRestauranteTitulo: 'La carta es solo para restaurantes',
    noRestauranteDescripcion: 'Tu organización no tiene sedes de restaurante. Los productos de tu tienda se gestionan en Tienda.',
    irResumen: 'Ir al Resumen',
    implicitaTitulo: 'Hoy tu sitio muestra una sola carta con todo el inventario',
    implicitaDescripcion: 'Las cartas por horario (Desayuno, Almuerzo, Bar) se activan con la próxima actualización del sitio web. Mientras tanto, ajusta precios web y agotados por sede.',
    pendiente: 'Las cartas por horario se activan con la próxima actualización del sitio web.',
    errorAccion: 'No pudimos completar la acción. Inténtalo de nuevo.',
    errorOrden: 'No pudimos guardar el orden. Lo dejamos como estaba.',
    vistaLateral: {
      titulo: 'Vista previa',
      sinCartas: 'A esta hora no hay ninguna carta a la vista en esta sede.',
      destacado: 'Destacado',
      noDisponible: 'La vista previa llega con la próxima actualización del sitio web.',
    },
    dialogo: {
      titulo: 'Nueva carta',
      descripcion: 'Luego eliges su horario, sedes y categorías.',
      nombre: 'Nombre',
      nombrePlaceholder: 'Almuerzo',
      icono: 'Icono',
      empezar: 'Empezar con',
      todas: 'Todas las categorías',
      vacia: 'Ninguna categoría',
      duplicar: 'Copia de otra carta',
      deCual: 'Copiar de',
      crear: 'Crear carta',
      nombreRequerido: 'Escribe el nombre de la carta.',
    },
    iconos: {
      desayuno: 'Desayuno',
      almuerzo: 'Almuerzo',
      cena: 'Cena',
      principal: 'Principal',
      bar: 'Bar',
      postres: 'Postres',
      general: 'General',
    },
    dias: { '1': 'Lun', '2': 'Mar', '3': 'Mié', '4': 'Jue', '5': 'Vie', '6': 'Sáb', '7': 'Dom' },
    diasLargos: { '1': 'lunes', '2': 'martes', '3': 'miércoles', '4': 'jueves', '5': 'viernes', '6': 'sábado', '7': 'domingo' },
    movil: {
      todas: 'todas',
    },
  },
  porSede: {
    descripcion: 'Qué productos de esta carta salen en cada sede, a qué precio web y si están agotados. Se guarda junto con el resto de la carta y sale en la web al guardar: no pasa por Publicar.',
    sede: 'Sede',
    elegirSede: 'Elige una sede',
    categoria: 'Categoría de la carta',
    buscar: 'Buscar producto',
    filtrar: 'Filtrar productos',
    filtros: { todos: 'Todos', personalizados: 'Personalizados', agotados: 'Agotados', ocultos: 'Ocultos' },
    col: { producto: 'Producto', enWeb: 'En la web', precio: 'Precio web', origen: 'Origen', agotado: 'Agotado' },
    sinPrecio: 'Sin precio',
    base: 'Base: {precio}',
    heredado: 'Como la principal',
    personalizado: 'Personalizado',
    restablecer: 'Restablecer',
    agotado: 'Agotado',
    disponible: 'Disponible',
    hastaOpcional: 'Hasta (opcional)',
    editado: 'sin guardar',
    soloLectura: 'Solo puedes ver estos ajustes. Pide el permiso de editar el sitio para cambiarlos.',
    pie: 'Precio web vacío = el precio vigente de Inventario en esa sede.',
    sinSedesTitulo: 'Esta carta no sale en ninguna sede',
    sinSedesDescripcion: 'Elige en qué sedes se muestra en la pestaña Contenido.',
    sinCategoriasTitulo: 'Aún no hay categorías en esta carta',
    sinCategoriasDescripcion: 'Añade una categoría en la pestaña Contenido.',
    categoriaNuevaTitulo: 'Guarda la carta para ver esta categoría',
    categoriaNuevaDescripcion: 'La categoría se añadió y aún no se ha guardado.',
    vacioTitulo: 'Esta categoría no tiene productos activos',
    vacioDescripcion: 'Crea o activa productos en Inventario.',
    errorTitulo: 'No pudimos cargar los productos de la sede',
    errorDescripcion: 'Revisa tu conexión e inténtalo de nuevo.',
    lote: {
      titulo: 'Toda la categoría',
      boton: 'Acciones para {categoria} en {sede}',
      mostrar: 'Mostrar todos en la web',
      ocultar: 'Ocultar todos de la web',
      agotar: 'Marcar todos como agotados',
      disponible: 'Marcar todos como disponibles',
      restablecer: 'Volver a como la principal',
    },
    aria: {
      enWeb: '{producto} en la web',
      precio: 'Precio web de {producto}',
      restablecer: 'Restablecer {producto} como la principal',
      agotado: '{producto} agotado',
      hasta: '{producto} agotado hasta',
    },
  },
  variantes: {
    variantes: 'Variantes',
    extras: 'Extras',
    mostrar: 'Mostrar en la carta',
    nOpciones: '{n} opciones',
    editarInventario: 'Editar en inventario',
    vacioTitulo: 'Los productos de esta carta no tienen variantes ni extras',
    vacioDescripcion: 'Agrégalos en Inventario y vuelve aquí para elegir cuáles se muestran.',
    pendienteTitulo: 'Elegir variantes y extras se activa con una actualización pendiente',
    pendienteDescripcion: 'Por ahora la carta muestra todas las variantes y extras de cada producto.',
  },
  detalle: {
    nombreContenido: 'la carta',
    recargar: 'Recargar',
    vistaPrevia: 'Vista previa',
    guardar: 'Guardar',
    visibleEn: 'Visible ahora en {sedes}',
    fueraDeHorario: 'Fuera de horario ahora',
    noEncontradaTitulo: 'No encontramos esta carta',
    noEncontradaDescripcion: 'Puede que la hayan eliminado. Vuelve a la lista de cartas.',
    volverCarta: 'Volver a Carta',
    pestanas: { contenido: 'Contenido', sede: 'Por sede', variantes: 'Variantes y extras', horario: 'Horario' },
    pestanasEtiqueta: 'Partes de la carta',
    cuando: 'Cuándo se muestra',
    noSeMuestra: 'No se muestra',
    anadirFranja: 'Añadir franja',
    quitarFranja: 'Quitar franja',
    desde: 'Desde',
    hasta: 'Hasta',
    sedes: 'En qué sedes',
    sedesTodas: 'Todas',
    sedesElegir: 'Elegir sedes',
    sedesAlMenosUna: 'Elige al menos una sede.',
    pdf: 'PDF de la carta (opcional)',
    pdfDescripcion: 'Si lo subes, el sitio ofrece «Descargar carta». La carta interactiva sigue siendo la principal.',
    subirPdf: 'Subir PDF',
    cambiarPdf: 'Cambiar PDF',
    quitarPdf: 'Quitar PDF',
    verPdf: 'Ver PDF',
    subiendo: 'Subiendo…',
    errorPdf: 'No pudimos subir el PDF. Usa un archivo PDF de menos de 10 MB.',
    categorias: 'Categorías de esta carta',
    anadirCategoria: 'Añadir categoría',
    notaCategorias: 'Arrastra para ordenar. Los productos salen de Inventario › Categorías; precios y modificadores no se editan aquí.',
    productosN: '{n} productos',
    unProducto: '1 producto',
    sinProductos: 'Esta categoría no tiene productos activos en el inventario.',
    alGuardar: 'Sus productos aparecen al guardar la carta.',
    sinCategorias: 'Esta carta aún no tiene categorías. Añade la primera.',
    quitarCategoria: 'Quitar de la carta',
    destacado: 'Destacado',
    ocultoEnCarta: 'Oculto en esta carta',
    destacar: 'Destacar «{nombre}»',
    quitarDestacado: 'Quitar destacado de «{nombre}»',
    ocultar: 'Ocultar «{nombre}» en esta carta',
    mostrar: 'Mostrar «{nombre}» en esta carta',
    editarInventario: 'Editar en inventario',
    delInventario: 'del inventario',
    sinPrecio: 'Sin precio',
    leyenda: 'Etiquetas de dieta y alérgenos (Inventario › Etiquetas):',
    sinEtiquetas: 'Aún no hay etiquetas de dieta. Créalas en Inventario › Etiquetas con el tipo «Dieta» o «Alérgeno».',
    dialogoCategoria: 'Añadir categoría',
    dialogoCategoriaDescripcion: 'Sus productos aparecen con el precio del inventario.',
    categoria: 'Categoría',
    todasAnadidas: 'Ya añadiste todas las categorías del inventario.',
    anadir: 'Añadir',
    variantesTitulo: 'Variantes y extras',
    variantesDescripcion: 'Elige qué variantes (tamaños) y qué extras (modificadores) se muestran en esta carta. Sus nombres y precios se editan en Inventario.',
    variantesIr: 'Ir a Inventario',
    sedeTitulo: 'Disponibilidad y precio web por sede',
    guardado: 'Guardamos la carta',
    errorGuardar: 'No pudimos guardar la carta. Tus cambios siguen aquí.',
    implicita: 'Esta es la carta que tu sitio muestra hoy. Sus categorías y horario se editan cuando se activen las cartas por horario.',
  },
  qr: {
    titulo: 'Carta QR',
    subtitulo: '{sede} · {mesas} mesas en {zonas} zonas',
    subtituloSinMesas: '{sede} · sin mesas',
    copiarGeneral: 'Copiar enlace general',
    copiado: 'Copiamos el enlace de la carta',
    descargar: 'Descargar PDF para imprimir',
    descargarN: 'Descargar PDF ({n} códigos)',
    descargarUno: 'Descargar el PDF de este código',
    sede: 'Sede',
    unQrPor: 'Un QR por',
    mesa: 'Mesa',
    zona: 'Zona',
    alEscanear: 'Al escanear',
    pedir: 'Ver la carta y pedir a la mesa',
    ver: 'Solo ver la carta',
    sinZona: 'Sin zona',
    asiImprime: 'Así se imprime (A6, 4 por hoja)',
    asiImprimeDescripcion: 'Lleva el nombre de tu sitio, la mesa y la zona. Si mueves una mesa de zona, el QR sigue sirviendo: apunta a la mesa, no a la zona.',
    zonaNota: 'El QR por zona abre la carta general de la sede: el pedido a la mesa necesita el QR de cada mesa.',
    sinMesasTitulo: 'Esta sede no tiene mesas',
    sinMesasDescripcion: 'Crea las mesas y zonas en el punto de venta; aquí aparecen solas.',
    irMesas: 'Ir a POS › Mesas',
    sinSitioTitulo: 'Tu sitio aún no tiene dirección',
    sinSitioDescripcion: 'Elige un subdominio o conecta un dominio para que los códigos abran tu carta.',
    irDominios: 'Ir a Dominios',
    nombreContenido: 'las mesas',
    escanea: 'Escanea para ver la carta y pedir',
    escaneaVer: 'Escanea para ver la carta',
  },
  vistaPrevia: {
    titulo: 'Vista previa de la carta',
    verComo: 'Ver como',
    sede: 'Sede',
    dia: 'Día',
    hora: 'Hora',
    dispositivo: 'Dispositivo',
    escritorio: 'Escritorio',
    celular: 'Celular',
    sinCarta: 'No hay carta a esta hora',
    sinCartaDescripcion: 'Ninguna carta de esta sede está a la vista ese día a esa hora.',
    pedir: 'Pedir a la mesa',
    agotado: 'Agotado',
    descargar: 'Descargar carta',
    noDisponible: 'La vista previa por hora llega con la próxima actualización del sitio web.',
    nombreContenido: 'la vista previa',
    tuMarca: 'Tu marca',
  },
} as const;

type Arbol = { [k: string]: string | Arbol };

export function textoConfiguracionCanonico(clave: string): string | undefined {
  let nodo: string | Arbol | undefined = TEXTOS_CONFIGURACION as unknown as Arbol;
  for (const parte of clave.split('.')) {
    if (typeof nodo !== 'object' || nodo === null) return undefined;
    nodo = (nodo as Arbol)[parte];
  }
  return typeof nodo === 'string' ? nodo : undefined;
}

export type TraductorConfiguracion = (clave: string, valores?: Record<string, string | number>) => string;

/** Textos de `sitioWeb.configuracion.<clave>` en el idioma activo, con el español canónico de respaldo. */
export function useTextosConfiguracion(): TraductorConfiguracion {
  const t = useTranslations('sitioWeb');
  return useCallback(
    (clave: string, valores?: Record<string, string | number>) => {
      const completa = `configuracion.${clave}`;
      if (t.has(completa)) return t(completa, valores);
      const canon = textoConfiguracionCanonico(clave);
      return canon === undefined ? clave : interpolar(canon, valores);
    },
    [t],
  );
}
